### ISSUE TITLE
[backport] nova-compute - vTPM needs additional binary

### ISSUE THREAD

**Issue by rrmichel** [osism/issues#1008]
Can you pls backport the following change: [https://review.opendev.org/c/openstack/kolla/+/916767](https://review.opendev.org/c/openstack/kolla/+/916767)

We need to build instances with [vTPM](https://docs.openstack.org/nova/latest/admin/emulated-tpm.html) support and right now the nova containers are missing binarys. 

Thanks!

**Comment by berendt** [comment]
* stable/2023.1: https://review.opendev.org/c/openstack/kolla/+/916768
* stable/2023.2: https://review.opendev.org/c/openstack/kolla/+/916767
