### ISSUE TITLE
Create a comparison matrix between features Neutron + OVS and Neutron + OVN

### ISSUE THREAD

**Issue by berendt** [osism/issues#106]

**Comment by fkr** [comment]
Linked this issue in the related item on the team 1 board.

**Comment by fkr** [comment]
https://github.com/SovereignCloudStack/Docs/pull/44

**Comment by berendt** [comment]
Next SCS discussion: 14.03.

**Comment by berendt** [comment]
The PR at SCS is almost finished. I'll close this here since there is nothing more to do here.
