### ISSUE TITLE
[bug] Unable to deploy nova

### ISSUE THREAD

**Issue by scoopex** [osism/issues#1062]
### OSISM release version

7.0.4

### What's the problem?

When deploying nova with the current [deployment state](https://github.com/SovereignCloudStack/hardware-landscape/tree/rollout-services) (a05959) the nova deployment fails with the following error message:

Executing [step 8 of the deployment guide ](https://osism.tech/docs/guides/deploy-guide/services/openstack)
```
$ osism apply nova

....
TASK [nova-cell : Check nova keyring file] *************************************
fatal: [st01-comp-r01-u09 -> localhost]: FAILED! => 
  msg: No file was found when using first_found.
fatal: [st01-comp-r01-u11 -> localhost]: FAILED! => 
  msg: No file was found when using first_found.
fatal: [st01-comp-r01-u13 -> localhost]: FAILED! => 
  msg: No file was found when using first_found.
fatal: [st01-comp-r01-u15 -> localhost]: FAILED! => 
  msg: No file was found when using first_found.
```
Where is the nova ceph keyring created?
Does anything else need to be configured here, or is configuration/documentation missing?

### References to existing reports

References to existing bug reports, mailing lists, ...

### Severity

medium

### Urgency

medium

**Comment by berendt** [comment]
You have to remove `ceph_nova_keyring: ceph.client.nova.keyring` from `environments/kolla/configuration.yml`.

**Comment by scoopex** [comment]
Done, that helped!
It's in the [upgrade notes](https://osism.tech/docs/release-notes/osism-7#upgrade-notes), sorry about that!
