### ISSUE TITLE
[bug] Unable to deploy prometheus

### ISSUE THREAD

**Issue by scoopex** [osism/issues#1063]
### OSISM release version

7.0.4

### What's the problem?

When deploying prometheus with the current [deployment state](https://github.com/SovereignCloudStack/hardware-landscape/tree/rollout-services) (a05959) the  deployment fails with the following error message:

```
$ osism apply prometheus
....

TASK [prometheus : Creating prometheus database user and setting permissions] ***
failed: [st01-comp-r01-u09] (item=st01-ctl-r01-u27) => changed=false 
  action: mysql_user
  ansible_loop_var: item
  item:
    key: '0'
    value:
      hosts:
      - st01-ctl-r01-u27
      - st01-ctl-r01-u28
      - st01-ctl-r01-u29
  msg: 'unable to connect to database, check login_user and login_password are correct or /var/lib/ansible/.my.cnf has the credentials. Exception message: (2003, "Can''t connect to MySQL server on ''api-int.int1.landscape.sovereignit.de'' ([Errno 101] Network is unreachable)")'
```

The listed node is capable to connect form the view of the node:

```
dragon@st01-ctl-r01-u27:~$ dig +short api-int.int1.landscape.sovereignit.de
10.10.21.200
dragon@st01-ctl-r01-u27:~$ grep api-int.int1.landscape.sovereignit.de /etc/hosts
10.10.21.200 api-int.int1.landscape.sovereignit.de api-int
dragon@st01-ctl-r01-u27:~$ nc -v 10.10.21.200 3306
Connection to 10.10.21.200 3306 port [tcp/mysql] succeeded!
5.5.5-10.11.7-MariaDB-1:10.11.7+maria~ubu2204-log��:*e>E#y\��!��CuF>DzZ2*{P]mysql_native_password


dragon@st01-comp-r01-u09:~$ dig +short api-int.int1.landscape.sovereignit.de
10.10.21.200
dragon@st01-comp-r01-u09:~$ grep api-int.int1.landscape.sovereignit.de /etc/hosts
10.10.21.200 api-int.int1.landscape.sovereignit.de api-int
dragon@st01-comp-r01-u09:~$ nc -v 10.10.21.200 3306
Connection to 10.10.21.200 3306 port [tcp/mysql] succeeded!
5.5.5-10.11.7-MariaDB-1:10.11.7+maria~ubu2204-log��:*e>E#y\��!��CuF>DzZ2*{P]mysql_native_password


```

### References to existing reports

References to existing bug reports, mailing lists, ...

### Severity

low

### Urgency

low

**Comment by berendt** [comment]
You have to check the connection from inside the kolla_toolbox container.

**Comment by scoopex** [comment]
Upgraded to 7.0.5, and it looks not better  (same error).

Performing a connection test in the "kolla_toolbox" container show that it uses a outdated configuration:
(should be 10.10.21.200, i changed this a few days ago)
```
(kolla-toolbox)[root@st01-comp-r01-u09 /]# netcat -v api-int.int1.landscape.sovereignit.de 3306
netcat: connect to api-int.int1.landscape.sovereignit.de (192.168.32.9) port 3306 (tcp) failed: Network is unreachable
```

Restarting "kolla_toolbox" helped to fix that problem. Probably /etc/hosts was outdated.
From my point of view the problem seems to be solved.

Probably it is useful to make the suggestion in the documentation that probaly changing the loadbalancer settings and/or the /etc/hosts content requires a restart of the containers (when we cannot eliminate this manual step entirely). 

There are also warnings in the console which might be remarkable:
```
[WARNING]: Skipped '/opt/configuration/environments/kolla/files/overlays/promet
heus/prometheus.yml.d' path due to this access issue: '/opt/configuration/envir
onments/kolla/files/overlays/prometheus/prometheus.yml.d' is not a directory
```

**Comment by scoopex** [comment]
From my point of view this topic should be solved now.
