### ISSUE TITLE
Ansible version too old for handling @cert-authority via ansible.builtin.known_hosts module

### ISSUE THREAD

**Issue by fzakfeld** [osism/issues#1074]
We are using a `@cert-authority` for our SSH host keys. The `known_hosts` role in `ansible-collection-common` supports defining the CA via a host_var, but the current release 7.1.0 is still at ansible version 2.16.8, which doesn't support this properly.

A fix to this got introduced in the 2.17-stable release:
https://github.com/ansible/ansible/pull/70340/files
https://github.com/ansible/ansible/blob/v2.17.1/changelogs/CHANGELOG-v2.17.rst

This issue is not super urgent to us, just not ideal. It would be great if we can see at least ansible 2.17 in the next release to target this issue.

**Comment by berendt** [comment]
No problem. I can bump to 2.17 with the next release. Feel free to use osism-ansible:latest, this already runs on 2.17. You can overwrite the version of osism-ansible via environments/manager/images.yml.

**Comment by berendt** [comment]
This will be fixed with https://github.com/osism/release/pull/1492.
