### ISSUE TITLE
kolla: backport Neutron OVN VPNasS for 2024.1

### ISSUE THREAD

**Issue by berendt** [osism/issues#1082]
* https://review.opendev.org/c/openstack/kolla-ansible/+/924575
* https://review.opendev.org/c/openstack/kolla/+/924302

Related to osism/issues#1073

**Comment by sowabdoul** [comment]
Hi @berendt, 
Could you please tell us the planned timeline for production-ready OVN VPNaaS support in Kolla-Ansible?
We are eagerly waiting for this feature in the stable branch.
