### ISSUE TITLE
[bug] CIAB does not deploy successfully / problems with kubernetes-dashboard

### ISSUE THREAD

**Issue by scoopex** [osism/issues#1083]
### OSISM release version

latest

### What's the problem?

It seems that the kubernetes-dashboard play is not available anymore:
(according to /var/log/install-cloud-in-a-box.log)
```
deploy | + osism apply kubernetes-dashboard
deploy | WARNING: OSISM CLI should not be used as root user
deploy | 
deploy | 2024-07-22 08:41:50 | INFO     | Task cbd4d748-83e4-42fb-ba0f-45dad86becf6 (kubernetes-dashboard) was prepared for execution.
deploy | 2024-07-22 08:41:50 | INFO     | It takes a moment until task cbd4d748-83e4-42fb-ba0f-45dad86becf6 (kubernetes-dashboard) has been started and output is visible here.
.....
deploy | ERROR: service kubernetes-dashboard in environment kubernetes not available
```

Probably the installation is moved to a more general playbook.

### References to existing reports

References to existing bug reports, mailing lists, ...

### Severity

low

### Urgency

medium

**Comment by berendt** [comment]
This works after release of 7.1.1.

**Comment by kayamax** [comment]
just received an error while deploying latest iso of ciab on bare metal:
...
deploy | Add monitoring-plane label to all hosts in group monitoring ------------- 2.82s
deploy | Make kubeconfig available for use inside the manager service ------------ 2.76s
deploy | osism.commons.k9s : Include distribution specific install tasks --------- 2.74s
deploy | k3s_server : Copy vip manifest to first master -------------------------- 2.70s
deploy | ERROR! the playbook: playbook-kubernetes-dashboard.yml could not be found
deploy | ERROR: DEPLOY FAILED
...
