### ISSUE TITLE
Add play to verify NTP sync/drift on all nodes

### ISSUE THREAD

**Issue by berendt** [osism/issues#1090]

**Comment by janhorstmann** [comment]
This could also be done continuously by monitoring via the prometheus node-exporter. The [node-exporter mixin](https://github.com/prometheus/node_exporter/tree/master/docs/node-mixin) already has a check for [clock skew](https://github.com/prometheus/node_exporter/blob/master/docs/node-mixin/alerts/alerts.libsonnet#L214) and [unsynchronized clocks](https://github.com/prometheus/node_exporter/blob/master/docs/node-mixin/alerts/alerts.libsonnet#L238).

Maybe adding a play could be done additionally

**Comment by berendt** [comment]
We should do both.
