### ISSUE TITLE
[bug] Zombie processes after using osism console --type ansible <HOSTGROUP>

### ISSUE THREAD

**Issue by brueggemann** [osism/issues#1114]
### OSISM release version

7.0.5

### What's the problem?

A customer of ours has the problem, that every time after he uses `osism console --type ansible <HOSTGROUP>` zombie processes are remaining.

See this `ps axfu` snippet:
```
root      442891  0.0  0.0 1236216 13808 ?       Sl   Aug19   0:29
/usr/bin/containerd-shim-runc-v2 -namespace moby -id
7fec25657efc934c92d4ae2043d4361bd7696e380dc096d61f06dee80f668ad8 -address
/run/containerd
root      442917  0.0  0.0   2904   860 ?        Ss   Aug19   0:00  \_ sleep
infinity
root     2754007  0.0  0.0      0     0 ?        Zs   08:44   0:00      \_
[ssh] <defunct>
root     2754008  0.0  0.0      0     0 ?        Zs   08:44   0:00      \_
[ssh] <defunct>
root     2754010  0.0  0.0      0     0 ?        Zs   08:44   0:00      \_
[ssh] <defunct>
root     2754011  0.0  0.0      0     0 ?        Zs   08:44   0:00      \_
[ssh] <defunct>
root     2754013  0.0  0.0      0     0 ?        Zs   08:44   0:00      \_
[ssh] <defunct>
root     2754014  0.0  0.0      0     0 ?        Zs   08:44   0:00      \_
[ssh] <defunct>
```

### References to existing reports

References to existing bug reports, mailing lists, ...

### Severity

low

### Urgency

medium

**Comment by berendt** [comment]
Only ssh zombie processes?

**Comment by brueggemann** [comment]
yes, only ssh zombie processes were seen

**Comment by berendt** [comment]
That should be done with tini. The next OSISM 7 release will be on Thursday morning. The OSISM 8 release is planned for next week. It will be fixed there. Please open issue again otherwise.
