### ISSUE TITLE
[bug] ERROR! the playbook: playbook-kubernetes-dashboard.yml could not be found ERROR: DEPLOY FAILED [Baremetal]

### ISSUE THREAD

**Issue by kayamax** [osism/issues#1119]
### OSISM release version

latest

### What's the problem?

just received an error while deploying latest iso of ciab on bare metal:
...
deploy | Add monitoring-plane label to all hosts in group monitoring ------------- 2.82s
deploy | Make kubeconfig available for use inside the manager service ------------ 2.76s
deploy | osism.commons.k9s : Include distribution specific install tasks --------- 2.74s
deploy | k3s_server : Copy vip manifest to first master -------------------------- 2.70s
deploy | ERROR! the playbook: playbook-kubernetes-dashboard.yml could not be found
deploy | ERROR: DEPLOY FAILED
...

### References to existing reports

similar to issue #1083

### Severity

medium

### Urgency

medium

**Comment by berendt** [comment]
Sorry. I had added a k8s prefix to all the Kubernetes playbooks to avoid overlaps in the future. I had forgotten to change it in the Cloud in a Box repo.
