### ISSUE TITLE
[bug] manila policy file permission issue

### ISSUE THREAD

**Issue by TheProJeckt** [osism/issues#1121]
### OSISM release version

7.1.2

### What's the problem?

i've encounterd an issue while applying manila.
The bug is in https://github.com/openstack/kolla-ansible/blob/master/ansible/roles/manila/tasks/config.yml#L91 in the "Copying over existing policy file" Task.
There is a 'become: true' missing, resolting in a "fatal: [xyz]: FAILED! => msg: 'Failed to get information on remote file (/etc/kolla/manila-api/policy.yaml): Permission denied'".

### Severity

medium

### Urgency

medium

**Comment by berendt** [comment]
* https://review.opendev.org/c/openstack/kolla-ansible/+/928469
