### ISSUE TITLE
[bug] make sync does error out on sed

### ISSUE THREAD

**Issue by chrisschwa** [osism/issues#1128]
### OSISM release version

7.1.3

### What's the problem?

using `make sync` on a mac in the configuration repository erros with:

```
Using branch main
sed -i "~s,version: .*,version: main," gilt.yml
sed: 1: "gilt.yml": extra characters at the end of g command
make: *** [sync] Error 1
```

### References to existing reports

I think thats because of a GNU specific sed character `~`

### Severity

medium

### Urgency

low

**Comment by berendt** [comment]
What kind of sed are you using on what kind of operating system?

**Comment by chrisschwa** [comment]
I dont know if i understand you correctly, but as i wrote in the Issue  i was using the `make sync` command on a mac (OSX) in the configuration repository.

**Comment by berendt** [comment]
It works here on my Mac as expected. I think it got fixed by https://github.com/osism/cfg-generics/commit/2fb9627967ccc46e090297725bea1b402c1abd56.
