### ISSUE TITLE
[bug] Dependency problem for octavia-interface.service service

### ISSUE THREAD

**Issue by scoopex** [osism/issues#1140]
### OSISM release version

8.0.0

### What's the problem?

After performing a kernel upgrade i restarted 3 of my compute nodes which also host the "ovn-database" and the octavia instrastructure (see https://github.com/SovereignCloudStack/hardware-landscape/blob/main/inventory/99-overwrite). 
After reboot the octavia octavia-interface.service service is not started automatically on all 3 nodes.

Systemd status shows the following information:
```
root@st01-comp-r01-u09:/home/scoopex# systemctl status octavia-interface.service
× octavia-interface.service - Octavia Interface Creator
     Loaded: loaded (/etc/systemd/system/octavia-interface.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-09-19 12:21:54 UTC; 38min ago
    Process: 3569 ExecStartPre=/sbin/ip link set dev o-hm0 address fa:16:3e:5f:67:6f (code=exited, status=1/FAILURE)
        CPU: 3ms

Sep 19 12:21:54 st01-comp-r01-u09 systemd[1]: Starting Octavia Interface Creator...
Sep 19 12:21:54 st01-comp-r01-u09 ip[3569]: Cannot find device "o-hm0"
Sep 19 12:21:54 st01-comp-r01-u09 systemd[1]: octavia-interface.service: Control process exited, code=exited, status=1/FAILURE
Sep 19 12:21:54 st01-comp-r01-u09 systemd[1]: octavia-interface.service: Failed with result 'exit-code'.
Sep 19 12:21:54 st01-comp-r01-u09 systemd[1]: Failed to start Octavia Interface Creator.
```

Manually restarting the service fixed the problem.

This might be a upstream problem of kolla-ansible, but i think its a good idea to file it here.
(for a later reference in the kolla-ansible upstream issue)

### References to existing reports

n/a

### Severity

low

### Urgency

low

**Comment by artificial-intelligence** [comment]
this might be a related upstream fix: https://review.opendev.org/c/openstack/kolla-ansible/+/920377

**Comment by scoopex** [comment]
Yes, the "Restart=on-failure" directive might help.

**Comment by berendt** [comment]
All back ports are now approved. Will be fixed tomorrow on the rolling tags.
