### ISSUE TITLE
Generic [loadbalancer:children] control group is not ideal

### ISSUE THREAD

**Issue by fzakfeld** [osism/issues#1142]
Currently the cfg-generics have control as the default children for the loadbalancer group

It is however very common to have dedicated loadbalancer in any lager enviroment. For us, as we are using netbox, I'd like to simply add the group "loadbalancer" as a tag instead of writing an override for some explicit hosts which would then be defined in git instead of netbox.

This obviously is a breaking change and users would need to define the loadbalancers in config, like it is done with control, compute etc. But I think this would make sense.

Let me know what you think...

**Comment by berendt** [comment]
I had the same discussion today regarding OpenSearch & Prometheus. It probably makes sense to not have them on the control nodes by default because of the IOPS.

**Comment by berendt** [comment]
@fzakfeld It should now be possible to overwrite the loadbalancer group via a Netbox tag.
