### ISSUE TITLE
[bug] Unable to deploy CiaB

### ISSUE THREAD

**Issue by scoopex** [osism/issues#1144]
### OSISM release version

8.0.0

### What's the problem?

At 2024-09-24 (476589a7d46511789a39240840309ea431f4eaf0) i tried a CiaB installation using the state of the CIAB repos of that date.

It seems that something is wrong with Fluentd.

```
deploy | RUNNING HANDLER [common : Restart fluentd container] ***************************
deploy | Monday 23 September 2024  19:05:35 +0000 (0:00:00.570)       0:00:30.123 ****** 
deploy | fatal: [manager.systems.in-a-box.cloud]: FAILED! => {"Command": "dumb-init --single-child -- kolla_start", "Created": 1727118336, "HostConfig": {"NetworkMode": "host"}, "Id": "e1e81aaddab7caa2c98383fcc5ce6cb616d3ab5caba8eb5cc47c958584e95429", "Image": "quay.io/osism/fluentd:5.0.4.20240909", "ImageID": "sha256:9b13f0454707cc99d142c601e6f858e7a4a6008b3a1265d1a6f514bb9ce41538", "Labels": {"build-date": "20240909", "de.osism.commit.docker_images_kolla": "8f7737a", "de.osism.commit.kolla": "4df43abd7", "de.osism.commit.kolla_version": "18.1.1", "de.osism.commit.release": "621ee93", "de.osism.release.openstack": "2024.1", "de.osism.version": "8.0.0", "fluentd_binary": "fluentd", "fluentd_user": "fluentd", "kolla_version": "2024.1", "maintainer": "Kolla Project (https://launchpad.net/kolla)", "name": "fluentd", "org.opencontainers.image.created": "2024-09-09T14:24:17.584054+00:00", "org.opencontainers.image.documentation": "https://osism.tech/docs/", "org.opencontainers.image.licenses": "ASL 2.0", "org.opencontainers.image.ref.name": "ubuntu", "org.opencontainers.image.source": "https://github.com/osism/container-images-kolla", "org.opencontainers.image.title": "fluentd", "org.opencontainers.image.url": "https://quay.io/organization/osism", "org.opencontainers.image.vendor": "OSISM GmbH", "org.opencontainers.image.version": "5.0.4"}, "Mounts": [{"Destination": "/var/lib/fluentd/data", "Driver": "local", "Mode": "rw", "Name": "fluentd_data", "Propagation": "", "RW": true, "Source": "/var/lib/docker/volumes/fluentd_data/_data", "Type": "volume"}, {"Destination": "/var/lib/kolla/config_files", "Mode": "ro", "Propagation": "rprivate", "RW": false, "Source": "/etc/kolla/fluentd", "Type": "bind"}, {"Destination": "/var/log/journal", "Mode": "ro", "Propagation": "rprivate", "RW": false, "Source": "/var/log/journal", "Type": "bind"}, {"Destination": "/var/log/kolla", "Driver": "local", "Mode": "rw", "Name": "kolla_logs", "Propagation": "", "RW": true, "Source": "/var/lib/docker/volumes/kolla_logs/_data", "Type": "volume"}, {"Destination": "/etc/localtime", "Mode": "ro", "Propagation": "rprivate", "RW": false, "Source": "/etc/localtime", "Type": "bind"}, {"Destination": "/etc/timezone", "Mode": "ro", "Propagation": "rprivate", "RW": false, "Source": "/etc/timezone", "Type": "bind"}], "Names": ["/fluentd"], "NetworkSettings": {"Networks": {"host": {"Aliases": null, "DNSNames": null, "DriverOpts": null, "EndpointID": "", "Gateway": "", "GlobalIPv6Address": "", "GlobalIPv6PrefixLen": 0, "IPAMConfig": null, "IPAddress": "", "IPPrefixLen": 0, "IPv6Gateway": "", "Links": null, "MacAddress": "", "NetworkID": ""}}}, "Ports": [], "State": "created", "Status": "Created", "changed": true, "msg": "Container timed out"}
deploy | 
```

See attached installation logfile
[install-cloud-in-a-box.log](https://github.com/user-attachments/files/17112795/install-cloud-in-a-box.log)

### References to existing reports

References to existing bug reports, mailing lists, ...

### Severity

low

### Urgency

low

**Comment by berendt** [comment]
Cannot be reproduced on local test system.

**Comment by scoopex** [comment]
That's strange, I will  test it again and then let you know the result

**Comment by scoopex** [comment]
Now it fails in the bootstrap phase (see screenshot)
![2024-09-30_14-07](https://github.com/user-attachments/assets/955ca139-9727-4553-8e61-d70d8f3dc192).

When i login to the system and inspect the logfiles, the error is not logged:
```
root@manager:/var/log# tail -15 /var/log/install-cloud-in-a-box.log 
bootstrap | included: /usr/share/ansible/collections/ansible_collections/osism/commons/roles/cleanup/tasks/timers-Debian-family.yml for manager.systems.in-a-box.cloud
bootstrap | 
bootstrap | TASK [osism.commons.cleanup : Disable apt-daily timers] ************************
bootstrap | Monday 30 September 2024  11:34:59 +0000 (0:00:00.847)       0:01:48.294 ****** 
bootstrap | skipping: [manager.systems.in-a-box.cloud] => (item=apt-daily-upgrade) 
bootstrap | skipping: [manager.systems.in-a-box.cloud] => (item=apt-daily) 
bootstrap | skipping: [manager.systems.in-a-box.cloud]
bootstrap | 
bootstrap | TASK [osism.commons.cleanup : Include service tasks] ***************************
bootstrap | Monday 30 September 2024  11:35:00 +0000 (0:00:00.675)       0:01:48.969 ****** 
bootstrap | included: /usr/share/ansible/collections/ansible_collections/osism/commons/roles/cleanup/tasks/services-Debian-family.yml for manager.systems.in-a-box.cloud
bootstrap | 
bootstrap | TASK [osism.commons.cleanup : Cleanup services] ********************************
bootstrap | Monday 30 September 2024  11:35:01 +0000 (0:00:00.841)       0:01:49.811 ****** 
bootstrap | ok: root@manager:/var/log#
``

**Comment by berendt** [comment]
> Reference in new issue



> Now it fails in the bootstrap phase (see screenshot) ![2024-09-30_14-07](https://private-user-images.githubusercontent.com/288876/372077932-955ca139-9727-4553-8e61-d70d8f3dc192.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MTkyMjIsIm5iZiI6MTcyNzcxODkyMiwicGF0aCI6Ii8yODg4NzYvMzcyMDc3OTMyLTk1NWNhMTM5LTk3MjctNDU1My04ZTYxLWQ3MGQ4ZjNkYzE5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQxNzU1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjNlYWY5OTczZjQyMzU2ZDFiOWFlMjAxNDBhOTY3Y2VhZmQ1ZTI4MTc5YjU0YjQyYjIzZDcwNDZhOGMyOTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UnVLBjPNyxBGHDlVqIWjZgN_HQIodJdFWx7EKAL4osQ).
> 
> When i login to the system and inspect the logfiles, the error is not logged:
> 
> ```
> root@manager:/var/log# tail -15 /var/log/install-cloud-in-a-box.log 
> bootstrap | included: /usr/share/ansible/collections/ansible_collections/osism/commons/roles/cleanup/tasks/timers-Debian-family.yml for manager.systems.in-a-box.cloud
> bootstrap | 
> bootstrap | TASK [osism.commons.cleanup : Disable apt-daily timers] ************************
> bootstrap | Monday 30 September 2024  11:34:59 +0000 (0:00:00.847)       0:01:48.294 ****** 
> bootstrap | skipping: [manager.systems.in-a-box.cloud] => (item=apt-daily-upgrade) 
> bootstrap | skipping: [manager.systems.in-a-box.cloud] => (item=apt-daily) 
> bootstrap | skipping: [manager.systems.in-a-box.cloud]
> bootstrap | 
> bootstrap | TASK [osism.commons.cleanup : Include service tasks] ***************************
> bootstrap | Monday 30 September 2024  11:35:00 +0000 (0:00:00.675)       0:01:48.969 ****** 
> bootstrap | included: /usr/share/ansible/collections/ansible_collections/osism/commons/roles/cleanup/tasks/services-Debian-family.yml for manager.systems.in-a-box.cloud
> bootstrap | 
> bootstrap | TASK [osism.commons.cleanup : Cleanup services] ********************************
> bootstrap | Monday 30 September 2024  11:35:01 +0000 (0:00:00.841)       0:01:49.811 ****** 
> bootstrap | ok: root@manager:/var/log#
> ``
> ```

Introduced by https://github.com/osism/cloud-in-a-box/commit/07e6727a34fb1f188a5fc803de784a1bf518661d.

Fixed by https://github.com/osism/cloud-in-a-box/commit/8ea14c40f0020d381a0be2aa1e2504213bf0c6af.

**Comment by scoopex** [comment]
Retried with the latest state. Successfully!
