### ISSUE TITLE
[bug] Horizon calls insufficient Permissions when creating LB

### ISSUE THREAD

**Issue by chrisschwa** [osism/issues#1146]
### OSISM release version

7.1.3

### What's the problem?

You can still create/delete Loadbalancers but Horzion tells you that its forbidden because of insufficient permissions.
In the Console of the Browser you can see that there is a 403 on 

```
Failed to load resource: the server responded with a status of 403 (Forbidden). /api/octavia-barbican/secrets/:1
Failed to load resource: the server responded with a status of 403 (Forbidden).  /api/octavia-barbican/certificates/:1
```

Further investigation showed that its an known bug and you have to give the Users a specific role. (`creator`)

### References to existing reports

[References to existing bug reports, mailing lists, ...](https://bugs.launchpad.net/octavia/+bug/2049541)

### Severity

low

### Urgency

low

**Comment by berendt** [comment]
It's not really a bug. You have to care about the assigned roles of the users you have on your cluster.

**Comment by flyersa** [comment]
you need the creator role for barbican access on your user

**Comment by chrisschwa** [comment]
Yeah i did that already and it worked flawless.

But i opened the issue because there is a corresponding one on launchpad and i couldnt see any mention about the need for that change on upgrade.

if that is known and ok for everyone we can just close the issue.

**Comment by flyersa** [comment]
had the same confusion lately. best you just close it ;)
