### ISSUE TITLE
Multiple Cluster Support for cephadm

### ISSUE THREAD

**Issue by linwalth** [osism/issues#116]
As the integration of Ceph into OSISM goes on i find it important to note that there should be a possibility to deploy and integrate multiple Ceph clusters, not just one as it is now, as there are architectural cases that would benefit from such an integration.

**Comment by berendt** [comment]
Good point. Let's include in the roadmap for cephadm.

**Comment by berendt** [comment]
Should be discussed with SCS Team 1.

**Comment by berendt** [comment]
Conversion to cephadm is not currently on the roadmap. Therefore, close this.
