### ISSUE TITLE
kolla: no logrotate config for redis available

### ISSUE THREAD

**Issue by maliblatt** [osism/issues#1166]
### OSISM release version

8.0.0

### What's the problem?

For the redis service there seems no existing logrotate config template being available. So the redis logs gets never rotated and is only growing. I found some redis logs with loglines from early 2023.
Can a 'cron-logrotate-redis.conf.j2' template being included for this service in https://github.com/openstack/kolla-ansible/tree/master/ansible/roles/common/templates?

### References to existing reports

nothing found

### Severity

low

### Urgency

low

**Comment by janhorstmann** [comment]
Fix for upstream: https://review.opendev.org/c/openstack/kolla-ansible/+/932392

**Comment by janhorstmann** [comment]
[Upstream backport to 2024.1](https://review.opendev.org/c/openstack/kolla-ansible/+/934345)
