### ISSUE TITLE
Cinder upgrade not working from 7.1.3 to 8.0.2

### ISSUE THREAD

**Issue by flyersa** [osism/issues#1182]
Hi,

running into a problem upgrading cinder from 7.1.x to 8.0.2 on the bootstrap container part. cinder manage db sync is returning 1 but no output and also --debug doesnt give anything.  Anyone an idea what this is and how to fix?

`{
    "changed": true,
    "msg": "Container exited with non-zero return code 1",
    "rc": 1,
    "stderr": "+ sudo -E kolla_set_configs\nINFO:__main__:Loading config file at /var/lib/kolla/config_files/config.json\nINFO:__main__:Validating config file\nINFO:__main__:Kolla config strategy set to: COPY_ALWAYS\nINFO:__main__:Copying service configuration files\nINFO:__main__:Copying /var/lib/kolla/config_files/cinder.conf to /etc/cinder/cinder.conf\nINFO:__main__:Setting permission for /etc/cinder/cinder.conf\nINFO:__main__:Copying /var/lib/kolla/config_files/cinder-wsgi.conf to /etc/apache2/conf-enabled/cinder-wsgi.conf\nINFO:__main__:Setting permission for /etc/apache2/conf-enabled/cinder-wsgi.conf\nINFO:__main__:Writing out command to execute\nINFO:__main__:Setting permission for /var/lib/cinder\nINFO:__main__:Setting permission for /var/log/kolla/cinder\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.3.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.1\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-backup.log.2.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-scheduler.log.4.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.3.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.4.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.4.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.5.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.1\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.3.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/privsep-helper.log\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-scheduler.log.1\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.1\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-scheduler.log\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-volume.log\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-backup.log.1\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.2.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.5.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.2.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.2.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.5.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.6.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-volume.log.1\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-backup.log.3.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-scheduler.log.3.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-backup.log\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.6.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-scheduler.log.2.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.6.gz\nINFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.4.gz\n++ cat /run_command\n+ CMD='/usr/sbin/apache2 -DFOREGROUND'\n+ ARGS=\n+ sudo kolla_copy_cacerts\n+ [[ ! -n '' ]]\n+ . kolla_extend_start\n++ [[ ! -d /var/log/kolla/cinder ]]\n+++ stat -c %a /var/log/kolla/cinder\n++ [[ 2755 != \\7\\5\\5 ]]\n++ chmod 755 /var/log/kolla/cinder\n++ . /usr/local/bin/kolla_cinder_extend_start\n+++ set -o errexit\n+++ [[ -n 0 ]]\n+++ cinder-manage db sync\n",
    "stderr_lines": [
        "+ sudo -E kolla_set_configs",
        "INFO:__main__:Loading config file at /var/lib/kolla/config_files/config.json",
        "INFO:__main__:Validating config file",
        "INFO:__main__:Kolla config strategy set to: COPY_ALWAYS",
        "INFO:__main__:Copying service configuration files",
        "INFO:__main__:Copying /var/lib/kolla/config_files/cinder.conf to /etc/cinder/cinder.conf",
        "INFO:__main__:Setting permission for /etc/cinder/cinder.conf",
        "INFO:__main__:Copying /var/lib/kolla/config_files/cinder-wsgi.conf to /etc/apache2/conf-enabled/cinder-wsgi.conf",
        "INFO:__main__:Setting permission for /etc/apache2/conf-enabled/cinder-wsgi.conf",
        "INFO:__main__:Writing out command to execute",
        "INFO:__main__:Setting permission for /var/lib/cinder",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.3.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.1",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-backup.log.2.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-scheduler.log.4.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.3.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.4.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.4.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.5.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.1",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.3.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/privsep-helper.log",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-scheduler.log.1",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.1",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-scheduler.log",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-volume.log",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-backup.log.1",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.2.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.5.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.2.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.2.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.5.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.6.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-volume.log.1",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-backup.log.3.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-scheduler.log.3.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-backup.log",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.6.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-scheduler.log.2.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.6.gz",
        "INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.4.gz",
        "++ cat /run_command",
        "+ CMD='/usr/sbin/apache2 -DFOREGROUND'",
        "+ ARGS=",
        "+ sudo kolla_copy_cacerts",
        "+ [[ ! -n '' ]]",
        "+ . kolla_extend_start",
        "++ [[ ! -d /var/log/kolla/cinder ]]",
        "+++ stat -c %a /var/log/kolla/cinder",
        "++ [[ 2755 != \\7\\5\\5 ]]",
        "++ chmod 755 /var/log/kolla/cinder",
        "++ . /usr/local/bin/kolla_cinder_extend_start",
        "+++ set -o errexit",
        "+++ [[ -n 0 ]]",
        "+++ cinder-manage db sync"
    ],
    "stdout": "",
    "stdout_lines": []
}`

there are also no migrations pending or anything:

`root@ctrl01:/home/dragon# docker exec cinder_api cinder-manage db online_data_migrations
Running batches of 50 until complete.
+------------------------------------------+----------------+-------------+
| Migration                                |   Total Needed |   Completed |
|------------------------------------------+----------------+-------------|
| snapshot_use_quota_online_data_migration |              0 |           0 |
| volume_use_quota_online_data_migration   |              0 |           0 |
+------------------------------------------+----------------+-------------+
`

**Comment by flyersa** [comment]
hmm this might be related coming from mariadb at this time when the command is run:

`2024-11-18 23:19:39 9 [ERROR] Slave SQL: Error 'Data truncated for column 'use_quota' at row 4' on query. Default database: 'cinder'. Query: 'ALTER TABLE volumes MODIFY use_quota BOOL NOT NULL DEFAULT true', Internal MariaDB error code: 1265
2024-11-18 23:19:39 9 [Warning] WSREP: Ignoring error 'Data truncated for column 'use_quota' at row 4' on query. Default database: 'cinder'. Query: 'ALTER TABLE volumes MODIFY use_quota BOOL NOT NULL DEFAULT true', Error_code: 1265
2024-11-18 23:21:23 2 [ERROR] Slave SQL: Error 'Data truncated for column 'use_quota' at row 4' on query. Default database: 'cinder'. Query: 'ALTER TABLE volumes MODIFY use_quota BOOL NOT NULL DEFAULT true', Internal MariaDB error code: 1265
2024-11-18 23:21:23 2 [Warning] WSREP: Ignoring error 'Data truncated for column 'use_quota' at row 4' on query. Default database: 'cinder'. Query: 'ALTER TABLE volumes MODIFY use_quota BOOL NOT NULL DEFAULT true', Error_code: 1265
2024-11-18 23:23:47 9 [ERROR] Slave SQL: Error 'Data truncated for column 'use_quota' at row 4' on query. Default database: 'cinder'. Query: 'ALTER TABLE volumes MODIFY use_quota BOOL NOT NULL DEFAULT true', Internal MariaDB error code: 1265
2024-11-18 23:23:47 9 [Warning] WSREP: Ignoring error 'Data truncated for column 'use_quota' at row 4' on query. Default database: 'cinder'. Query: 'ALTER TABLE volumes MODIFY use_quota BOOL NOT NULL DEFAULT true', Error_code: 1265
2024-11-18 23:27:25 6 [ERROR] Slave SQL: Error 'Data truncated for column 'use_quota' at row 4' on query. Default database: 'cinder'. Query: 'ALTER TABLE volumes MODIFY use_quota BOOL NOT NULL DEFAULT true', Internal MariaDB error code: 1265
2024-11-18 23:27:25 6 [Warning] WSREP: Ignoring error 'Data truncated for column 'use_quota' at row 4' on query. Default database: 'cinder'. Query: 'ALTER TABLE volumes MODIFY use_quota BOOL NOT NULL DEFAULT true', Error_code: 1265
`

**Comment by flyersa** [comment]
yeah... running those querys with strict mode disabled in a session before in mysql fixes this issue. was there some change in mysql lately?

**Comment by artificial-intelligence** [comment]
fwiw this seems to be still unfixed upstream, but a fix is in development:
https://bugs.launchpad.net/cinder/+bug/2070475
