### ISSUE TITLE
Update ansible-core version in manager-kolla image

### ISSUE THREAD

**Issue by muellerbe** [osism/issues#123]
issue
cannot use node_id in ansible_host for the nova-cell role via delegate_to
https://opendev.org/openstack/kolla-ansible/src/branch/master/ansible/roles/nova-cell/tasks/discover_computes.yml#L61

possible solution
use ansible-core>=2.11.9
https://github.com/ansible/ansible/commit/5c2251504c7f985fa586c658247f2973950ed732

actual ansible-core version in manager-kolla image
$ docker exec -it manager_kolla-ansible_1 bash
Ansible version: 2.10.17
Container version: latest

**Comment by berendt** [comment]
We use the Ansible versions supported by the upstream.

stable/wallaby:

```
ansible_version_min: '2.9'
ansible_version_max: '2.10'
```

stable/xena:

```
ansible_version_min: '2.10'
ansible_version_max: '2.11'
```

master:

```
ansible_version_min: '2.11'
ansible_version_max: '2.12'
```
