### ISSUE TITLE
Zuul CI: discuss use of volumes and network resources in nodepool

### ISSUE THREAD

**Issue by berendt** [osism/issues#124]
We want to be able to create a testbed environment via nodepool. Currently there are two features that are missing from nodepool that are needed in order to replicate the current setup as deployed by terraform:

- Create volumes and attach them to nodes
- Create network resources and use them to build a specific nodeset
  - router
  - network
  - subnet
  - port (with static IP)

**Comment by osfrickler** [comment]
Initial feedback from the zuul community: Should be feasible, but will require a lot of work. Will need to refine into more manageable steps.

**Comment by berendt** [comment]
By using Ephmeral storage, this is no longer necessary.
