### ISSUE TITLE
Discuss role for updating NIC firmware

### ISSUE THREAD

**Issue by muellerbe** [osism/issues#125]
discuss a role for updating NIC firmware for SCS project.

roles/nic-firmware-update/tasks/main.yml
include_tasks mellanox when mellanox_fw_update
include_tasks <anotherNICmanufacturer> when <anotherNICmanufacturer>_fw_update
...

**Comment by berendt** [comment]
Not in the scope of the project for now. However, we are preparing an exemplary playbook for the use of LVFS in #140.
