### ISSUE TITLE
ConntrackLimit nearly reached

### ISSUE THREAD

**Issue by maliblatt** [osism/issues#134]
Since there are more users and more traffic on our platform we sometimes get a HostConntrackLimit Warning via prometheus. It seems the standard value of 262144 for /proc/sys/net/netfilter/nf_conntrack_max / /proc/sys/net/nf_conntrack_max is not enough in a (our?) cloud.
Is anybody else facing that issue? Would it make sense to rise the limit by default when installing a cloud with osism?
What is the correct way to modify this limit in osism context?

thanks and regards
Markus

**Comment by frosty-geek** [comment]
Maybe @JohnGarbutt or @cityofships have some suggestions on some working best practices

**Comment by berendt** [comment]
Feel free to increase the default value via the sysctl role: https://github.com/osism/ansible-collection-commons/blob/main/roles/sysctl/defaults/main.yml

You can also use `sysctl_extra` to define custom values.

**Comment by maliblatt** [comment]
Thanks, I will use sysctl_extra that works perfect for us after upgrading the collection :-)
