### ISSUE TITLE
Prepare a custom playbook to update a firmeware via LFVS

### ISSUE THREAD

**Issue by berendt** [osism/issues#140]
https://fwupd.org

**Comment by matfechner** [comment]
after i've take a little bit time to investigate about the contributing companies it gives an impression that consumer and desktop environments support is very well ! But for systems like server or network equipment, their is less  support.

**Comment by berendt** [comment]
Next Wednesday in the SCS Team 1 then to consult again.

**Comment by berendt** [comment]
Overtaken by #245
