### ISSUE TITLE
.vault_pass script does not work

### ISSUE THREAD

**Issue by linwalth** [osism/issues#145]
https://docs.osism.tech/overview/secrets.html?#search-secret-files-for-password

this links to https://github.com/osism/cfg-cookiecutter/blob/main/cfg-%7B%7Bcookiecutter.project_name%7D%7D/environments/.vault_pass which is the script which gets deployed via cookiecutter.

It does not work, though - I suspect it is a WIP still

**Comment by berendt** [comment]
The mentioned script is probably not yet in the Cookiecutter repository.

**Comment by tibeer** [comment]
@linwalth thanks for pointing that out. Indeed there was a pull request which implemented this functionality, but it was never merged: https://github.com/osism/cfg-cookiecutter/pull/189 In favor of the upcoming hashicorp vault integration it was abandoned. I'll fix the documentation :)
