### ISSUE TITLE
docker version in defaults is lagging behind release

### ISSUE THREAD

**Issue by linwalth** [osism/issues#147]
The docker version in the collection defaults is older than the one in release, e.g.:

https://github.com/osism/ansible-collection-services/blob/0b42fc48c66e1a790a881c55ad48125fc2941076/roles/docker/defaults/main.yml#L86

https://github.com/osism/release/blob/main/3.0.0/base.yml#L12

**Comment by berendt** [comment]
Renovate configuration already added. But broken at the moment: https://github.com/osism/release/issues/352
