### ISSUE TITLE
manager redis, mariadb not accessible on quay.io

### ISSUE THREAD

**Issue by linwalth** [osism/issues#154]
when i set the docker_registry parameter from index.docker.io to quay.io i get the following errors when running osism-update-manager:
```
ERROR: for mariadb  unauthorized: access to the requested resource is not authorized
ERROR: for redis  unauthorized: access to the requested resource is not authorized
```
docker_registry: index.docker.io works fine, however.

**Comment by berendt** [comment]
That doesn't make sense either. The ``docker_registry`` is ``index.docker.io`` by default.

I don't know if MariaDB and Redis also publish their images on Quay.io.

However, you can explicitly adjust the registry for individual services.

https://github.com/osism/ansible-defaults/blob/main/all/000-registries.yml

**Comment by linwalth** [comment]
Thank you for the information + quick response!
