### ISSUE TITLE
fix sphinx rst pipelines

### ISSUE THREAD

**Issue by tibeer** [osism/issues#155]
Since the last update of jinja2 there is an issue when building rst Sphinx documentation. At least, when Sphinx is pinned to an old version. We should remove the version pinning in the `requirements.txt` file to assure building again.

**Comment by berendt** [comment]
Do not remove the version pinning. Instead enable renovate in all affected repositories and add the renovate configuration to ensure that the used Sphinx version is up-to-date.

**Comment by berendt** [comment]
Sample configuration: https://github.com/osism/container-image-osism-ansible/blob/main/.github/renovate.json

Generic configuration: https://github.com/osism/renovate-config

Ping Jens or Christian for the Repository access in the Github Renovate Bot App
