### ISSUE TITLE
Xena libvirt SASL breaks nova deployment

### ISSUE THREAD

**Issue by flyersa** [osism/issues#157]
With xena now libvirt_enable_sasl is by default true which was false before in wallaby. On new xena osism deployments this breaks nove-compute deployments as nova-compute gets authentication errors on the libvirt process.

So something is missing here, setting libvirt_enable_sasl to false solves the problem.

**Comment by berendt** [comment]
@osfrickler Can you please document the missing parameters and requirements here? We should then note them in the 3.0.0/Xena release notes as well.

**Comment by berendt** [comment]
I have added a note in the release notes.

**Comment by osfrickler** [comment]
The only issue I am aware of is happening when there is a mismatch between the configured hostname and the one in DNS or /etc/hosts. If you still see this issue please reopen and we can collect some more detailed debugging information.
