### ISSUE TITLE
Transfer release images from Quay.io to the internal Harbor service

### ISSUE THREAD

**Issue by berendt** [osism/issues#158]
We are currently publishing release images to our internal registry as well as to Quay.io.

In the event of a total failure or loss of our internal registry, all objects on the internal registry can be automatically refilled by the CI.

With the exception of the release images since these cannot be rebuilt.

Therefore we need a script that identifies all release images on Quay.io from the osism namespace and restores them to the internal registry.

```
quay.io/osism/*/*.YYYYMMDD -> harbor.service.osism.tech/osism/release/*.YYYYMMDD
```

Use sinker (https://github.com/plexsystems/sinker) for this.

```
sinker syncs container images from one registry to another. This is useful in cases when you rely on images that exist in a public container registry, but need to pull from a private registry.
```

**Comment by tibeer** [comment]
On hold - Harbor is maybe not the solution that fits our needs...

**Comment by tibeer** [comment]
Stale.
