### ISSUE TITLE
Check if there is a tool to check Ansible tasks for malicious actions

### ISSUE THREAD

**Issue by berendt** [osism/issues#161]
In a conversation with a customer, one of the topics was the use of Ansible Collection from third-party sources and how to ensure that no malicious actions can be executed.

We should discuss how we generally handle roles from third party sources and how we label them.

Furthermore, we should check if there are any tools to check roles or prevent the execution of certain tasks.

**Comment by tibeer** [comment]
https://www.jeffgeerling.com/blog/2019/how-evaluate-community-ansible-roles-your-playbooks

**Comment by tibeer** [comment]
I've tried to find some sort of tool that can provide such functionality but ultimately failed.
But tracking third party sources and labeling them is a good idea.
Maybe as an extension for SBOMs?

**Comment by berendt** [comment]
Yes the internally used Ansible Collections we should list with in the SBOM repository then. Then at least it is clear for everyone what we use. A complete review of all Ansible Collections we use is not possible at the moment.
