### ISSUE TITLE
Evaluate moving all Ansible code to FQCN's

### ISSUE THREAD

**Issue by tibeer** [osism/issues#165]
Ansible added the functionality specify roles in an FQCN schema.
Instead of "shell" you may now use "ansible.builtin.shell".
We should update all of our ansible code to use the FQCN schema.
@berendt please comment on this.

**Comment by berendt** [comment]
Yes. Please implement everywhere where not yet made. Is also the prerequisite for Ansible Lint 6.x

**Comment by ra-rau** [comment]
@berendt: This is done
