### ISSUE TITLE
Help the Large Scale SIG with the "The Scaling Journey"

### ISSUE THREAD

**Issue by berendt** [osism/issues#175]
* https://wiki.openstack.org/wiki/Large_Scale_SIG
* https://wiki.openstack.org/wiki/Large_Scale_SIG/Configure
* https://wiki.openstack.org/wiki/Large_Scale_SIG/Monitor
* https://wiki.openstack.org/wiki/Large_Scale_SIG/ScaleUp
* https://wiki.openstack.org/wiki/Large_Scale_SIG/ScaleOut
* https://wiki.openstack.org/wiki/Large_Scale_SIG/UpgradeAndMaintain

**Comment by osfrickler** [comment]
This has been done, mostly by @ra-beer, and the content is now available at https://docs.openstack.org/large-scale/.
