### ISSUE TITLE
Test the Kolla-Ansible quickstart guide

### ISSUE THREAD

**Issue by berendt** [osism/issues#177]
https://docs.openstack.org/kolla-ansible/latest/user/quickstart.html

Test step by step on a virtual system (Ubuntu 20.04).

**Comment by ra-rau** [comment]
I can evaluate that the quickstart guide for kolla ansible is working with some little changes and some diffrent setup. But i think it will need some rework for better understanding. It would be better to make diffrent pathes for diffrent installations and not only one for all.

Here are some of the things what i have found:
- My opinion: Python venv could be a bit better explained.
- Ansible installation does not fit. If you install it only with pip you wouldn’t get an ansible.cfg file.
- First you have to choose and configure a backend for cinder. NFS or LVM or something else.
- Rework the setup requirements: 1. For the multinode-installation. 2. For using Cinder.
- One note would be nice: If you are working on openstack, be sure that all ip-adresses what you will use, are visibel and available in your openstack-installation.
- It would be nice to get a little bit more information for the changes what someone will do in the global.yml.
- Something what is missing in the documentation is the thing about cinder. That you have to configure a lvm or nfs and that you have to enable the cinder_backand_port in the global.yml.

**Comment by osfrickler** [comment]
Sounds reasonable, please submit these changes as a patch to the upstream document.

**Comment by berendt** [comment]
That's done.
