### ISSUE TITLE
add ovs-dpdkctl.sh script to kolla container

### ISSUE THREAD

**Issue by muellerbe** [osism/issues#182]
https://opendev.org/openstack/kolla-ansible/src/branch/master/ansible/roles/ovs-dpdk/tasks/config.yml#L27

there is a script needed with name ovs-dpdkctl.sh whis is here

https://opendev.org/openstack/kolla-ansible/src/commit/668fecf397c3106d6c7d4957054c26a00e27ffdb/tools/ovs-dpdkctl.sh

at the point /ansible/roles/ovs-dpdk/tools/ovs-dpdkctl.sh I think (src: ../tools/ovs-dpdkctl.sh)

**Comment by berendt** [comment]
The proposed solution does not solve the real problem.

In the upstream, the move of the script to the role was prepared:

https://review.opendev.org/c/openstack/kolla-ansible/+/837703

**Comment by berendt** [comment]
https://review.opendev.org/c/openstack/kolla-ansible/+/837703 has been merged.


Backports opened:

* https://review.opendev.org/c/openstack/kolla-ansible/+/837798 (Xena)
* https://review.opendev.org/c/openstack/kolla-ansible/+/837799 (Yoga)

**Comment by berendt** [comment]
Backport in the upstream probably does not take place.

The problem that was solved with the review does not affect kolla-ansible if you use kolla-ansible with the tools directory. This only affects us with our container images.

Will therefore prepare a backport for it for stable/xena.
