### ISSUE TITLE
Collect ovn/ovs logs with Fluentd

### ISSUE THREAD

**Issue by amachowiak** [osism/issues#184]
Moin :)

Currently Fluentd does not collect log files from /var/log/kolla/openvswitch/*log. I'd be happy to have them in ElasticSearch as well.

I investigated some time and found out that:

1) It seems there needs to be a config file in https://github.com/openstack/kolla-ansible/tree/master/ansible/roles/common/templates/conf/input

Suggestion:
```
<source>
  @type tail
  path /var/log/kolla/openvswitch/*.log
  pos_file /var/run/td-agent/openvswitch.pos
  format /^(?<Timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}\S+)\|\d+\|(?<subroutine>\S+)\|(?<log_level>\S+)\|(?<Payload>.*)?$/
  time_key Timestamp
  tag kolla.*
  time_format %FT%T.%L%Z
  # see https://docs.fluentd.org/input/tail
  enable_stat_watcher false
</source>
```

2) Additionally, ovn/ovs logs are created with restrictive permissions that are not readable by Fluentd:

```
root@control01-dev:~# ll /var/log/kolla/openvswitch/
total 114132
drwxr-sr-x  2 root  root       4096 Jul 12 14:05 ./
drwxrwsr-x 30 42447 42400      4096 Dec  9 12:06 ../
-rw-r-----  1 root  root     324875 Dec 14 17:35 ovn-controller.log
-rw-r-----  1 root  root      14247 Nov 29 14:45 ovn-nb-db.log
-rw-r-----  1 root  root  116224955 Dec 15 13:47 ovn-northd.log
-rw-r-----  1 root  root      25039 Nov 29 15:26 ovn-sb-db.log
-rw-r-----  1 root  root       2239 Oct 27 19:03 ovsdb-server.log
-rw-r-----  1 root  root     240543 Dec 14 23:28 ovs-vswitchd.log
```

Probably there need to be set a umask or permission stuff around here:
https://github.com/openstack/kolla-ansible/tree/master/ansible/roles/ovn/templates

Not sure whether it is better to create an issue here or upstream. I would need this solution in victoria and wallaby. 

Kind regards,
André.

**Comment by berendt** [comment]
@matfechner Have you already verified this? If not, please do it this week.

**Comment by matfechner** [comment]
@berendt:  verified ! the configuration is now present in xena and it is working
