### ISSUE TITLE
Add documentation to all Ansible roles in all Ansible collections

### ISSUE THREAD

**Issue by berendt** [osism/issues#185]
Sample document: https://raw.githubusercontent.com/osism/ansible-collection-commons/main/roles/motd/README.rst

**Comment by berendt** [comment]
It is not possible to use the zuul-sphinx extension as planned because it is too customized for Zuul.

For example, a zuul configuration is read and there are many elements defined that we do not need in the context of Ansible.

Therefore, before creating and integrating the documentation, it is necessary to create our own ansible-sphinx extension based on the idea of the zuul-sphinx extension.

Repository for the extension is already created. The implementation of the extension itself could not yet take place due to time constraints.

**Comment by berendt** [comment]
Ansible-Sphinx implementation: https://github.com/osism/issues/issues/198

**Comment by ra-rau** [comment]
@berendt: Can we close this?
