### ISSUE TITLE
Create S3 account and bucket for publishing zuul artifacts

### ISSUE THREAD

**Issue by osfrickler** [osism/issues#190]
We want to be able to publish build artifacts from our zuul instance like images or tarballs.

**Comment by berendt** [comment]
Does it make sense to push the logs to the S3 as well?

**Comment by osfrickler** [comment]
The bucket is working fine, but zuul currently does not allow to publish artifacts to S3, we will have to develop a role for that.

Putting logs into S3 currently does not seem to be useful, we may reconsider that later.
