### ISSUE TITLE
Implement ansible-sphinx extension

### ISSUE THREAD

**Issue by berendt** [osism/issues#198]
Example input: https://opendev.org/zuul/zuul-jobs/raw/branch/master/roles/add-authorized-keys/README.rst

Example output: https://zuul-ci.org/docs/zuul-jobs/general-roles.html?highlight=add%20authorized%20keys#role-add-authorized-keys

Zuul Sphinx Extension: https://opendev.org/zuul/zuul-sphinx

**Comment by berendt** [comment]
Discuss with Tim if he can take over.

**Comment by fkr** [comment]
@berendt needs to clean away the attempt at a fork.
