### ISSUE TITLE
/usr/local/lib/python3.10/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated   "class": algorithms.Blowfish,

### ISSUE THREAD

**Issue by berendt** [osism/issues#199]
After the last update of cryptography, a deprecation warning occurs. Should be found out where this comes from and resolved.

**Comment by osfrickler** [comment]
Should be fixed by paramiko 2.11.0, see https://github.com/paramiko/paramiko/issues/2038
