### ISSUE TITLE
Prepare use of Ubuntu 22.04 

### ISSUE THREAD

**Issue by berendt** [osism/issues#200]
We want to support Ubuntu 22.04 LTS (Jammy Jellyfish) as base OS both for our containers and the host systems.

**Comment by osfrickler** [comment]
First steps: Upstream testing
https://review.opendev.org/c/zuul/nodepool/+/836263
https://review.opendev.org/c/zuul/nodepool/+/838909
https://review.opendev.org/c/opendev/system-config/+/838923
https://review.opendev.org/c/openstack/project-config/+/839057
https://review.opendev.org/c/openstack/diskimage-builder/+/836228
https://review.opendev.org/c/openstack/project-config/+/839366
https://review.opendev.org/c/openstack/devstack/+/839359
https://review.opendev.org/c/openstack/diskimage-builder/+/838981
https://review.opendev.org/c/openstack/kolla/+/839585

**Comment by berendt** [comment]
That has been done in the meantime. Ubuntu 22.04 is in and on everything.
