### ISSUE TITLE
bootstrap gather facts should be speeded up

### ISSUE THREAD

**Issue by grawert** [osism/issues#202]
The bootstrap playbook is gathering facts from every host for all other hosts. Meaning with n hosts there is n*n facts gathering. It would be nice to change the facts gathering so that the facts are fetched once.

**Comment by berendt** [comment]
Moved to osism/issues for better visibility

**Comment by grawert** [comment]
The n*n facts gathering seems to appear when hosts are limited. This should not be done anyway. So the case is obsolete.

Facts gathering on hosts with many VMs takes long because all virtual interfaces are included. Ansible supports filters. But unfortunately the filters are applied only after the facts have been gathered. No speed gain possible through filters.
