### ISSUE TITLE
Docs: Configure Fluentd communication with user authentication to elasticsearch 

### ISSUE THREAD

**Issue by matfechner** [osism/issues#207]
We should add in the documentation appendix section 
how an operator is able to activate fluentd with user context authentication to elasticsearch:

https://opendev.org/openstack/kolla-ansible/src/branch/stable/xena/ansible/roles/common/defaults/main.yml#L40

append the kolla/configuration.yml with following parameters:

```
fluentd_elasticsearch_user: ""
fluentd_elasticsearch_password: ""
```

this  issue was requested by @linwalth

**Comment by linwalth** [comment]
Thank you for considering this, Mathias!
I would only add to this that the fluentd user/pw should probably generally be in the secrets.yml and not the configuration.yml.

**Comment by berendt** [comment]
@matfechner Can you please add the missing documentation the next days? Would like to close this issue.

**Comment by matfechner** [comment]
@berendt yes i will do this
