### ISSUE TITLE
align default branch names: master -> main

### ISSUE THREAD

**Issue by frosty-geek** [osism/issues#21]
Hi,

cfg-cookiecutter already switched to "main" as default branch, this repo should do the same to stay aligned.

HINT: this may need changes in cfg-cookiecutter default config

I'm not working on a pull request and this is low prio  IMHO

Regards,
Ralf

**Comment by berendt** [comment]
- [ ] container-image-kolla-ansible
- [ ] container-image-ceph-ansible
