### ISSUE TITLE
Flag to fix cloud-init issues

### ISSUE THREAD

**Issue by flyersa** [osism/issues#213]
If openstack is installed with osism in certain environments that utilize cloud-init such as PXE booting from MaaS environments there can issues arrise by overriding netplan configs and hosts file upon reboot after osism bootstrap by cloud-init.

This causes multiple issues (nova vnc, no internal api availability etc.) with openstack services if hostnames are not fully resolvable for some reason by the internal hosts dns resolvers (which can happen in certain scenarios).

While this is not a osism issue directly it would anyway maybe be a good idea to add some kind of flag like cloudinit_no_overrides: true in a ansible config that will disable cloud inits ability to override hosts file and netplan configs in /etc/cloud/cloud.cfg ?

**Comment by berendt** [comment]
Makes sense to me.

**Comment by berendt** [comment]
@flyersa Do you think we could just include this in the cleanup role and completely remove existing Cloud Init configuration and Cloud Init itself after First Boot?

**Comment by flyersa** [comment]
Yes i think removing it completly would not cause any issues. In case of redeployment it needs to be setup again anyway by MaaS as example.
