### ISSUE TITLE
Evaluate and document how to use Bifrost with an air gap

### ISSUE THREAD

**Issue by berendt** [osism/issues#216]
When deploying Bifrost, a variety of things are post-installed inside the Bifrost container via Ansible. As a result, external connectivity is required during the deployment of Bifrost. Which makes it more difficult to implement the provision of Bifrost in an environment with air gap.

It should therefore be examined whether and how the installation of Bifrost can be implemented in such a way that it can take place without (or with less) external connectivity.

**Comment by muellerbe** [comment]
https://docs.openstack.org/bifrost/latest/install/offline-install.html

**Comment by muellerbe** [comment]
(bifrost-deploy)[root@mgr2 bifrost-10.2.1.dev29]# grep "_git_url:" /bifrost/playbooks/roles/bifrost-prep-for-install/defaults/main.yml
dib_git_url: "{{ git_url_root }}/openstack/diskimage-builder"
ironicclient_git_url: "{{ git_url_root }}/openstack/python-ironicclient"
openstacksdk_git_url: "{{ git_url_root }}/openstack/openstacksdk"
ironic_git_url: "{{ git_url_root }}/openstack/ironic"
ironicinspector_git_url: "{{ git_url_root }}/openstack/ironic-inspector"
ironicinspectorclient_git_url: "{{ git_url_root }}/openstack/python-ironic-inspector-client"
reqs_git_url: "{{ git_url_root }}/openstack/requirements"
staging_drivers_git_url: "{{ git_url_root }}/x/ironic-staging-drivers"
keystone_git_url: "{{ git_url_root }}/openstack/keystone"
sushy_git_url: "{{ git_url_root }}/openstack/sushy"
ipa_git_url: "{{ git_url_root }}/openstack/ironic-python-agent"
ipa_builder_git_url: "{{ git_url_root }}/openstack/ironic-python-agent-builder"
prometheus_exporter_git_url: "{{ git_url_root }}/openstack/ironic-prometheus-exporter"

**Comment by muellerbe** [comment]
bifrost.yml - file:///etc/bifrost/git is an example path

# Offline
ironicclient_git_url: file:///etc/bifrost/git/python-ironicclient
ironic_git_url: file:///etc/bifrost/git/ironic
dib_git_url: file:///etc/bifrost/git/diskimage-builder
openstacksdk_git_url: file:///etc/bifrost/git/openstacksdk
ironicinspector_git_url: file:///etc/bifrost/git/ironic-inspector
ironicinspectorclient_git_url: file:///etc/bifrost/git/python-ironic-inspector-client
reqs_git_url: file:///etc/bifrost/git/requirements
staging_drivers_git_url: file:///etc/bifrost/git/ironic-staging-drivers
keystone_git_url: file:///etc/bifrost/git/keystone
sushy_git_url: file:///etc/bifrost/git/sushy
ipa_git_url: file:///etc/bifrost/git/ironic-python-agent
ipa_builder_git_url: file:///etc/bifrost/git/ironic-python-agent-builder
prometheus_exporter_git_url: file:///etc/bifrost/git/ironic-prometheus-exporter

**Comment by muellerbe** [comment]
https://opendev.org/openstack/bifrost/src/branch/master/playbooks/roles/bifrost-prep-for-install/defaults/main.yml

**Comment by berendt** [comment]
No longer needed. We use osism/node Image today or MAAS to provide initial systems.
