### ISSUE TITLE
RFE role for collecting hardware data

### ISSUE THREAD

**Issue by muellerbe** [osism/issues#220]
do OSISM want to have a role for collecting hardware data like lspci or lstopo?
untiil now we have a role for collecting lspci and lstopo data on each node, tar this, fetch to manager and cleanup on all nodes, this role could be enhanced for other hardware data collecting commands

one more question is, where to add this role, if you want this

**Comment by berendt** [comment]
We already have with sosreport.

https://github.com/osism/ansible-collection-commons/blob/main/roles/sosreport/defaults/main.yml#L10-L35
