### ISSUE TITLE
Docker-CLI package 5:20.10.16 not found while installing Docker

### ISSUE THREAD

**Issue by linwalth** [osism/issues#222]
Trying to upgrade Docker i run into the following error:
`"E: Version '5:20.10.16*' for 'docker-ce-cli' was not found\n", "stderr_lines": ["E: Version '5:20.10.16*' for 'docker-ce-cli' was not found"]`

**Comment by berendt** [comment]
```
dragon@testbed-manager:~$ dpkg -l docker-ce-cli
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version                    Architecture Description
+++-==============-==========================-============-========================================================
ii  docker-ce-cli  5:20.10.6~3-0~ubuntu-focal amd64        Docker CLI: the open-source application container engine
```

**Comment by linwalth** [comment]
Thank you for the input. Makes sense. So would I be correct in assuming that 20.10.16 just has no packages yet?
Looking at the docker docs it seems that way (latest is 20.10.15):
https://docs.docker.com/engine/release-notes/

Then the problem would be that 20.10.16 is defined here:
https://github.com/osism/ansible-collection-services/blob/a3aae4d542c16688f11fde7062ac3f79704edd35/roles/docker/defaults/main.yml#L87

**Comment by linwalth** [comment]
i stand corrected: https://download.docker.com/linux/ubuntu/dists/focal/stable/binary-amd64/Packages 20.10.16 exists, but it seems my manager node is unable to find it.

**Comment by linwalth** [comment]
Running apt update manually solved the hiccup. I was able to install 20.10.16.
