### ISSUE TITLE
Check all container images for old URLs

### ISSUE THREAD

**Issue by berendt** [osism/issues#23]
```
                "org.opencontainers.image.documentation": "https://docs.osism.de",
                "org.opencontainers.image.licenses": "ASL 2.0",
                "org.opencontainers.image.revision": "a89aa3d756f41b80c16bcc0865310016ea2b22e8",
                "org.opencontainers.image.source": "https://github.com/osism/container-image-ara-server",
                "org.opencontainers.image.url": "https://www.osism.de",
```

osism.de should be osism.tech. Shell all container images for wrong URLs and fix them.

**Comment by tibeer** [comment]
- [ ] container-image-uyuni/Containerfile
- [ ] container-image-awxclient/Containerfile
- [ ] container-image-ara-server/Containerfile
- [ ] container-image-openstackclient/Containerfile
- [ ] testbed/environments/openstack/playbook-bootstrap-basic.yml
- [ ] testbed/docs/source/conf.py
- [ ] testbed/docs/source/notes.rst
- [ ] testbed/README.md
- [ ] ansible-collection-commons/.github/templates/galaxy.yml.j2
- [ ] ansible-collection-commons/galaxy.yml
- [ ] website/source/.htaccess
- [ ] container-image-osism-ansible-enterprise/Containerfile
- [ ] container-image-osism-ansible-enterprise/scripts/build.sh
- [ ] container-images-kolla/templates/wallaby/template-overrides.mako
- [ ] container-images-kolla/templates/victoria/template-overrides.mako
- [ ] container-images-kolla/templates/latest/template-overrides.mako
- [ ] testbed-edge/environments/kolla/files/overlays/bifrost/bifrost.yml
- [ ] testbed-edge/docs/bifrost-image-handling.md
- [ ] testbed-edge/contrib/update-image.sh
- [ ] container-image-manager-runner/scripts/build.sh
- [ ] container-image-heimdall/Containerfile
- [ ] container-image-healthcheck/Containerfile
- [ ] container-image-kosmoo/Containerfile
- [ ] company-guide/source/conf.py
- [ ] openstack-configuration-validator/Containerfile
- [ ] ansible-collection-validations/galaxy.yml
- [ ] cfg-generics/README.md
- [ ] container-image-jenkins/Containerfile
- [ ] ansible-collection-services/.github/templates/galaxy.yml.j2
- [ ] ansible-collection-services/galaxy.yml
- [ ] container-image-patchman/Containerfile
- [ ] container-image-cephclient/Containerfile
- [ ] container-image-manager/scripts/build.sh
