### ISSUE TITLE
Publish ansible collection documentations to docs.osism.tech

### ISSUE THREAD

**Issue by berendt** [osism/issues#235]

**Comment by osfrickler** [comment]
Initial job is working now, publishing ansible-collection-commons docs to https://docs.staging.osism.tech/ansible-collection-commons/index.html: 
https://zuul.osism.xyz/t/osism/build/3e4e9e3dccb84e3bbd7f758fa874c5d7

Next steps:
- run the job on the other collection repos
- switch the job to publish to the production site
