### ISSUE TITLE
Ansible lint: Discussion Ansible FQCN check

### ISSUE THREAD

**Issue by ra-rau** [osism/issues#238]
We have to discuss which collections we want to check and which not. At this time only the ansible.builtins. will be checked by default-rule fqcn_builtin. It is hard coded in the rule. We have diffrent options now:
1. We could expend the existent rule and hard code all other collections we use too. 
2. We could make a new rule which includes a config file. In this file we can again hard code the collections we are using.
3. We can modify the existing rule for testing only the right writing like   * . * . * :    This fits not for all roles from OSISM. Because we have some custom collections we use at this time. But we have the possibility to use path excludes to skip the check for some files.

Here you can find the code from the fqcn-builtin rule:
https://github.com/ansible/ansible-lint/blob/main/src/ansiblelint/rules/fqcn_builtins.py

**Comment by osfrickler** [comment]
I think maybe we should start with a copy of the builtin rule that does the same thing for our own collections. If that works well, we could consider doing the same for other external collections, but it will be more difficult to keep those up to date I guess.
