### ISSUE TITLE
Docker cli-plugin failed

### ISSUE THREAD

**Issue by zach-b1** [osism/issues#239]
Hi the docker cli plugin for dragon user is wrong in version 3.1.0:

```
cat ~/.docker/cli-plugins/docker-compose 
version https://git-lfs.github.com/spec/v1
oid sha256:b2aabbc04768efb0dc73c14d105781dd0aceb7a801d3a27d5113ad8e222f0395
size 25907200

$ docker compose
docker: 'compose' is not a docker command.
See 'docker --help'
```
after delete ~/.docker/cli-plugins/docker-compose works docker compose

**Comment by berendt** [comment]
Related to #240

**Comment by zach-b1** [comment]
isn't fixed

manager version is 3.1

**Comment by berendt** [comment]
Version 3.2.0 is the latest stable version. It works there. If not something in your deployment is missing. Probably you have to run the docker-compose role.
