### ISSUE TITLE
horizon container tag for 3.1.0 release is missing

### ISSUE THREAD

**Issue by rrmichel** [osism/issues#244]
release 3.1.0 trying to pull the horizon tag 20.1.1.dev3.20220328 - which is missing.

quay only provides:
20.1.2.dev3.20220328
20.1.1.dev3.20220321

**Comment by berendt** [comment]
It's broken in the 3.1.0 release. Will fix it with the upcoming 3.2.0 release. Please set the correct image tag via environments/kolla/image.yml for the moment.
