### ISSUE TITLE
Integration of Cephadm-Ceph with Kolla-Fluentd

### ISSUE THREAD

**Issue by linwalth** [osism/issues#246]
Once we are rolling out Ceph via Cephadm, we will have to find a way to integrate the logging on the Ceph machines with the Kolla FluentD.

Ramifications I have run into so far: 
- Kolla-FluentD knows not of the Ceph User (=> Container-Mounted Ceph Log Dirs cannot be read)
- This concerns thus the way we log: Maybe make Ceph send log to FluentD via Rsyslog?
etc, pp.

**Comment by berendt** [comment]
I'll close this for now. The switch to cephadm is currently not planned since the deprectation of ceph-ansible has been removed. Therefore, from our point of view, there is no need to integrate ceph-adm in any way.
