### ISSUE TITLE
ironic-inspector missing image tag

### ISSUE THREAD

**Issue by rrmichel** [osism/issues#249]
Release: OSISM 3.1.0

Deployment tryed to pull quay.io/osism/ironic-inspector:18.2.2.dev20.20220328

Available is only 
10.8.1.dev3.20220328 
10.8.1.dev3.20220321

**Comment by berendt** [comment]
Will be fixed with the next release. For the moment overwrite the images.

**Comment by berendt** [comment]
Is repaired in the CI. Will fit with 4.0.0.
