### ISSUE TITLE
create possibility to undo Openstack service rollouts

### ISSUE THREAD

**Issue by linwalth** [osism/issues#255]
Having had to roll back a service manually and then investigating the services which have rolled out config depending on the service i unrolled I feel like ultimately there ought to be a solution to undo service rollouts in a more automated and controlled way.

Necessities regarding this beyond configuration management include removing entries from the central Openstack Database, and removal of containers and container images.

https://github.com/osism/mappings is probably the place where this would start.

**Comment by berendt** [comment]
As a first step, I would document that first. Not sure if it is worth to automate this.

**Comment by berendt** [comment]
@linwalth Which services specifically did you want to roll back?

**Comment by linwalth** [comment]
Trove, in this case. But another usecase would be cleaning up residual service containers (and volumes!) after migrating services from one server to another. Maybe a blanket solution checking and deleting containers and volumes from servers where they are not supposed to be is more fitting than specific rollbacks.

Or just delete the containers manually, as it is not a big and/or recurring hassle.

**Comment by berendt** [comment]
Will close this in favour of #302. We need some mechanism to check and ensure that everything that should run on a system is running and everything that is running and should not be running can be removed in some way.
