### ISSUE TITLE
Hashicorp Consul/Vault Service?

### ISSUE THREAD

**Issue by ghost** [osism/issues#258]
Hi,

we have the need for a highly-available hierarchical key/value store to store metadata for Openstack resources. Hashicorp Consul would be a perfect and easy fit.

As for deploying and operating Openstack with the OSISM there is also need for storing and accessing credentials in an automated fashion. Having this need as well, Vault would be a nice match that serves both approaches.

So, my question is: Are there chances to get Hashicorp Vault service (or just Consul) included in the OSISM tool stack?

Best,
André

**Comment by berendt** [comment]
As discussed during the Lean Coffee, we will use the Vault service only as a view on the Secrets in the Configuration Repository and not as a service that can be consumed independently of the Management Plane.

The same applies to Consul. We do not currently plan to use Consul on the Management Plane. The same applies to the Control Plane.
