### ISSUE TITLE
Create openvswitch_exporter image

### ISSUE THREAD

**Issue by berendt** [osism/issues#26]
Kolla is still missing an image for the openvswitch_exporter.

Refer to https://review.opendev.org/c/openstack/kolla/+/762986 for it. This is the new image for the OVN Exporter.

As a binary, our fork of openvswitch_exporter is to be used:  https://github.com/osism/openvswitch_exporter

**Comment by osfrickler** [comment]
https://review.opendev.org/c/openstack/kolla/+/812463
