### ISSUE TITLE
Setup new registry.osism.tech system

### ISSUE THREAD

**Issue by berendt** [osism/issues#28]
Got a 14 * 16 TByte system from Hetzner so we can set up the registry.osism.tech there and keep all the builds of the Docker images, especially the PRs, in the future.

**Comment by tibeer** [comment]
Plan is to use LVM with Longhorn as default storage backend. Need to device if there should be one big logical volume (LV) or two equally sized LVs for potential backup solution. Knowing that backing up data on the same machine is a bad idea, we do not require the service to be up 24/7. If there is a disk outage, we can easily swap it and pull the data from the backup disk in the same system.

**Comment by tibeer** [comment]
Probably look into LVM mirroring: https://wiki.gentoo.org/wiki/LVM/de#Mirrored_volumes
1 disk for system
1 disk for LVM log
6*16TB LV1
6*16TB LV1mirror

**Comment by tibeer** [comment]
resolved by @berendt
