### ISSUE TITLE
Missing sudo in container quay.io/osism/kolla-ansible:wallaby

### ISSUE THREAD

**Issue by zach-b1** [osism/issues#286]
Hello

in the Container "quay.io/osism/kolla-ansible:wallaby" isn't sudo installed and configurated, please fixed.

Following error Message is coming by deploy common

osism-kolla deploy common

TASK [common : Find custom fluentd input config files] *******************************************************************************************************************************************************************************************************
fatal: [xxx -> localhost]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: 1: sudo: not found\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 127}

NO MORE HOSTS LEFT

**Comment by berendt** [comment]
The task does not require sudo: https://github.com/openstack/kolla-ansible/blob/stable/wallaby/ansible/roles/common/tasks/config.yml#L82-L89

Also In the testbed the tasks works as expected. Do you enforce the use of become somewhere in the Ansible configuration?

sudo should not be required at all in the kolla-ansible container image.

**Comment by berendt** [comment]
We removed sudo more than 18 months ago from kolla-ansible: https://github.com/osism/container-image-kolla-ansible/commit/625fbfba52c73590cd6a53c15be4ce7902c38877. This is definitely due to something else.

**Comment by zach-b1** [comment]
Hi @berendt 
thanks for the Information, after remove ansible_become option out the kolla configuration.yml works .
