### ISSUE TITLE
Ceph/Openstack Version Defaults per Manager Version

### ISSUE THREAD

**Issue by linwalth** [osism/issues#289]
Defaults von Ceph und openstack Version werden, falls nicht gesetzt, auf die ManagerVersion gesetzt.
https://github.com/osism/testbed/blob/f0cfc14278ff8ce3ccfc70b5bb17ad0aaeb8dbed/environments/manager/images.yml#L49
Der Default könnte also gar nicht auf die default openstack/ceph version defaulten, weil die manager_version zuerst kommt.
Mit der kann Kolla/Ceph allerdings nichts anfangen, da es bei Openstack zB xena oder yoga erwartet. (Ceph analog pacific oder quincy)

**Comment by berendt** [comment]
Makes no sense to use the manager_version by default there.
