### ISSUE TITLE
Use organization-wide variables for DOCKER_*

### ISSUE THREAD

**Issue by berendt** [osism/issues#29]
Currently, DOCKER_* is used for each repository. Organization-wide variables should be used instead.

**Comment by ra-rau** [comment]
Here is a list of affected repositories:
- [ ] container-image-inventory-reconciler
- [ ] container-images-kolla
- [ ] container-image-uyuni
- [ ] container-image-ceph-ansible
- [ ] container-images
- [ ] openstack-configuration-validator
- [ ] python-osism

**Comment by berendt** [comment]
Migrated to the new Harbor instance harbor.services.osism.tech and introduced organisation secrets for DOCKER_*.
