### ISSUE TITLE
Neutron Upgrade failing due to missing Neutron SSH key

### ISSUE THREAD

**Issue by linwalth** [osism/issues#291]
Neutron Upgrade Failed, because the Neutron SSH key was undefined. We had to create the key and the ansible var/dict ourselves.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/__init__.py", line 1160, in do_template
    res = j2_concat(rf)
  File "<template>", line 12, in root
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'neutron_ssh_key' is undefined

sudo -E kolla_set_configs
INFO:__main__:Loading config file at /var/lib/kolla/config_files/config.json
INFO:__main__:Validating config file
INFO:__main__:Kolla config strategy set to: COPY_ALWAYS
INFO:__main__:Copying service configuration files
INFO:__main__:Copying /var/lib/kolla/config_files/neutron.conf to /etc/neutron/neutron.conf
INFO:__main__:Setting permission for /etc/neutron/neutron.conf
INFO:__main__:Copying /var/lib/kolla/config_files/neutron_vpnaas.conf to /etc/neutron/neutron_vpnaas.conf
INFO:__main__:Setting permission for /etc/neutron/neutron_vpnaas.conf
INFO:__main__:Copying /var/lib/kolla/config_files/ml2_conf.ini to /etc/neutron/plugins/ml2/ml2_conf.ini
INFO:__main__:Setting permission for /etc/neutron/plugins/ml2/ml2_conf.ini
ERROR:__main__:MissingRequiredSource: /var/lib/kolla/config_files/id_rsa file is not found

**Comment by osfrickler** [comment]
AFAICT there is no good way to create new secrets automatically. The key will be generated by a fresh cookiecutter run for a yoga deployment. We need to add a note to the release notes that this needs to be done manually on upgrades.

**Comment by fkr** [comment]
good catch @linwalth - finding items like these will cause the upgrade notes to be even better for the release. thanks!

**Comment by berendt** [comment]
Has to be added to the upgrade notes. No way to automate this.
