### ISSUE TITLE
Openstack Exporter FQDN missing

### ISSUE THREAD

**Issue by linwalth** [osism/issues#297]
Kolla defines the OS-Exporter behind the LB. When using a certificate that does not include the LB address as SAN this leads to a certificate problem, because it defines the address to scrape and not the FQDN the certificate expects.

https://github.com/openstack/kolla-ansible/blob/6cab1fcbd070d4c002e6e67c552996415b223fe0/ansible/roles/prometheus/templates/prometheus.yml.j2#L110

To fix this it would be necessary to make use of kolla_internal_fqdn in this configuration stanza instead of using the internal api LB address. 

Since Kolla defines kolla_internal_fqdn from kolla_internal_vip_address this should not create any breaking changes in the mechanism for deployments which just use the IP address:

https://github.com/openstack/kolla-ansible/blob/7c36bbfa00b6c5b6897ae2086529cb527b348f6c/ansible/group_vars/all.yml#L49

**Comment by berendt** [comment]
Is that still a problem at the moment?

**Comment by linwalth** [comment]
Not for me, as I have been using a prometheus.yml overlay file as workaround, which I then decided to keep due to unrelated configuration-merge-based necessities.

It is not a priority topic for me - For newcomers it might be a problem though, so I would like to see it upstream.

**Comment by maliblatt** [comment]
We have the same issue and we also workarounded it with an overlay file.
I have also opened an upstream issue that morning for it: https://bugs.launchpad.net/kolla-ansible/+bug/2008208
