### ISSUE TITLE
ceph quincy update missing module/action

### ISSUE THREAD

**Issue by maliblatt** [osism/issues#298]
after upgrading the ceph-ansible container on the manager to quincy we are getting an error when trying to perform the ceph upgrade:
```
dragon@manager1-dev1-az0:~$ osism-ceph rolling_update -e @/ansible/group_vars/all/099-generic.yml

ERROR! couldn't resolve module/action 'openstack.config_template.config_template'. This often indicates a misspelling, missing collection, or incorrect module path.
```

This comes from /ansible/roles/ceph-config/tasks/main.yml, line 128:
```
- name: "generate {{ cluster }}.conf configuration file"
  openstack.config_template.config_template:
```

Is there something missing or did we do something wrong?

**Comment by berendt** [comment]
Thanks for testing. Quincy is currently in preparation. Do not use yet. Will also not be included in the release.

**Comment by berendt** [comment]
That should have been done by now.
