### ISSUE TITLE
Rename build/release-docker-image workflows to build-release-container-image

### ISSUE THREAD

**Issue by berendt** [osism/issues#30]
in ```.github/workflows``` rename existing files:

* ```build-docker-image.yml``` -> build-container-image.yml
* ```release-docker-image.yml``` -> release-container-image.yml

within the files match the name and the new filename:

* ```name: Build docker image```--> ```name: Build container image```
* ```      - .github/workflows/build-docker-image.yml``` --> ```      - .github/workflows/build-container-image.yml```
* ```  build-docker-image:``` --> ```  build-docker-image:```

**Comment by ra-rau** [comment]
@berendt: done
