### ISSUE TITLE
Discuss the merge of all openstack-*-manager projects

### ISSUE THREAD

**Issue by berendt** [osism/issues#317]
At the moment we have the following manager projects:

* opentack-image-manager
* openstack-sandbox-manager
* openstack-project-manager
* openstack-flavor-manager

openstack-simple-stress is also related.

Idea: let's provide an OpenStack Swiss Army Knife that integrates all those tools into one single tool.

**Comment by fkr** [comment]
makes a lot of sense imho

**Comment by berendt** [comment]
Add the orphaned resource identifier/cleaner to the new tool

**Comment by berendt** [comment]
I think the discussion is done. The merge itself will then take place via an SCS Epic.
