### ISSUE TITLE
Replace proprietary Elasticsearch and Kibana with Opensearch

### ISSUE THREAD

**Issue by bernhardreiter** [osism/issues#318]
Elasticsearch is listed as part of the available services, e.g. https://docs.osism.tech/overview/service-architecture.html has it mentioned under Logging. 

As Elasticsearch just like Kibana is not Open Source anymore since early 2021,  e.g. see https://en.wikipedia.org/wiki/Elasticsearch#Licensing_changes

From my understanding o OSISM's goals, replacing Elasticsearch and Kibana with something like Opensearch (https://www.opensearch.org/) is necessary to keep everything being "Open Source".

**Comment by berendt** [comment]
This is now done in Kolla's Zed release. We will deliver this with the upcoming 5.0.0 release. It can already be used in Latest with the rolling tag on Zed.
