### ISSUE TITLE
Evaluate using Mitogen to speed up Ansible

### ISSUE THREAD

**Issue by linwalth** [osism/issues#333]
To speed up Ansible it would be useful to utilize the Mitogen strategy plugin.
https://mitogen.networkgenomics.com/ansible_detailed.html
Kolla as well as OSISM altogether could benefit from the speed boost that Mitogen provides.
https://github.com/mitogen-hq/mitogen/releases/tag/v0.3.0-rc.0

**Comment by berendt** [comment]
We used to have this as a plug-in in the past. Then Mitogen was not updated for new Ansible versions for a long time. In the meantime they seem to be able to do Ansible 5 and 6 as well. I like to throw it into the latest builds, then you can test if it changes something of the runtimes for you.

**Comment by linwalth** [comment]
sounds great. keep me posted and i will update the manager containers and see how it works out.

**Comment by berendt** [comment]
* osism-ansible merged. Will run some tests tomorrow and then I will add the plugin to ceph-ansible & kolla-ansible

**Comment by linwalth** [comment]
Running kolla-facts on the kolla-ansible container showed the mitogen runs to be about a minute faster.

**Comment by berendt** [comment]
@linwalth Can you please add the required Ansible configuration to be able to use the Mitogen plugin.

**Comment by linwalth** [comment]
[defaults]
strategy_plugins = /usr/share/ansible/plugins/mitogen/ansible_mitogen/plugins/strategy
strategy = mitogen_linear

**Comment by berendt** [comment]
Let's test everything: https://github.com/osism/testbed/pull/1370

**Comment by linwalth** [comment]
Running osism-generic facts with the latest osism-ansible container showed no difference. Yet, as described above, the differences between non-mitogen and mitogen running kolla-facts were considerable at one minute difference. (Specifically since the manager was under load when I was running the mitogen test)

**Comment by berendt** [comment]
It's not working with ceph-ansible. Details are in the prepare testbed PR.
