### ISSUE TITLE
Strongswan Driver can't be loaded by neutron L3 Agent 

### ISSUE THREAD

**Issue by pjsinka** [osism/issues#346]
While trying to deploy Neutron VPNaaS we stumbled upon the following: 

`WARNING stevedore.named [req-21184ed2-e5c9-4137-b34c-29c51c282528 - - - - -] Could not load neutron_vpnaas.services.vpn.device_drivers.strongswan_ipsec.StrongSwanDriver
INFO neutron.agent.agent_extensions_manager [req-7e21da0e-ff6a-4fe4-8508-2e358d96a1c8 - - - - -] Loaded agent extensions: ['vpnaas', 'port_forwarding']`

We checked if strongswan was installed and it was:

`libstrongswan/now 5.8.2-1ubuntu3.5 amd64 [installed,local]
strongswan-charon/now 5.8.2-1ubuntu3.5 amd64 [installed,local]
strongswan-libcharon/now 5.8.2-1ubuntu3.5 amd64 [installed,local]
strongswan-starter/now 5.8.2-1ubuntu3.5 amd64 [installed,local]
strongswan/now 5.8.2-1ubuntu3.5 all [installed,local]`

**Comment by berendt** [comment]
Which service is the log from?

**Comment by pjsinka** [comment]
`/var/log/kolla/neutron/neutron-l3-agent.log.1: ERROR neutron_lib.rpc [-] Timeout in RPC method get_vpn_services_on_host. Waiting for 55 seconds before next attempt. If the server is not down, consider increasing the rpc_response_timeout option as Neutron server(s) may be overloaded and unable to respond quickly enough.: oslo_messaging.exceptions.MessagingTimeout: Timed out waiting for a reply to message ID 6ffb2393268e4b309362e48634acfa57
/var/log/kolla/neutron/neutron-l3-agent.log.1: WARNING neutron_lib.rpc [-] Increasing timeout for get_vpn_services_on_host calls to 120 seconds. Restart the agent to restore it to the default value.: oslo_messaging.exceptions.MessagingTimeout: Timed out waiting for a reply to message ID 6ffb2393268e4b309362e48634acfa57
/var/log/kolla/neutron/neutron-l3-agent.log.1: ERROR neutron.agent.l3.agent   File "/var/lib/kolla/venv/lib/python3.8/site-packages/neutron_vpnaas/services/vpn/agent.py", line 75, in update_router
/var/log/kolla/neutron/neutron-l3-agent.log.1: ERROR neutron.agent.l3.agent   File "/var/lib/kolla/venv/lib/python3.8/site-packages/neutron_vpnaas/services/vpn/device_drivers/ipsec.py", line 1122, in sync
/var/log/kolla/neutron/neutron-l3-agent.log.1: ERROR neutron.agent.l3.agent     vpnservices = self.agent_rpc.get_vpn_services_on_host(
/var/log/kolla/neutron/neutron-l3-agent.log.1: ERROR neutron.agent.l3.agent   File "/var/lib/kolla/venv/lib/python3.8/site-packages/neutron_vpnaas/services/vpn/device_drivers/ipsec.py", line 799, in get_vpn_services_on_host
/var/log/kolla/neutron/neutron-l3-agent.log.1: ERROR neutron.agent.l3.agent     return cctxt.call(context, 'get_vpn_services_on_host', host=host)
/var/log/kolla/neutron/neutron-l3-agent.log.1: WARNING stevedore.named [req-18207101-1659-4a32-804b-dbb8122c6348 - - - - -] Could not load neutron_vpnaas.services.vpn.device_drivers.strongswan_ipsec.StrongSwanDriver
/var/log/kolla/neutron/neutron-l3-agent.log.1: INFO neutron.agent.agent_extensions_manager [req-8fc25bdf-a320-427a-80a1-ca6b5b0d9069 - - - - -] Loaded agent extensions: ['vpnaas', 'port_forwarding']
/var/log/kolla/neutron/neutron-l3-agent.log.1: INFO neutron.agent.agent_extensions_manager [req-8fc25bdf-a320-427a-80a1-ca6b5b0d9069 - - - - -] Initializing agent extension 'vpnaas'`

**Comment by linwalth** [comment]
It is a log from the neutron-l3-agent container.

**Comment by flyersa** [comment]
This can be closed.

The warning is kind of normal as it seems to be a bug with neutron-vpnaas. It will complain about this with all drivers. That a VPN service is not going out of Pending_Create is also normal, it will only be created once it is associated with a IPSec Connection. Until there is no ipsec connection defined it will remain in pending_create

**Comment by berendt** [comment]
Thanks for testing. Let's add some documentation snippet for it.
