### ISSUE TITLE
Prepare a list of Pulp alternatives

### ISSUE THREAD

**Issue by berendt** [osism/issues#348]
Goal is to provide (airgapped) mirrors for:
- Ansible Galaxy Roles and Collections
- APT packages
- Container images
- PIP packages

**Comment by tibeer** [comment]
We will use the following tool (at the moment) to achieve mirror capabilities:

|Package Technology|Mirror-Tool|
|---|---|
|Ansible Roles / Collections|We will build our own|
|APT/DEB packages|aptly|
|Container images|registry (from docker)|
|PIP packages|bandersnatch|

**Comment by berendt** [comment]
The Docker registry service got a new name: distribution.

https://github.com/distribution/distribution

**Comment by fkr** [comment]
@tibeer is working on an alternative for galaxy: http://github.com/osism/python-ansible-wormhole
