### ISSUE TITLE
Zun Images missing

### ISSUE THREAD

**Issue by flyersa** [osism/issues#360]
Hello,

we have a usecase for zun. Zun itself should be pretty straight forward with kolla. Looks like osism has no images for zun?

On zun deploy i get:

manifest for quay.io/osism/zun-api:yoga not found: manifest unknown: manifest unknown

can we have zun images please? Maybe also if images are added that will not be officially supported by osism etc. add some config flag or something like "use_not_supported_images: true" ?

**Comment by berendt** [comment]
You can find a list of all supported services here: https://github.com/osism/release/blob/main/4.1.0/openstack-yoga.yml#L44-L69

We will deprecate some of them with the next release (see https://github.com/osism/release/pull/586).

We are not currently planning to support Zun. Please join us at one of the Wednesday meetings of the SCS meeting to discuss the requirement.

**Comment by flyersa** [comment]
Is there any progress here? I would like to see Zun Images. It has no large depedencies or big overhead. Did you discuss that ?

**Comment by berendt** [comment]
You have not been to a weekly meeting to discuss this.

**Comment by flyersa** [comment]
well thats why i ask here.

**Comment by berendt** [comment]
As temporary solution until we found a way to discuss this in the context of the SCS project you can already use Zun from the Kolla upstream repository. Add the following entries into your ``environments/kolla/images.yml`` file:

```
zun_tag: "zed-ubuntu-jammy"
zun_api_image: "quay.io/openstack.kolla/zun-api"
zun_api_tag: "{{ zun_tag }}"
zun_wsproxy_image: "quay.io/openstack.kolla/zun-wsproxy"
zun_wsproxy_tag: "{{ zun_tag }}"
zun_compute_image: "quay.io/openstack.kolla/zun-compute"
zun_compute_tag: "{{ zun_tag }}"
zun_cni_daemon_image: "quay.io/openstack.kolla/zun-cni-daemon"
zun_cni_daemon_tag: "{{ zun_tag }}"
```

You also have to add ``enable_zun: "yes"`` into your ``environments/kolla/configuration.yml`` file.

Do configure Docker to be usable with Zun you have to set ``docker_zun: true`` for all nodes running the ``zun-compute`` service.

**Comment by flyersa** [comment]
Thank you for this information. Do you have an idea what zun_cni_version needs to be set too?  By default i get errors like this:

`fatal: [hv08.fs.stackxperts.com]: FAILED! => {"changed": true, "cmd": ["docker", "cp", "zun_cni_daemon:/opt/loopback", "/opt/cni/bin/"], "delta                                                                  ": "0:00:00.047264", "end": "2023-03-07 09:50:58.690243", "msg": "non-zero return code", "rc": 1, "start": "2023-03-07 09:50:58.642979", "stder                                                                  r": "invalid output path: directory \"/opt/cni\" does not exist", "stderr_lines": ["invalid output path: directory \"/opt/cni\" does not exist"                                                                  ], "stdout": "", "stdout_lines": []}
`

outside of etcd not working because it complains about missing cert and key configuration. Guess i need to figure this out too.

**Comment by berendt** [comment]
The /opt/cni directory is created by the osism.services.docker role:

https://github.com/osism/ansible-collection-services/blob/main/roles/docker/defaults/main.yml#L188-L197

You first have to enable the Zum integration in osism.services.docker, have to re-deploy the Docker service, then you can deploy Zun.

For the certificates required by etcd service have a look at https://github.com/openstack/kolla-ansible/blob/master/ansible/roles/etcd/tasks/copy-certs.yml.

**Comment by fkr** [comment]
@berendt is this something worthwhile to document?

**Comment by berendt** [comment]
In the meanwhile we re-enabled the build of the Zun images.
