### ISSUE TITLE
Manila windows_smb pywinrm is missing

### ISSUE THREAD

**Issue by zach-b1** [osism/issues#363]
Hello

I try to deploy manila with windows_smb backend and in the log I found the messages, that pywinrm missing.

It's possible to add the packages in the container of manila-share?

**Comment by berendt** [comment]
Please be aware that we do not support the Manila service at the moment and that is is only available as untested technical preview. It is not recommended to use it for productive environments.

If there is a requirement from the customer side for this service, please coordinate with us in advance.

We will add the missing package. However, only when images for Zed are available. The packages will not be included in Xena or Yoga.
