### ISSUE TITLE
Power monitoring issue for HP Servers

### ISSUE THREAD

**Issue by rmueller-b1** [osism/issues#365]
We ran into a bug for HP Servers causing them to crash after some time. This issue is known and there is an easy fix: https://wiki.froberg.org/en/hp-proliant-acpi-error-power-meter
The 3 kernel modules provided in the link should be added to the repository for easy implementation. I tried to add them in enviornment/configuration.yml and roll them out but the modules were not loaded. The provided fix itself is working when you execute the steps manually.

**Comment by berendt** [comment]
Please provide the configuration you added to the configuration as well as the command you tried to load the modules.

**Comment by rmueller-b1** [comment]
I added it to the kernel modules part and tried to roll it out via `osism apply common`
```
# kernel modules

kernel_modules_extra:
...
  - ipmi_si
  - acpi_ipmi
  - acpi_power_meter
```

**Comment by berendt** [comment]
``common`` applies the common role provided by Kolla. You want to apply the ``osism.commons.kernel_modules`` role. You can do this via ``osism apply kernel-modules`` (https://github.com/osism/python-osism/blob/main/osism/commands/apply.py#L90).

**Comment by berendt** [comment]
I think that's done. Otherwise, open again.
