### ISSUE TITLE
Check how local disks are deleted in the Nova service

### ISSUE THREAD

**Issue by berendt** [osism/issues#369]
In the SCS, a flavour is introduced in which local plates can be used. It must be checked and documented how local disks used in Nova are deleted.

**Comment by osfrickler** [comment]
Currently local disks are simply free again, by removing the file for file-backed disks and by running `lvremove` for LVM-backed disks.

The best solution would likely be to enforce encryption being used, there are some references for this:

https://docs.openstack.org/security-guide/tenant-data/data-encryption.html
https://specs.openstack.org/openstack/nova-specs/specs/pike/approved/libvirt-qemu-native-luks.html
https://review.opendev.org/c/openstack/nova/+/537642/3/releasenotes/notes/qemu-native-luks-decryption-6e9ad8cc658be14d.yaml

This only seems to be supported by the LVM backend.

**Comment by fkr** [comment]
We need to turn this into a proper action item so that we can assure that local volumes are properly shredded.
thanks for researching @osfrickler
