### ISSUE TITLE
Lag of documentation vGPU

### ISSUE THREAD

**Issue by chschilling** [osism/issues#371]
If you want to use vGPU and pci-passthrough in Openstack, documentation is refering to add configurations to /etc/modules and /etc/modprobe.d/vfio.conf

As in Ubuntu 20.04, vfio-pci is part of the kernel. So configuration in modprobe is not working any more.
We managed to get it running by adding configurations to grubdefaults:
`GRUB_CMDLINE_LINUX_DEFAULT="amd_iommu=on iommu=pt vfio_iommu_type1.allow_unsafe_interrupts=1 vfio_pci.ids=10de:20b7"
`
Is there another way to configure it correctly?

If not, would be nice if documentation is corrected as for 20.04

If I can help anywhere, let me know

**Comment by berendt** [comment]
We have not yet had vGPUs in scope. Can we document and test this together? We don't have a GPU test system at the moment.

**Comment by chschilling** [comment]
Would be a pleasure, as we are highly strugeling in implementation.
What about Tomorrow morning or Monday whole day for a meeting?

**Comment by berendt** [comment]
As discussed, we will clarify the details on Monday at 9 am.

**Comment by berendt** [comment]
That has been done in the meantime. There is enough documentation upstream. Bug with mdev was closed by backport.
