### ISSUE TITLE
osism apply wont ask vault_pass

### ISSUE THREAD

**Issue by matfechner** [osism/issues#372]
the osism apply commands don't ask in foreground the vaultpassword with .vault_pass script  in environments. Only if the password is given directly in .vault_pass and  osism apply will work

**Comment by linwalth** [comment]
that is a problem i have run into in the past. +1

**Comment by berendt** [comment]
Duplicate of osism/python-osism#83.

Added a hacky workaround as comment in osism/python-osism#83
