### ISSUE TITLE
Autodetect CPU architecture

### ISSUE THREAD

**Issue by berendt** [osism/issues#374]
In some Ansible roles, the CPU architecture is currently explicitly set by argument. This should be read out automatically from the facts.

E.g. in ``osism.services.docker``:

```
docker_debian_repository_arch: amd64
```

**Comment by lindenb1** [comment]
For reference, I started to implement this for collections-commons -> https://github.com/osism/ansible-collection-commons/pull/570

**Comment by sbstnnmnn** [comment]
→ https://github.com/osism/ansible-collection-services/pull/#1270
