### ISSUE TITLE
Fix nova libvirt containers for mdev / vgpu usage

### ISSUE THREAD

**Issue by chschilling** [osism/issues#380]
Hey there, 
in relation to #371, we are actually trying to document how to use vgpu mdev devices in combination of nvida gpus.

We got it working to have everything configured correctly, resources are provided to placement api and we are able to create exact one vm with vgpu in place.

But then we ran into a nova libvirt bug:

https://bugs.launchpad.net/nova/+bug/1906494

It seems, that the bug is fixed in master and is waiting for merge back to yoga.
Is it possible, to speed things up by patching osism containers directly?

https://review.opendev.org/c/openstack/nova/+/866153

Thanks,

Christian

**Comment by berendt** [comment]
The review mentioned contains only one unit test. I think if we backport that we have no added value. Is there an open review somewhere that fixes the actual problem?

**Comment by chschilling** [comment]
Sorry, wrong bug

https://bugs.launchpad.net/nova/+bug/1951656
https://review.opendev.org/c/openstack/nova/+/866153
https://review.opendev.org/c/openstack/nova/+/866154

**Comment by berendt** [comment]
@chschilling Please test latest Yoga images. Integrated the back port there. Images will be available in appr. 2 hours.

**Comment by chschilling** [comment]
@berendt looks promising!
There is still an issue with reboot of HV, but thats something we need to figure out to how we handle that...

Thanks for backporting
