### ISSUE TITLE
unable to use variable for ansible_host for osism-generic facts

### ISSUE THREAD

**Issue by chschilling** [osism/issues#383]
Hey there,

I am trying to cleanup hostinventory al little bit to keep it simple and don't need to add informations multiple times.
To do so, my host_vars only contains interfaces config:

```
network_interfaces:
  - device: bond0
    family: inet
    method: static
    address: 10.4.0.174
    netmask: 255.255.240.0
    gateway: 10.4.0.1
    mtu: 9000
```

and my group_vars for computes uses:

```
ansible_host: "{{ network_interfaces[0].address }}"
```

That seems to work fine for 

```
osism-generic operator -u ubuntu
osism-generic python3 
osism-generic reboot
```

but fails for 
``` 
osism-generic facts 
```

with 
```
[mux  279880] 11:58:51.357929 D mitogen.parent: command line for Connection(None): ssh -o "LogLevel ERROR" -l dragon -i /ansible/secrets/id_rsa.operator -o "Compression yes" -o "ServerAliveInterval 30" -o "ServerAliveCountMax 10" -o "BatchMode yes" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -o "GlobalKnownHostsFile /dev/null" -C -o ControlMaster=auto -o ControlPersist=60s "{{ network_interfaces[0].address }}" /usr/bin/python3 -c...

fatal: [<node>]: UNREACHABLE! => {
    "changed": false,
    "msg": "EOF on stream; last 100 lines received:\nssh: Could not resolve hostname {{ network_interfaces[0].address }}: Name or service not known\r",
    "skip_reason": "Host <node> is unreachable",
    "unreachable": true
}
```

I have checked the /ansible/inventory/hosts.yml file which is  created somewhere, and in here, we do have " '{{ network_interfaces[0].address }}' " inserted, which should be the faulty part.

I couldn't find out, where that file is created, seems that there is some kind of bug in there.

Greetings,

Christian

**Comment by berendt** [comment]
``/inventory/hosts.yml`` is generated by the inventory reconciler service (https://github.com/osism/container-image-inventory-reconciler, the container is manager-inventory_reconciler-1). Via https://github.com/osism/container-image-inventory-reconciler/blob/main/files/run.sh.

You can trigger a sync of the reconciler via ``osism reconciler sync``.

I'll look at the problem itself later.

**Comment by chschilling** [comment]
It is an issue with 
```
ansible-inventory -i /inventory.pre --list -y --output /inventory.merge/hosts.yml 
```
as it seems.

That module is not checking correctly for variables, as it seems.
Even simple Combination is not possible:

```
$ cat testhost.yml
testhost: 12345
testsubhost: "{{ testhost }}"

ansible-inventory -i inventory/ --host testhost

{
....
    "testhost": 12345,
    "testsubhost": "{{ testhost }}",
....
}
```

**Comment by chschilling** [comment]
Hey,

any update in here?

Greetings,
Christian

**Comment by berendt** [comment]
Still working on it. My holiday has delayed it a bit.

In the meantime, however, there is already a command to display the facts and inventory details of a certain system.

* ``osism dump facts mgr001``
* ``osism dump inventory mgr001``

**Comment by chschilling** [comment]
I switched variablepositions now and moved ansible_host variable to hostvar and all other stuff to groupvar.
It seems so far to work as it should, can you tell me if there will be any sideeffects? 
Don't think that there should happen anything stupid, but whoknows :D

**Comment by berendt** [comment]
Hm. Sounds like this is something that doesn't work in Ansible then. I'll close this then.
