### ISSUE TITLE
improvement: Separate rabbitmq and Galera more granular

### ISSUE THREAD

**Issue by matfechner** [osism/issues#386]
to scale up  the Controlplane it is important to choose more granular on which nodes
infrastructure Services like mysql or rabbitmq should run.

at the moment it will decided by inventory group control

**Comment by berendt** [comment]
This is already possible via the ``rabbitmq`` and ``mariadb`` host groups. Simply add them to the ``99-overwrite`` inventory file.

**Comment by berendt** [comment]
List of all available inventory groups for Kolla can be found here:

* https://github.com/osism/cfg-generics/blob/main/inventory/50-kolla
* https://github.com/osism/cfg-generics/blob/main/inventory/51-kolla

**Comment by berendt** [comment]
Nothing to do here. It's a standard kolla-ansible feature.
