### ISSUE TITLE
Openstack Certificate failure

### ISSUE THREAD

**Issue by rmueller-b1** [osism/issues#387]
Hello,
in our cloud we defined a certificate file for openstack. The file is rolled out to all control nodes. I saw in the ironic_api container a warning that that certificate files contains more than one certificate and is therefore ignored. I ran an "update-ca-certificates --fresh" to verify weather the node itself can use that certificate. I received the same message as I saw in the container.

My suggestion is that this is the cause of an Ironic inspect error I received:
Failed to set boot device to PXE: Failed to set boot device for node <id>
because it tries to reach a https URL (the ILO interface for that node) but gets a 400 error as return. When I use curl to reach that URL I receive: curl: (60) SSL certificate problem: unable to get local issuer certificate

The .crt is defined as cacert in enviornment/kolla/configuration.yml.

I have the following questions about this topic:
1. Why are there 126 certificates in the file /etc/ssl/certs/ca-certificates.crt?
2. Where is the source of those certificates?
3. Why is the system complaining about multiple certificates in one file? We did not have this issue before we reconfigured our cloud.
4. Is it possible that we are missing a package on our nodes that could fix this issue?

Kind regards,
Robert Müller

**Comment by berendt** [comment]
Where have you defined this certificate and how do you do the rollout?

The ``/etc/ssl/certs/ca-certificates.crt?`` on the system itself or inside some of the containers?

**Comment by rmueller-b1** [comment]
The issue itself is not fixed but it was not due to my described issue. Therefore I will close this issue.
Thanks for your support.
