### ISSUE TITLE
Ironic TFTP options

### ISSUE THREAD

**Issue by rmueller-b1** [osism/issues#388]
We discovered an issue during pxe boot while inspecting an ironic node. The node does not get the required files to start the boot process. Below you can see the output of a TCP dump running on the control node that is responsible for the inspection.

$ tcpdump -vvv -i ironic_dhcp
12:51:34.205307 IP (tos 0x0, ttl 64, id 52269, offset 0, flags [none], proto UDP (17), length 1500)
    ctl01.deploy.hpf.basf.net.52279 > 10.74.24.50.1332: [bad udp cksum 0x4ac8 -> 0xd365!] UDP, length 1472

We found a possible solution: we have to set the option --blocksize to a specific value. We tried to set the option in the file /etc/kolla/ironic-tftp/config.json (config file of the ironic_tftp container) but that did not properly set the option in the container.
We need the possiblity to set the option persistent in our OSISM config repository. Please provide a solution for us.

We found the following part in the official openstack dokumentation https://docs.openstack.org/ironic/latest/install/configure-pxe.html

**Comment by berendt** [comment]
``option --blocksize to a specific value`` for which service?

Please share the modified ``/etc/kolla/ironic-tftp/config.json`` file.

**Comment by berendt** [comment]
https://review.opendev.org/c/openstack/kolla-ansible/+/868046 is probably what you want to have. Please check and confirm. I will merge the backport afterwards.

**Comment by schulze-b1** [comment]
yes, this looks good. please merge.
