### ISSUE TITLE
[WARNING]: Removed restricted key from module data: ansible_facts

### ISSUE THREAD

**Issue by berendt** [osism/issues#389]
```
TASK [osism.commons.hosts : Include type specific tasks] ***********************
[WARNING]: Removed restricted key from module data: ansible_facts
```

**Comment by chschilling** [comment]
Hey @berendt,

could it be, that because of that osism-generic hosts is not working anymore?

```
fatal: [host]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_{{ internal_interface|default(eth0) }}'"
```
Greetings

**Comment by berendt** [comment]
Ne does not look related to me. Just tested the role with us. There, it also works without problems.

**Comment by chschilling** [comment]
did you ran the generic facts before?

**Comment by berendt** [comment]
Nope. But we also run that facts jobs every few hours as a periodic job.

**Comment by chschilling** [comment]
ok, strange, need to dig deeper than

**Comment by berendt** [comment]
The error no longer occurs in the stable-next deployment check. Seems to have been solved by the Ansible upgrades in the meantime.
