### ISSUE TITLE
Setup search.osism.tech

### ISSUE THREAD

**Issue by berendt** [osism/issues#39]
https://github.com/hound-search/hound

All OSISM repositories should be searchable.  Please deploy directly on a Kubernetes cluster via Okeanos.

**Comment by tibeer** [comment]
More or less implemented. Yet, hound fails during startup: 
```
fatal: unable to access 'https://github.com/osism/container-image-openstackclient.git/': Could not resolve host: github.com
```

**Comment by tibeer** [comment]
Issue of setting up hound in Kubernets: Config as well as Data are stored in the same directory. It cannot be seperated. There is an issue in the hound repository (294), but it was not fixed in any kind. Maybe have a look here: https://github.com/bykvaadm/hound-helm-chart/

**Comment by tibeer** [comment]
Maybe also built our own container ...
