### ISSUE TITLE
Remove check-ansible-syntax GitHub action

### ISSUE THREAD

**Issue by berendt** [osism/issues#395]
* Use Zuul job ansible-lint:  https://github.com/osism/zuul-jobs/blob/main/.zuul.yaml#L2-L4
* Remove Github Action job definitions

* ansible-collection-services
* ansible-collection-commons
* ansible-playbooks
* ansible-defaults
* ansible-collection-validations
* ansible-playbooks-manager

**Comment by ra-beer** [comment]
Do we really need ansible syntax check at ansible-defaults? There are only vars not playbooks or roles or tasks

**Comment by ra-beer** [comment]
Done
