### ISSUE TITLE
ironic issues

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#401]
we had multiple issues during ironic introspection.

1. renaming of template file in kolla-ansible during update ignores existing overlay files
- file “ironic-ipxe-httpd.conf.j2” was renamed to “ironic-http-httpd.conf.j2”
- commit can be seen here: https://github.com/openstack/kolla-ansible/commits/master/ansible/roles/ironic/templates/ironic-http-httpd.conf.j2
- since the project had an overlay file for this template, the overlay file was ignored after the update of kolla-ansible
- changelogs in osism or kolla-ansible do not mention this renaming
- how can this be prevented in the future, as we do not want updates to break existing setups

2. ironic-python-agent ignores kernel parameter
- when using the os baremetal node create command, we tried adding ‘--driver-info kernel_append_params="ipa-network-interface=ens5f0"’ to the options as well, since we wanted the agent only to use this specified interface.
- the code says "help=The interface to use when looking for an IP address. Can be supplied as ipa-network-interface kernel parameter.) at https://github.com/openstack/ironic-python-agent/blob/master/ironic_python_agent/config.py
- but the agent still tries all interfaces with DHCP, which apparently took too long with 6 interfaces and the agent quits and restarts with a timeout, without the correct interface receiving an IP.
- workaround was to increase the timeout in the dhcp systemd unit file
- did we use the parameter in a wrong way or why was this parameter not used?

**Comment by berendt** [comment]
I'll close here. Since no feedback has been received so far, I assume that the problems will no longer occur with the current version of Ironic. Unfortunately, we still do not have a dedicated test environment for Ironic. The SCS Lab has only been available for use since November 2023 and is currently under construction.
