### ISSUE TITLE
Logrotation for /var/log/ceph/ceph-volume.log missing

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#402]
- we had issues with ceph, which lead to increased logging
- /var/log/ceph/ceph-volume.log grew in under 2 days to a size that lead to /var being 100% full, which in turn lead to alot of other issues
- why is there no logrotate for these logfiles?
- how is logrotate in osism handled in general?

**Comment by berendt** [comment]
Logrotate is currently only implemented by kolla-ansible. So only within /var/log/kolla. Not by ceph-ansible or other services.

We can take this as a feature request to add Logrotate as a role to manage /var/log completely with Logrorate.

**Comment by berendt** [comment]
Looks like this only affects the Ceph logs. We use journald by default for all systems service with the following default parameters: https://github.com/osism/ansible-collection-services/blob/main/roles/journald/defaults/main.yml#L5-L11

**Comment by berendt** [comment]
As a workaround place the following content in the ``/etc/logrotate.d/ceph`` file and add a cron job with ```30 * * * * /usr/sbin/logrotate /etc/logrotate.d/ceph >/dev/null 2>&1```. We'll add this to the Ceph playbooks.

```
/var/log/ceph/*.log {
    rotate 7
    daily
    compress
    sharedscripts
    postrotate
        killall -q -1 ceph-mon ceph-mgr ceph-mds ceph-osd ceph-fuse radosgw rbd-mirror || pkill -1 -x "ceph-mon|ceph-mgr|ceph-mds|ceph-osd|ceph-fuse|radosgw|rbd-mirror" || true
    endscript
    missingok
    notifempty
    su root root
}

/var/log/tcmu-runner/*.log {
    rotate 7
    daily
    compress
    sharedscripts
    postrotate
        killall -q -1 tcmu-runner || pkill -1 -x "tcmu-runner" || true
    endscript
    missingok
    notifempty
    su root root
}
```

**Comment by berendt** [comment]
Fixed in latest ceph-ansible & osism builds. You can now use ``osism apply ceph-infra`` to deploy the missing logrotate configuration file. This role is now also included in the other playbooks (ceph-mons, ceph-osds, ..) This way the logrotate configuration should be available everywhere in the future.
