### ISSUE TITLE
nova-compute fails to auth to libvirtd when `hostname` != `hostname -f`

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#404]
- we ran into exactly the same bug that is mentioned here: https://bugs.launchpad.net/kolla-ansible/+bug/1989791
- the workaround worked for us as well
- could you please check if/when this bug can be fixed?

**Comment by berendt** [comment]
This is a known problem which we had also documented. We can take this with us for the next sprint and fix it. Then it's done.

**Comment by berendt** [comment]
Another workaround we use in the testbed (in ``environments/kolla/configuration.yml``):

```
libvirt_enable_sasl: "no"
```

**Comment by berendt** [comment]
I think nothing more to do here.
