### ISSUE TITLE
Implement ansible galaxy proxy / mirror

### ISSUE THREAD

**Issue by fkr** [osism/issues#408]
Based on [http://github.com/osism/python-ansible-wormhole](https://github.com/osism/python-ansible-wormhole) a galaxy proxy / mirror will be implemented in order to nicely support air gapped installs.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by tibeer** [comment]
Forgot to close.
