### ISSUE TITLE
Add a playbook to decommission a storage node

### ISSUE THREAD

**Issue by berendt** [osism/issues#413]

**Comment by matfechner** [comment]
in ceph ansible exists shrink osd the command,  osism-ceph shrink-osd  -l  testbed-node-0.testbed.osism.xyz -e osd_to_kill=x,y . In productive environments should run before  ceph osd crush reweight osd.x, to decrease the replication procedure's

**Comment by berendt** [comment]
That‘s done: https://osism.tech/docs/guides/operations-guide/ceph#remove-a-single-osd-node
