### ISSUE TITLE
missing osismclient container while upgrading

### ISSUE THREAD

**Issue by maliblatt** [osism/issues#418]
When trying to update our manager to 4.2.0 we are encountering the following error when trying to run osism-update-manager:

`TASK [osism.services.manager : Copy osismclient bash completion script] **************************************************************************************************
fatal: [manager1-dev2-az0.pco.ps-intern.de]: FAILED! => {"changed": false, "cmd": "INTERACTIVE=false osism complete >> /etc/bash_completion.d/osism", "delta": "0:00:00.044015", "end": "2023-01-30 14:55:30.312511", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2023-01-30 14:55:30.268496", "stderr": "Error: No such container: osismclient", "stderr_lines": ["Error: No such container: osismclient"], "stdout": "", "stdout_lines": []}`

On our manager we do not have an osismclient container. Is it possible to modify the update script that this container will be deployed in the update process? Or what is the right way to get the osismclient container to our old manager?

**Comment by berendt** [comment]
Can you please share the output of docker-compose --project-directory /opt/manager ps.

**Comment by maliblatt** [comment]
sure:

`dragon@manager1-dev2-az0:~$ docker-compose --project-directory /opt/manager ps
NAME                             COMMAND                  SERVICE                STATUS              PORTS
ceph-ansible                     "/entrypoint.sh slee…"   ceph-ansible           running             
kolla-ansible                    "/entrypoint.sh slee…"   kolla-ansible          running             
manager-ara-server-1             "sh -c '/wait && /ru…"   ara-server             running (healthy)   10.70.194.67:8120->8000/tcp
manager-inventory_reconciler-1   "/sbin/tini -- /entr…"   inventory_reconciler   running (healthy)   
manager-mariadb-1                "docker-entrypoint.s…"   mariadb                running (healthy)   3306/tcp
manager-redis-1                  "docker-entrypoint.s…"   redis                  running (healthy)   6379/tcp
osism-ansible                    "/entrypoint.sh slee…"   osism-ansible          running  `

**Comment by berendt** [comment]
Strange that it's not there. As a workaround, I'll add an ignore_errors.

**Comment by maliblatt** [comment]
thanks for the info, but is it somehow possible to get this osismclient container up and running on our managers? That would be the most preferred solution for us because then we can also use the new osism commands.

**Comment by berendt** [comment]
I have written to you on Matrix about this. Let's look at why that didn't work separately from the issue here.
