### ISSUE TITLE
Allow encryption of Ceph key files and SSL private keys

### ISSUE THREAD

**Issue by berendt** [osism/issues#42]

**Comment by berendt** [comment]
Check this in the testbed.

**Comment by osfrickler** [comment]
The SSL private keys that are provided in the testbed are encrypted via ansible-vault, this should be possible for other deployments, too.

The Ceph client keys are store unencrypted on the manager currently in the testbed setup. A generic deployment could provide them encrypted via ansible-vault though if they have a preconfigured Ceph setup. I don't think changing the testbed setup is worthwhile, as the keys need to be unencrypted on all other nodes anyway. Open to discussion though.

**Comment by osfrickler** [comment]
See also https://review.opendev.org/c/openstack/kolla-ansible/+/824566 for a related proposal that would allow Ceph client keys to be stored in Hashicorp Vault or similar.

**Comment by berendt** [comment]
Comes upstream only in the next release. Must therefore be postponed.
