### ISSUE TITLE
change settings for docker daemon on hosts

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#422]
due to the customer landscape, we had to use an insecure registries entry in /etc/docker/daemon.json on some hosts:
"insecure-registries": ["IP:PORT"],

is it possible to have this setting in the environments/kolla/configuration.yml?
If yes, could you please tell me the syntax of the setting and with which osism/kolla command I can push this setting to the hosts.

**Comment by berendt** [comment]
You can overwrite the used docker registry for Kolla in ``environments/kolla/configuration.yml`` via ``docker_registry_kolla`` and ``docker_namespace``. To you the images from the new container registry you have to refresh all running services via the ``refresh-containers`` action (``osism-kolla refresh-containers X`` or ``osism apply -a refresh-containers X``).

Here is an example:

https://github.com/osism/testbed/blob/main/environments/kolla/configuration.yml#L2-L6

**Comment by berendt** [comment]
Or do you mean the entry in ``/etc/docker/daemon.json`` itself? Docker is managed via the ``osism.services.docker`` role.

Insecure registries can be set via the ``docker_insecure_registries`` parameter (https://github.com/osism/ansible-collection-services/blob/main/roles/docker/defaults/main.yml#L98). Deployment via ``osism apply docker`` or ``osism-generic docker``.

**Comment by berendt** [comment]
I'm just clearing the issues and I think that's done. If it doesn't do what you thought it would, please reopen it.
