### ISSUE TITLE
deployment step in documentation missing

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#423]
due to customer requirements, we have to deploy the monitoring software (prometheus + alertmanager +grafana) on a second manager-node. we added the following to the inventory:

[monitoring]
mgr2
[grafana]
mgr2

following the documentation https://docs.osism.tech/deployment/services/monitoring.html the command “osism-kolla deploy prometheus” failed due to missing requirement kolla-toolbox on the target-node.

TASK [prometheus : Creating prometheus database user and setting permissions] -> fatal: [mgr2]: FAILED! => {"changed": false, "msg": "kolla_toolbox container is not running."}

this could be fixed with “osism-kolla deploy common -l mgr2” since this role deploys kolla-toolbox. Is this something that should be included in the manager-deployment or monitoring documentation page?

**Comment by berendt** [comment]
The ``common`` role has always to be deployed on all nodes. It could make sense to add the ``common`` role in the generic bootstrap/maintenance playbooks for nodes.
