### ISSUE TITLE
not possible to configure external url for prometheus dashboard

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#424]
per default all monitoring dashboards point to os-api-int.*, but we need external access for them, e.g. for them to point to os-api.*. for grafana to point to the right prometheus url and for the prometheus alertmanager to have the correct url, I could get this with the following variables in configuration.yml:
prometheus_alertmanager_external_url: "http://os-api.site.com:9093"
grafana_prometheus_url: "http://os-api.site.com:9091"

for prometheus I could not find such a variable. as seen in the ansible code how the start parameters are build together:
./templates/prometheus-server.json.j2:    "command": "/opt/prometheus/prometheus --config.file /etc/prometheus/prometheus.yml --web.listen-address {{ api_interface_address | put_address_in_context('url') }}:{{ prometheus_port }} --web.external-url={{ internal_protocol }}://{{ kolla_internal_fqdn | put_address_in_context('url') }}:{{ prometheus_port }} --storage.tsdb.path /var/lib/prometheus{% if prometheus_cmdline_extras %} {{ prometheus_cmdline_extras }}{% endif %}",

--web.external-url always uses the kolla_internal_fqdn and can't be overwritten. i tried adding a second --web.external-url with the cmdline extras, but then prometheus won't start because of the double variable. i think a fix would be to handle the external url the same as it is already done with the alertmanager-external-url in defaults/main.yml as its own variable that can be overwritten when necessary in the configuration.yml

**Comment by berendt** [comment]
This is not intended by the logic as it is implemented in Kolla. The internal API endpoint is for internal APIs and internal services (operator level). The external API endpoint is for external APIs and external services (customer level). Prometheus is a purely internal service. Alertmanager and Grafana are the associated external services.

**Comment by berendt** [comment]
As a workaround:

You can add additional HAProxy service (internal + external) via the ``environments/kolla/vilfes/overlays/haproxy/services.d/haproxy.cfg`` configuration file.

Some like following (untested) could work:

```
listen prometheus_api_external
  mode http
  http-request del-header X-Forwarded-Proto
  option httplog
  option forwardfor
  http-request set-header X-Forwarded-Proto https if { ssl_fc }
  {{ "bind %s:%s %s"|e|format(kolla_external_vip_address, prometheus_proxy_server_port, external_tls_bind_info)|trim() }}
{% for host in groups['prometheus'] %}
  server {{ hostvars[host]['ansible_hostname'] }} {{ hostvars[host]['prometheus_address'] }}:{{ prometheus_port }} check inter 2000 rise 2 fall 5
{% endfor %}
```

**Comment by schulze-b1** [comment]
> This is not intended by the logic as it is implemented in Kolla. The internal API endpoint is for internal APIs and internal services (operator level). The external API endpoint is for external APIs and external services (customer level). Prometheus is a purely internal service. Alertmanager and Grafana are the associated external services.

due to the special network setup we have at the customer, the kolla-logic/internal/external differentiation does not really exist or is possible here. so it would be good, if the customer has at least the chance to change this if needed. i believe the following changes would be enough to accomplish this:

https://github.com/openstack/kolla-ansible/blob/master/ansible/roles/prometheus/templates/prometheus-server.json.j2
```
... --web.external-url={{ prometheus_external_url }} ...
```

https://github.com/openstack/kolla-ansible/blob/master/ansible/roles/prometheus/defaults/main.yml
```
   haproxy:
      prometheus_server:
      ...
      prometheus_server_external:
        enabled: "{{ enable_prometheus_server_external | bool }}"
        mode: "http"
        external: true
        port: "{{ prometheus_port }}"
        active_passive: "{{ prometheus_active_passive | bool }}"

prometheus_external_url: "{{ internal_protocol }}://{{ kolla_internal_fqdn | put_address_in_context('url') }}:{{ prometheus_port }}"
```

https://github.com/openstack/kolla-ansible/blob/master/etc/kolla/globals.yml
```
#enable_prometheus_external: "no"
...
#enable_prometheus_server_external: "{{ enable_prometheus_external | bool }}"
```

https://github.com/openstack/kolla-ansible/blob/master/ansible/group_vars/all.yml
```
enable_prometheus_external: "no"
...
enable_prometheus_server_external: "{{ enable_prometheus_external | bool }}"
```

would this be a valid solution?

**Comment by berendt** [comment]
Yes. But this way you have to touch kolla-ansible itself. You should avoid this.

I think my proposed workaround is easier. Have a look at https://github.com/osism/testbed/blob/main/environments/kolla/files/overlays/haproxy/services.d/haproxy.cfg as a sample for Swift API endpoints, forwarding external traffic to the internal Ceph RGW services. Should be possible this way for the Prometheus API as well.

This way you can keep the customisation in the configuration repository and you do not have to touch the kolla-ansible sources.
