### ISSUE TITLE
Ubuntu 22.04 OVS/Neutron Bridge Issue

### ISSUE THREAD

**Issue by flyersa** [osism/issues#428]
Hello,

we noticed that on new installations based on Ubuntu 22.04 there is no working traffic on provider and flat networks unless bridge sysctl settings are set to ignore iptables. 

- Hosts are installed with MAAS with default 22.04 image without any modifications.
- setting firewall_driver = openvswitch in the openvswitch_agent.ini solves the problem.

We noticed this on 2 seperate new 22.04 installations already without any custom changes to the minimal 22.04 installation. On 20.04 however the setting is default to 1 as well and then everything works for some reason.

**Comment by berendt** [comment]
Please check for this task in your logs of the compute node deployment: https://github.com/openstack/kolla-ansible/blob/master/ansible/roles/nova-cell/tasks/config-host.yml#L11-L24

**Comment by flyersa** [comment]
That will set it to 1 as it should. You want the logs for it on deployment? If its 1 it will not pass any traffic for some reason, thats the main issue. We worked around it setting it to 0 and doing SGs in OVS instead of iptables

**Comment by flyersa** [comment]
For myself we kept it with that setting in openvswitch_agent.ini as you mentioned and adjusted the sysctl settings. It is required on all network nodes. But it is stil a quickfix

**Comment by Nils98Ar** [comment]
We‘ve tested it locally via `/etc/kolla/neutron-openvswitch-agent/openvswitch_agent.ini` on the „broken“ Ubuntu 22.04 compute node and it seemed to work.

The instances were reachable again. Assumed default is drop this should mean that the existing „allow rules“ were recreated if I‘m not missing something. Newly created security groups (deny rules) were working as well.

**Comment by flyersa** [comment]
thanks for you feedback. stil something that needs to be checked imho. Or we deprecate iptables in osism @berendt

**Comment by berendt** [comment]
I'll take this to the SCS Call on Wednesday and then give an update here on how we proceed.

**Comment by Nils98Ar** [comment]
Thank you! We will wait with further upgrades until we know more.

For now we have only tested switching the firewall_driver on an empty compute node and then migrated instances to it.

According to this there might be more steps necessary on the network nodes. https://docs.openstack.org/neutron/latest/contributor/internals/openvswitch_firewall.html#upgrade-path-from-iptables-hybrid-driver

**Comment by berendt** [comment]
As discussed in SCS call: We'll document to use OVS by default. Will be documented.

**Comment by Nils98Ar** [comment]
@berendt Please also document the path from iptables to ovs especially on network nodes.

It's no problem on empty compute nodes (instances can be migrated back after the switch) but I am not sure about in-use network nodes. See https://docs.openstack.org/neutron/latest/contributor/internals/openvswitch_firewall.html#upgrade-path-from-iptables-hybrid-driver.

**Comment by Nils98Ar** [comment]
@matfechner Or do all  [approaches](https://docs.openstack.org/neutron/latest/contributor/internals/openvswitch_firewall.html#upgrade-path-from-iptables-hybrid-driver) only apply to compute nodes?

[There pictures](https://docs.openstack.org/neutron/pike/admin/deploy-ovs-selfservice.html#architecture) imply that. The terms `qvo` and `qbr` that are mentioned in the approaches can only be found under _Compute Nodes_ and  the term `firewall` too...

Maybe there is no need for further steps on the network nodes apart from configuration in `environments/kolla/files/overlays/neutron/openvswitch_agent.ini`?

**Comment by matfechner** [comment]
Hi @Nils98Ar  qvo is the openvswitch side, the qbr is necessary to offers the kernel a route for filtering qvo (openvswitch) and qvb (instance tap device), openvswitch is not able to attach tap devices if iptables applied. So i guess Network nodes qdhcp, qr-* and qg-* normaly not need the qvo part. the prefer solution should the openvswitch firewall

**Comment by Nils98Ar** [comment]
@matfechner That means there should be no need to do anything special for the network nodes apart from the `environments/kolla/files/overlays/neutron/openvswitch_agent.ini` config?

**Comment by matfechner** [comment]
Hi @Nils98Ar  from my estimation is no special things to do for the networks nodes

**Comment by Nils98Ar** [comment]
@matfechner Thank you, that fits with my findings :)

**Comment by flyersa** [comment]
I just noticed after upgrading to Zed that also now existing 20.04 installations are affected by this. Network wont work if not setting sysctl net.bridge.bridge-nf-call-iptables=0 and firewall driver to openvswitch. This is a major issue on upgrades from yoga to zed on existing installations that utilize openvswitch

**Comment by Nils98Ar** [comment]
We‘ve experienced these issues with yoga on 22.04.

Maybe zed is affected because the images are based on Ubuntu 22.04?

**Comment by flyersa** [comment]
reconfiguring nova also seems to change that settings back to 1  which results obviously then in network connectivity loss for all machines using port security until it is switched back

**Comment by berendt** [comment]
We could add a when to the sysctl task in kolla-ansible to be able to overwrite it with a specific value.

**Comment by berendt** [comment]
This is already possible. Can you set ``set_sysctl`` to False on the compute nodes?

```
- name: Enable bridge-nf-call sysctl variables
  become: true
  sysctl:
    name: "{{ item }}"
    state: present
    value: "1"
    sysctl_set: true
    sysctl_file: "{{ kolla_sysctl_conf_path }}"
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
  when:
    - set_sysctl | bool
    - inventory_hostname in groups[nova_cell_compute_group]
```

**Comment by berendt** [comment]
@berendt Mention this in the upgrade nodes of the release notes.

**Comment by Nils98Ar** [comment]
@berendt  @flyersa Do you have any idea why our config works with `ovs firewall_driver` enabled and `net.bridge.bridge-nf-call-iptables=1`? Maybe then iptables is active but not used?

**Comment by flyersa** [comment]
good question. I see mixed behavior between different installations. Sometimes it works (for a while), other times it will just stop. I didnt bother investigate so far as fix is available. Guess that needs some deeper digging. Will try to replicate this in our lab

**Comment by flyersa** [comment]
@berendt set_sysctl: false seems to work flawless . Thank you for pointing this out

**Comment by Nils98Ar** [comment]
We‘ve configured the firewall_driver for neutron-openvswitch-agent. What about the neutron-l3-agent that also seems to use iptables for NAT? https://docs.openstack.org/neutron/latest/contributor/internals/layer3.html#finding-the-router-in-ip-ipconfig

**Comment by Nils98Ar** [comment]
> We‘ve configured the firewall_driver for neutron-openvswitch-agent. What about the neutron-l3-agent that also seems to use iptables for NAT? https://docs.openstack.org/neutron/latest/contributor/internals/layer3.html#finding-the-router-in-ip-ipconfig

@berendt @flyersa @matfechner Do you think the neutron-l3-agent needs attention as well?

**Comment by berendt** [comment]
I think it is enough to do this in the Open vSwitch Agent.

**Comment by flyersa** [comment]
We didnt notice any issues with routers etc. so the agent should be the only thing

**Comment by Nils98Ar** [comment]
We've upgraded the first network node to 22.04 and now we have problems with floating IPs.

Ping between floating IP instance and tenant net IP instance (non floating ip) is not working in both directions.
In the one direction we only see echo replys on the network node and in the other only requests (tcpdump). Seems to be related to the floating IP NAT.

If we restart the neutron-l3-agent on the networks node approx. 20 pings are successful and then it isn't working again.

From outside both instances are pingable.

The good news is that we don't use floating IPs for production workloads yet :) But still for customer dev systems...

**Comment by Nils98Ar** [comment]
@flyersa Do you use floating IPs and could you check the behaviour in your environments?

@berendt @matfechner Any ideas?

**Comment by flyersa** [comment]
yes we use floating ips, i dont see any issue with them

**Comment by Nils98Ar** [comment]
Pings between floating IP instance and tenant network IP (non-floating) instance are working?

**Comment by flyersa** [comment]
> @flyersa Pings between floating IP instance and tenant network IP (non-floating) instance are working?

yep. Not with you or why do you ask?

**Comment by Nils98Ar** [comment]
Yes 

> We've upgraded the first network node to 22.04 and now we have problems with floating IPs.
> 
> Ping between floating IP instance and tenant net IP instance (non floating ip) is not working in both directions. In the one direction we only see echo replys on the network node and in the other only requests (tcpdump). Seems to be related to the floating IP NAT.
> 
> If we restart the neutron-l3-agent on the networks node approx. 20 pings are successful and then it isn't working again.
> 
> From outside both instances are pingable.
> 
> The good news is that we don't use floating IPs for production workloads yet :) But still for customer dev systems...

@flyersa Yes this is the behavior… for now I’ve stopped the faulty 22.04 network node.
We will continue debugging tomorrow.

**Comment by flyersa** [comment]
@Nils98Ar i just tested this again on a full 22.04 installation with ovs and net.bridge.bridge-nf-call-iptables=0  and i can reach the internal net of the instance with a fip assigned and vice versa.

**Comment by Nils98Ar** [comment]
Okay thank you for checking this!

If you have any idea or hint what could cause that we only see „half of the icmp communication“ on the network nodes via tcpdump let me know.

**Comment by Nils98Ar** [comment]
We‘ve applied it in the meantime but this didn‘t help.

Currently it seems that icmp traffic gos from the compute node via vxlan to network node 2 but the floating ips are on the router on network node 1.

**Comment by Nils98Ar** [comment]
Multiple Restarts of neutron/ovs containers on both firewall nodes didn‘t help.

In the end stopping, waiting and starting l3_agent on network node 1 seemed to help. No idea why.

**Comment by artificial-intelligence** [comment]
at first it didn't sound related, because it's a problem in DVR setups, but you saying it works if you stop, wait and start the l3 agent, this reminds me of this bug report:

https://bugs.launchpad.net/neutron/+bug/2004041

Can you check if this patch fixes your issue? https://review.opendev.org/c/openstack/neutron/+/872265

**Comment by Nils98Ar** [comment]
Currently we cannot reproduce the issue. We tried multiple node restarts, container restarts as well as container stops and starts on both network nodes. The keepalived does it‘s job.

The only odd thing is that the keepalived (sometimes) does a failover/failback if a network node comes back although preemption seems to be disabled.

**Comment by artificial-intelligence** [comment]
possibly related bug report:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1008684

**Comment by berendt** [comment]
Stale. Please re-open if required.
