### ISSUE TITLE
Check if we have to replace Grafana with something else

### ISSUE THREAD

**Issue by berendt** [osism/issues#434]
Plutono is a fork of Grafana 7.5.17 under the Apache 2.0 License. It is currently limited to maintenance and security updates.

* https://grafana.com/licensing/
* https://github.com/credativ/plutono

**Comment by fkr** [comment]
Since Grafana is AGPLv3 I wonder why we should replace it?

**Comment by berendt** [comment]
I haven't checked it in detail yet. There was only from another project efforts in this direction and I think we should check and document it in the context of SCS.

**Comment by berendt** [comment]
@matfechner Please briefly enter the status from SIG Monitoring here. Then we can close this.

**Comment by fkr** [comment]
tl;dr from the SIG monitoring is, that no switch is needed since Grafana is AGPLv3 and this is fine for SCS.
