### ISSUE TITLE
change settings for docker daemon on hosts - reopening

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#441]
I'm just clearing the issues and I think that's done. If it doesn't do what you thought it would, please reopen it.

_Originally posted by @berendt in https://github.com/osism/issues/issues/422#issuecomment-1419667702_
       
if i add docker_insecure_registries: ['IP:PORT'] to the environments/configuration.yml, it works when rolling out with osism-generic docker. but it doesn't work if i only want this variable set for a single host, e.g. adding it to inventory/host_vars/hostX.yml will not work. could you please check why this is the case? re-opening this in a new issue, since i couldn't re-open the old issue.

**Comment by berendt** [comment]
Run reconciler sync after adjusting from the host variable?

**Comment by schulze-b1** [comment]
yes, seems i forgot the reconciler. thanks. closing the issue.

**Comment by berendt** [comment]
I'll add something so that it runs automatically when something changes in the config repository. It's a bit annoying to have to do this manually.

**Comment by berendt** [comment]
But in general, if something doesn't fit with the variables, it's either the reconciler or too old facts. In most cases, it helps to restart the reconciler and synchronise the facts.
