### ISSUE TITLE
 Backport Rabbitmq Patch for heartbeat and handshake timeout

### ISSUE THREAD

**Issue by zach-b1** [osism/issues#455]
Hello,

it's possible to back port the following Patch to older OpenStack/kolla version?

https://review.opendev.org/c/openstack/openstack-ansible-rabbitmq_server/+/855996/2

BR
Martin

**Comment by osfrickler** [comment]
The patch you cite is for OpenStack Ansible, not for kolla.

If you want to set those options with kolla-ansible, have a look at https://review.opendev.org/c/openstack/kolla-ansible/+/865434 which introduced a `rabbitmq_extra_config` config option that would allow for it. Best first try to get that patch backported upstream, if that doesn't work out, we can discuss backporting it within OSISM.

**Comment by berendt** [comment]
@zach-b1 Added back port for Zed + Yoga kolla-ansible images. Please test with the rolling tag if it works like expected.

**Comment by zach-b1** [comment]
@berendt thanks it's worked, i will documentation this:

rabbitmq_extra_config:
  heartbeat: 640
  ssl_handshake_timeout: 20000
  handshake_timeout: 40000
