### ISSUE TITLE
fluentd not exposing port for prometheus metrics

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#457]
we have deployed the common role on all nodes and fluentd containers are running without issues and no apparent errors can be seen in the logs. but only on the control nodes prometheus is able to gather metrics from fluentd on port 24231. example from the control nodes:
# ss -tulpn | grep 24231
tcp LISTEN 0 4096 $IP:24231 0.0.0.0:* users:(("ruby",pid=2800226,fd=47))

checking for the pid:
/opt/td-agent/bin/ruby -Eascii-8bit:ascii-8bit /usr/sbin/td-agent -o /var/log/kolla/fluentd/fluentd.log --under-supervisor

on all other nodes the port is not open. we have not special configuration for fluentd in the configuration.yml's and overlay. exporters were deployed according to the docu with "osism-kolla deploy prometheus". did we miss anything during deployment or why is this not working for all nodes?

**Comment by berendt** [comment]
@matfechner Please have a look on this.

**Comment by schulze-b1** [comment]
we were able to solve the issue. due to changed customer network settings, the elasticsearch containers were not reachable behind the haproxy. fluentd gave warnings for this (only for new containers, not for the containers on the control nodes where the port was open), but it was not apparent in the logs, that this was also the cause for fluentd not opening the port for prometheus metric scraping. therefore closing this issue.
