### ISSUE TITLE
Gnocchi Container does not have /var/lib/gnocchi/tmp folder

### ISSUE THREAD

**Issue by linwalth** [osism/issues#468]
Gnocchi cannot process "file" type storage backend metric files, because it lacks the directory `/var/lib/gnocchi/tmp/`

`FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/gnocchi/tmp/gnocchib_t0az22'`

**Comment by berendt** [comment]
Do you not want to use Ceph as storage backend von Gnocchi?

**Comment by linwalth** [comment]
currently, we do not wish to use ceph. our reasoning is that gnocchi uses a myriad of small objects to store, which does not synergize with ceph too well.

**Comment by berendt** [comment]
@linwalth In which container image is this required?
