### ISSUE TITLE
Container miss "python_path" variable horzion (Version Zed)

### ISSUE THREAD

**Issue by zach-b1** [osism/issues#469]
Hi 

in the Ansible-Kolla Version, "Zed" found out that the Horizon Container unhealthy is with following messages;

Target WSGI script not found or unable to stat: /var/lib/kolla/venv/lib/python3.8

in the config is "python3.8" defined :
/etc/kolla/horizon# grep python3 -R
horizon.conf:    WSGIScriptAlias / /var/lib/kolla/venv/lib/python3.8/site-packages/openstack_dashboard/wsgi.py
horizon.conf:    Alias /static /var/lib/kolla/venv/lib/python3.8/site-packages/static

but in the container is:
(horizon)[]# ls /var/lib/kolla/venv/lib/ 
python3.10

**Comment by berendt** [comment]
I'm adding a backport to fix this on Ubuntu 20.04. Please note that we only support Zed on Ubuntu 22.04.

**Comment by zach-b1** [comment]
@berendt jepp I deploy zed under Ubuntu 20.04

**Comment by garloff** [comment]
> Please note that we only support Zed on Ubuntu 22.04.

As SCS R4 / OSISM v5.x uses OpenStack Zed, we need to always upgrade to 22.04?
(Or did you want to express the opposite: Yoga and earlier are not supported on 22.04?)

**Comment by berendt** [comment]
We have simply fixed the Horizon container. Now works on 22.04 and 20.04.
