### ISSUE TITLE
hostnames instead of ip addresses as prometheus targets

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#473]
all targets in prometheus.yml are automatically populated with IP:Port and therefore are shown like this in prometheus gui + grafana. in this customer environment identifying a host with IP is not feasable, which is why we would need hostnames as targets so hosts can be clearly identified.

how can this be implemented? i couldn't find anything.

**Comment by berendt** [comment]
Fixed with https://review.opendev.org/c/openstack/kolla-ansible/+/886688 in upstream. Soon available on Zed/2023.1 as well as the coming 5.3.0 release.
