### ISSUE TITLE
Outdated docs at http://docs.osism.de/upgrade/ceph.html

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#481]
Hi,

while upgrading to 5.0.0.c I experienced an outdated documentation at http://docs.osism.de/upgrade/ceph.html

I would kindly ask you to update this page to pacific or quincy.
At least this line is wrong:
osism-ceph rolling_update -e @/ansible/group_vars/all/defaults.yml

should be 

osism-ceph rolling_update -e @/ansible/group_vars/all/099-ceph.yml

**Comment by berendt** [comment]
That's done. New docs here:

https://osism.github.io/docs/guides/upgrade-guides/ceph
