### ISSUE TITLE
5.0.0.c: Mitogen unusable on Ubuntu 22.04

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#482]
Hi,

as recommended we upgraded out manager to Ubtuntu 22.04 in order to run osism-update-manager. However, Mitogen is broken as a result of that.

 time osism-generic docker -l compute4-dev2-az1.pco.ps-intern.de

PLAY [Group hosts based on configuration] ***********************************************************************************************************************************************************************************************************************************************************************************************************************
ERROR! Your Ansible version ((2, 14, 3)) is too recent. The most recent version
supported by Mitogen for Ansible is (2, 13).x. Please check the Mitogen
release notes to see if a new version is available, otherwise
subscribe to the corresponding GitHub issue to be notified when
support becomes available.

    https://mitogen.rtfd.io/en/latest/changelog.html
    https://github.com/mitogen-hq/mitogen/issues/

real	0m3.408s
user	0m0.021s
sys	0m0.020s

**Comment by berendt** [comment]
We have to deactivate Mitogen for the time being. I note it in the release notes.
