### ISSUE TITLE
Upgrade guide should contain upgrade steps for Octavia and a download link for a matching amphora image

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#484]
Hi,

the upgrade guide https://docs.osism.de/upgrade.html does not contain any steps to upgrade Octavia. There is especially the need to have a current amphora image. It would be very handy to have it already downloadable so that we don't need create an image manually.

Kind regards,
André.

**Comment by berendt** [comment]
Images are available at https://github.com/osism/openstack-octavia-amphora-image.

Will you add the missing documentation to the Octavia upgrade section?
