### ISSUE TITLE
OSISM 5.0.0 OVN version

### ISSUE THREAD

**Issue by maliblatt** [osism/issues#486]
After upgrading one of our test environments to OSISM 5.0.0c we recognized that OVN is shipped in version 22.03.0.
From https://www.ovn.org/en/releases/ I can see the latest LTS Release is v22.03.2 (2022-12-20) which ships several bug fixes.
Is there a specific reason for not shipping 22.03.2 ?

**Comment by nerdicbynature** [comment]
I'd like to add:

After syncing with StackIt we would like to have the option to use the following versions of OVN and OVS:
OVN: 22.12
OVS: 3.10

There are a lot of performance improvements that we would like to benfit from.

**Comment by berendt** [comment]
Here we are following Kolla's upstream. To change the versions now shortly before the release is something very short term.

**Comment by berendt** [comment]
@fkr Can you please take care of this.

**Comment by berendt** [comment]
OVS now @ 3.0.1 and OVN @ 22.09.0.

Also prepared everything to be able to use source builds in the future to be able to upgrade to OVS 3.1 and OVN 23.03.

**Comment by berendt** [comment]
Shortly discuss in the PB today. Then we can also go directly up to the last stable versions.

* https://github.com/osism/container-images-kolla/pull/278 (OVN 23.03)
* https://github.com/osism/container-images-kolla/pull/281 (OVS 3.1.0)

**Comment by berendt** [comment]
OVN LBaaS is definitely faster and more consistent with the new OVN. 

<img width="1594" alt="Bildschirm­foto 2023-03-20 um 09 06 40" src="https://user-images.githubusercontent.com/419091/226281067-19223282-97c2-4d95-a1a2-004df25678a0.png">

**Comment by fkr** [comment]
> @fkr Can you please take care of this.

Am not really sure, what I was supposed to do between friday afternoon and Sunday evening (when you submitted the work) ;)

When I initially saw your comment, I was not sure wether or not it is good to pull this in before R4 - but judging from your work you have decided that it makes sense.

**Comment by nerdicbynature** [comment]
BTW:
Today 12:51 @ ovn-discuss to someone using ovn 22.03 and ovs 2.17:

```
The versions you're using have an upgrade path with potentially
significant performance improvements, e.g OVS 3.1 + OVN 23.03.
Both ovsdb-server and core OVN components became much faster in
the previous year.
```

**Comment by berendt** [comment]
As discussed in the PB we will release 5.0.0 with OVS @ 3.0.1 and OVN @ 22.09.0 and will change to build from sources with 5.1.0.

Closing this as done.
