### ISSUE TITLE
5.0.0c: Existing Swift object store container can't be set to public 

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#488]
Hi,

here is another bug. An existing private container cannot set to public. If you check the container to become public you get a success message. However, containers stays private.

Kind regards,
Andre.

**Comment by berendt** [comment]
@nerdicbynature That should be fixed with 5.0.0/5.1.0 Horizon container images. Can you please check?

**Comment by berendt** [comment]
Should be done.
