### ISSUE TITLE
outdated version of cadvisor

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#489]
the prometheus_cadvisor version used in yoga release is already over 2 years old - v0.38.7 (57a2c804) -> 13.01.2021 (kolla_prometheus_cadvisor_version: "yoga"). since cadvisor is very resource hungry i would like to disable some metrics, but a lot of features/metrics have only been implemented in the last 2 years and are not included in the yoga release version.

is it possible to bump the cadvisor version so i can upgrade this single container to a newer version?

**Comment by berendt** [comment]
Can you use the Zed images for Prometheus? There we have version 0.45.

**Comment by schulze-b1** [comment]
I don't know if we can use zed images, thats why I opened the issue. If it is possible to already use zed images for the monitoring stack, then please tell me the upgrade path / what variables to change and what to do, as I couldn't find any documentation for this.

**Comment by berendt** [comment]
You can overwrite all used image tags. Have a look at https://github.com/osism/ansible-defaults/blob/main/all/002-images-kolla.yml#L375-L397 for the prometheus images.

Add the following line to ``environments/kolla/images.yml``. This way you can use a newer container image for the cadvisor service.

```
prometheus_cadvisor_tag: zed
```

**Comment by berendt** [comment]
As described please use new version of the image. Yoga images are no longer updated and version therein also no longer adjusted.
