### ISSUE TITLE
common containers not deployed to manager

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#492]
when running osism-kolla deploy common for one of our manager nodes (mgr1), only the fluentd container is deployed. kolla-toolbox and cron containers are skipped. what could be the reason for this? i do not see any errors. the ansible log just says "conditions not met".

**Comment by berendt** [comment]
The kolla-toolbox and the cron containers are not required on the manager node.

https://github.com/osism/cfg-generics/blob/main/inventory/50-kolla#L22-L27
