### ISSUE TITLE
5.1.0 release

### ISSUE THREAD

**Issue by berendt** [osism/issues#493]
Plusserver production upgrade scheduled for 11.04.

**Comment by maliblatt** [comment]
from our investigations in the last days we found a bug neutron (21.1.1.dev6) which was shipped with 5.0.0 (neutron-server:21.1.1.20230321). The neutron in the daily build zed container (21.1.1.dev12) has been fixed, so is it possible to take the newer neutron into the 5.1.0 release?
details can be found in https://github.com/osism/issues/issues/490

**Comment by berendt** [comment]
Will do. The new release will be available on Monday.

**Comment by berendt** [comment]
Done.

**Comment by garloff** [comment]
Let me just comment that I really appreciate the focus that has been put on this issue by OSISM (@berendt, @osfrickler), PlusServer (@maliblatt, @nerdicbynature) and dNation (@matofeder) and our team (@fkr) to track things down and resolve them.
With this focus, spirit and collaboration, even annoying issues that occasionally slip through upstream (like the one here) are not something we have to fear.
