### ISSUE TITLE
docker-compose error during osism-update-manager

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#494]
while executing osism-update-manager to upgrade a manager to 4.2.0, where are getting errors with the docker-compose.yml-task for redis and mariab:
unauthorized: access to the requested resource is not authorized

the reason seems to be that the images are getting pulled from quay.io/library/ where the images seem to not be public accessable:
image: "quay.io/library/mariadb:10.11.2"
image: "quay.io/library/redis:7.0.10-alpine"

i looked into the ansible code and the library-org (https://quay.io/organization/library) seems to be hardcoded:
/ansible/group_vars/all/images.yml:ara_server_mariadb_image: "{{ docker_registry }}/library/mariadb:{{ ara_server_mariadb_tag }}"
/ansible/group_vars/all/images.yml:manager_redis_image: "{{ docker_registry }}/library/redis:{{ manager_redis_tag }}"

how can we get access to these images to finish the upgrade?

**Comment by berendt** [comment]
quay.io should be index.docker.io there. Can you please share your value for docker_registry?

**Comment by schulze-b1** [comment]
we have the following in environements/kolla/configuration.yml:
docker_registry: index.docker.io
docker_registry_kolla: quay.io

and the following in the host_vars-files for the managers:
docker_registry: index.docker.io
docker_registry_docker_hub: index.docker.io
docker_registry_ansible: quay.io
docker_registry_service: quay.io
docker_registry_kolla: quay.io
docker_registry_quay_io: quay.io
docker_registry_cephclient: quay.io
ceph_docker_registry: quay.io

we also restarted the inventory-reconciler this time after doing config-changes.

nevertheless if i look at the docker-compose.yml in /opt/manager after the failed ansible-run, all images point to quay.io and none to index.docker.io.

**Comment by berendt** [comment]
The osism-update-manager script doesn't depends on the normal inventory and the inventory reconciler. It's just a bash script that only uses ``environments/configuration.yml`` and the files located in ``environments/manager``. Add the registry parameters also to ``environments/manager/``.

**Comment by schulze-b1** [comment]
we found the issue with a wrong set variable - docker_registry_service was set to quay.io and overwrites docker_registry variable. after setting this correctly, the image issue was fixed. we had multiple other issues with the osism-update-manager script, but i will open a separate issue for this.
