### ISSUE TITLE
osism-generic network not working with ubuntu 22.04

### ISSUE THREAD

**Issue by maliblatt** [osism/issues#495]
seems that here is missing a file for ubuntu 22.04:
https://github.com/osism/ansible-collection-commons/tree/main/roles/network/vars/interfaces

TASK [osism.commons.network : Gather variables for each operating system] ******************************************************************
fatal: [node1]: FAILED! => {"msg": "No file was found when using first_found."}

**Comment by osfrickler** [comment]
Can you try to use `network_type: netplan`? That's what we are using for our 22.04 nodes, maybe we can switch the default for that?

**Comment by Nils98Ar** [comment]
We consider switching to netplan too. Is there any „migration work“ needed apart from changing `network_type` config to `netplan` and re-deploy network?

**Comment by berendt** [comment]
On Ubuntu 22.04 you have to use Netplan instead of the old interfaces file. You have to set network_type to netplan and you have to migrate the old network configuration in host_vars to the Netplan. Please have a look at https://github.com/osism/testbed/blob/main/inventory/group_vars/testbed-managers.yml#L35-L39 and https://github.com/osism/ansible-collection-commons/blob/main/roles/network/templates/netplan/01-osism.yaml.j2.

Netplan documentation itself is available at https://netplan.readthedocs.io/en/stable/.

@osfrickler We can now switch from old interfaces files to Netplan by default.

**Comment by Nils98Ar** [comment]
Could anybody provide an example snippet how the `up:` section can be translated to netplan?https://docs.osism.tech/deployment/services/loadbalancer.html#add-health-manager-interface-configuration-to-config-repository

**Comment by berendt** [comment]
Should no longer be necessary with Zed. When using tenant networks for Octavia, everything is created there as well.

https://github.com/openstack/kolla-ansible/blob/master/ansible/roles/octavia/tasks/hm-interface.yml#L55-L84

Have a look at https://github.com/osism/testbed/blob/main/inventory/group_vars/testbed-managers.yml#L40-L44 for a sample how to do the ``up`` thing from interfaces.

**Comment by Nils98Ar** [comment]
Thank you!

Ok so the the whole hm interface in the host_vars should be unnecessary.

It looks like most of the OSISM octavia documentation has been automated in kolla-ansible or made default in osism/ansible-defaults and osism/cfg-generics in the meantime ;)

I will try to delete the redundant config.

**Comment by maliblatt** [comment]
thanks for the explanation. we have tested netplan in a fresh environment and it works as expected.
Our old environments will be migrated to netplan later, so this issue can be closed.

**Comment by Nils98Ar** [comment]
@berendt It should be mentioned in the release notes that migration to netplan is needed when upgrading to Ubuntu 22.04.

**Comment by berendt** [comment]
Let me mention it.

**Comment by fkr** [comment]
> Let me mention it.

Imho this is a good service to the users. Thanks @berendt.
