### ISSUE TITLE
ansible-lint: Replaced outdated tag '403' with 'package-latest'

### ISSUE THREAD

**Issue by berendt** [osism/issues#496]
```
WARNING  Replaced outdated tag '403' with 'package-latest', replace it to avoid future regressions
WARNING  Listing 1 violation(s) that are fatal
```

At least it breaks ansible-collection-services at the moment. Should be changed everywhere.

**Comment by ra-beer** [comment]
The problem isn't because of the outdated tag it is this one: 
`     1 syntax-check[specific] min     core, unskippable `

I will have a look at it.

**Comment by ra-beer** [comment]
But we can let this issue open and fix the outdated tags general.

**Comment by ra-beer** [comment]
Done
