### ISSUE TITLE
auditd config seems not to be ready for Ubuntu 22.04

### ISSUE THREAD

**Issue by costelter** [osism/issues#497]
After running the bootstrap on a newly installed 22.04 env and after upgrading from 20.04 (R3 -> R4) the config for the auditd is failing with multiple errors.

Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: Unknown user: chrony
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 25 of /etc/audit/audit.rules
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: Unknown user: chrony
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 26 of /etc/audit/audit.rules
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: Unknown user: ntp
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 55 of /etc/audit/audit.rules
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: Unknown user: ntp
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 56 of /etc/audit/audit.rules
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: Error sending add rule data request (No such file or directory)
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 100 of /etc/audit/audit.rules
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: Error sending add rule data request (No such file or directory)
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 101 of /etc/audit/audit.rules
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: Error sending add rule data request (No such file or directory)
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 103 of /etc/audit/audit.rules
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: Error sending add rule data request (No such file or directory)
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 292 of /etc/audit/audit.rules
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: Error sending add rule data request (No such file or directory)
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 293 of /etc/audit/audit.rules
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: Error sending add rule data request (No such file or directory)
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 325 of /etc/audit/audit.rules
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: Error sending add rule data request (No such file or directory)
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 326 of /etc/audit/audit.rules
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: Error sending add rule data request (No such file or directory)
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 347 of /etc/audit/audit.rules
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: parameter passed without an option given
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 348 of /etc/audit/audit.rules
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: parameter passed without an option given
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 349 of /etc/audit/audit.rules
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: parameter passed without an option given
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 350 of /etc/audit/audit.rules
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: parameter passed without an option given
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 351 of /etc/audit/audit.rules
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: parameter passed without an option given
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 352 of /etc/audit/audit.rules
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: Error sending add rule data request (No such file or directory)
Apr 17 08:43:08 compute2-prod3-az1 augenrules[51185]: There was an error in line 360 of /etc/audit/audit.rules

I assume there are some adjustments necessary. We didn't took a deeper look yet. We just noticed it while upgrading and while rolling out a fresh environment (directly starting with Ubuntu 22.04).

**Comment by costelter** [comment]
May be this a change of behavior of the auditd coming with Ubuntu 22.04.
Those erroneous lines are all dealing with non existant directories like /etc/sysconfig/* or  /Library/Application Support/*.
Non existant files (binaries) cause no errors.

**Comment by costelter** [comment]
oh, and non-existant users are also causing an error (see chrony + ntp)

**Comment by artificial-intelligence** [comment]
first findings:

we seem to [sync rules](https://github.com/osism/ansible-collection-services/blob/cd83abf7a41462038dda5bde20f7209bbcdfe719/roles/auditd/templates/rules/20-neo23x0.rules.j2) for auditd from [here](https://github.com/Neo23x0/auditd).

There is a [closed bug upstream](https://github.com/Neo23x0/auditd/issues/1), which refers to the same problem of the unknown `chrony` user.

If we look at the [chrony source](https://salsa.debian.org/debian/chrony/-/blob/debian/latest/) used in ubuntu, we can indeed see, that the user is [`_chrony`](https://salsa.debian.org/debian/chrony/-/blob/b1e69cc2746990aa1423d6b39eac42de8f771fc5/debian/postinst#L19) instead of `chrony`, for whatever reason.

so we could most likely fix that by pulling [this commit](https://github.com/Neo23x0/auditd/commit/c1b6620b48d46756d51cd3fb4d754e0fb8f10f88).

a more general approach might be to automatically rebase/pull these upstream changes regularly, i.e. via the renovate bot.

still investigating the rest of the issues.

**Comment by costelter** [comment]
JFTR. auditd with 20-neo23x0.rules dated 2022/07/19 had performance impact on 3 of our control nodes of one of our environments which has currently the biggest workloads. We stripped the useless parts (as for OSX) already which caused the errors reported.

The impact appeared all of a sudden with no changes on that weekday (saturday, no changes on env or new massive workloads).

We disabled the auditd for now as it has no real benefit except bigger logfiles which nobody will ever parse (and hopefully will never have to look at).

**Comment by berendt** [comment]
It is probably best to activate the auditd only if there is a default for it and you also use the logs. I'm preparing it to be an opt-in and not an opt-out. We don't use this ourselves because of the impact on the services and because we don't get any added value from it.

**Comment by berendt** [comment]
I think this is fixed with the latest sync of the rules. Please re-open if it is still not working like expected.
