### ISSUE TITLE
GitHub: add  workflow_dispatch to all "Build docker image" workflows

### ISSUE THREAD

**Issue by berendt** [osism/issues#5]
File to change: ```.github/workflows/build-docker-image.yml```

Add ```workflow_dispatch:``` to all "Build docker image" workflows.

```
---
name: Build docker image

"on":
  workflow_dispatch:
[...]
```

**Comment by tibeer** [comment]
@berendt done. 

Affected repositories:
container-image-ara-server
container-image-ceph-ansible
container-image-ceph-daemon
container-image-cephclient
container-image-kolla-ansible
container-image-manager-runner
container-image-openstackclient
container-image-osism-ansible
container-image-patchman
container-images-kolla

Related PRs:
https://github.com/osism/container-image-ara-server/pulls/54
https://github.com/osism/container-image-ceph-ansible/pulls/121
https://github.com/osism/container-image-ceph-daemon/pulls/37
https://github.com/osism/container-image-cephclient/pulls/15
https://github.com/osism/container-image-kolla-ansible/pulls/160
https://github.com/osism/container-image-manager-runner/pulls/1
https://github.com/osism/container-image-openstackclient/pulls/36
https://github.com/osism/container-image-osism-ansible/pulls/146
https://github.com/osism/container-image-patchman/pulls/3
https://github.com/osism/container-images-kolla/pulls/59
