### ISSUE TITLE
Enable Grafana unified alerting in kolla-ansible

### ISSUE THREAD

**Issue by grawert** [osism/issues#50]
Make the configuration of Grafana unified alerting possible via kolla-ansible. The `grafana.ini` template needs to be enhanced with a configuration block for the unified alerting and the patch need to be submitted to kolla-ansible project.

**Comment by grawert** [comment]
https://review.opendev.org/c/openstack/kolla-ansible/+/815694

**Comment by berendt** [comment]
According to the review: Will be handled via custom config.
