### ISSUE TITLE
"ll" alias inside containers

### ISSUE THREAD

**Issue by linwalth** [osism/issues#501]
Many operators, myself included, are accustomed to using `ll` to display the contents of a directory.
Would it be possible to put the `ll` alias inside all containers, because at the moment it does not exist there.

**Comment by berendt** [comment]
Inside the containers?

**Comment by linwalth** [comment]
yes, inside the containers.

**Comment by berendt** [comment]
Would prefer not to build anything in the containers. It is not intended that you work with bash etc. in the filesystem of the running containers. Therefore, IMO we should not suggest that the work there is desired by introducing e.g. such aliases.

**Comment by garloff** [comment]
Being a very frequent user of `ll` myself, I still agree with @berendt: The containers are not meant to be entered with `docker exec -it CONT /bin/bash` except in unusual debugging situations. We should not optimize for those and not pretend we want to facilitate operators to go in there.

**Comment by berendt** [comment]
Should we document this? That we intentionally make it uncomfortable to work inside the container so that you just don't make a habit of it?

**Comment by linwalth** [comment]
Potentially a good idea. "Nudging" mechanism and official explanation as to why.
