### ISSUE TITLE
ara server missing on second manager

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#504]
we realized the ara server is missing on our second manager node. the warning we get when executing playbooks is:
[WARNING]: Skipping callback 'ara_default', unable to load due to: The server dependencies must be installed to record data offline or run the API server.
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

how can the ara server be deployed individually? when the manager node was deployed in the past, we followed the osism documentation but missed afterwards that there was no ara server.

**Comment by berendt** [comment]
``ara_enable: true`` set in ``environments/manager/configuration.yml`` ?

**Comment by schulze-b1** [comment]
yes. this was set to true. after upgrading OS to ubuntu 22.04 and running the run.sh manager script again, this time the ara server was deployed. not sure why it didn't work the first time. one more thing - can we define ara_server_host: "$IP" in host_vars? meaning that manager1 has as ara host IP1 and manager2 has as ara host IP2? or does it have to be a single IP defined in environments/manager/configuration.yml?

**Comment by berendt** [comment]
Never tested. But in principle this should already work if you move ara_server_host into the host_vars if you want to use two different ARA instances.

**Comment by schulze-b1** [comment]
i tested it and it worked. closing issue.
