### ISSUE TITLE
no autostart of containers after reboot

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#506]
we had issues with some containers (e.g. prometheus-server) not starting automatically after a server reboot. shouldn't they autostart? if not, how can this be configured?

**Comment by berendt** [comment]
As of Zed, Systemd units are available for this purpose. Not before. You have to check and correct them manually.

**Comment by schulze-b1** [comment]
hm, strange, because we use yoga and some containers are still starting automatically, but not all of them. anyway, if this is generally not supported in yoga, i will close this issue and see if it works after upgrading to zed.
