### ISSUE TITLE
Evaluate and migrate to Compose v2

### ISSUE THREAD

**Issue by berendt** [osism/issues#51]
https://docs.docker.com/compose/cli-command/

**Comment by tibeer** [comment]
`docker compose` is a drop-in replacement for `docker-compose`. Once V1 (`docker-compose`) is marked as deprecated (or issue 257 in docker/roadmap get's closed), a transition is possible. Though, `docker-compose` will remain as an alias for the new `docker-compose` so code-basis does not need to be updated.

**Comment by berendt** [comment]
Thans. Let’s get rid of docker-compose with #65.
