### ISSUE TITLE
osism command / osismclient sometimes hangs

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#512]
Hi,

sometime `osism apply xy` gives no output and just hangs. A manager restart did not help.
Occured with `osism apply docker -l control*` recently. `osism apply docker -l manager` worked before but is now also not working.

We used `osism-generic docker` as workaround which worked.

Are you aware of problems with hanging osismclient?

Best regards
Nils

**Comment by berendt** [comment]
This currently happens sometimes through the way we use Celery with Redis as a broker. However, the Ansible playbook itself continues to run. You can always use ARA to see the current state.

There is also ``osism task list``. This will show you all running tasks. I should add a comment that can attach to a running task.

```
$ osism task list
+-------------------+--------------------------------------+----------------------------+----------+----------------------------+-------------+
| Worker            | ID                                   | Name                       | Status   | Start time                 | Arguments   |
|-------------------+--------------------------------------+----------------------------+----------+----------------------------+-------------|
| celery@reconciler | 3ddff808-206d-4f80-97f9-107c9671da7f | osism.tasks.reconciler.run | ACTIVE   | 2023-05-12 07:21:57.216316 | []          |
+-------------------+--------------------------------------+----------------------------+----------+----------------------------+-------------+
```

**Comment by berendt** [comment]
We recently improved this by changing from Redis PubSub to Redis Streams.
