### ISSUE TITLE
outdated kolla-operations repo

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#515]
the repo https://github.com/osism/kolla-operations seems to be outdated, as nothing has changed in nearly two years. it says in the readme "Will be moved to openstack/kolla-operations later. Discussion on this during the PTG in October 2021." - has the move happened? is there a more recent version of the repo somewhere else? if not, can this repo be updated, since the rule files at https://github.com/samber/awesome-prometheus-alerts have gotten updates as well.

**Comment by berendt** [comment]
The repository is a path that is currently not actively followed. Feel free to update the rules inside the osism/kolla-operations repository when you want to use somewhere. The repository itself is still available in the container images at the moment.

**Comment by Nils98Ar** [comment]
Are there other plans regarding OSISM monitoring or is monitoring not followed at all at the moment?

**Comment by berendt** [comment]
I talked to Sven and Felix about the topic earlier this day. Sven will take over the topic and we will work out the details in the next SCS calls. I think we will then write a blog article or something to introduce the planning.

**Comment by fkr** [comment]
@Nils98Ar We can revive this in the next SIG Monitoring call on May 26th at 12:05 CEST. (see our public calendar).
@artificial-intelligence that would be a good way to go over the stuff currently present together.

**Comment by berendt** [comment]
Makes sense to push this completely to SIG Monitoring.

@artificial-intelligence Do you take SIG monitoring then also with you as a regular appointment.

**Comment by berendt** [comment]
We syned all rules & dashboard in the repository.
