### ISSUE TITLE
Haproxy does not listen to keystone port 35357 / nova upgrade pre-checks fail and errors in horizon

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#518]
Hi,

we had to add the following lines manually to the `/etc/kolla/haproxy/services.d/keystone.cfg` on each control node:
`bind <int-api IP>:35357`
`bind <ext-api IP>:35357`

After that the nova deploy worked and the errors in horizon went away.

+---------------------------------------------------------------------+
| Check: Cinder API                                                   |
| Result: Warning                                                     |
| Details: Unable to determine Cinder API version due to error: Could |
|   not find versioned identity endpoints when attempting to          |
|   authenticate. Please check that your auth_url is correct.         |
|   Unable to establish connection to http://api-                     |
|   int.xyz.cloud:35357: HTTPConnectionPool(host='api-                     |
|   int.xyz.cloud', port=35357): Max retries exceeded with            |
|   url: / (Caused by                                                 |
|   NewConnectionError('<urllib3.connection.HTTPConnection            |
|   object at 0x7f4638b02850>: Failed to establish a new              |
|   connection: [Errno 111] ECONNREFUSED'))                           |
+---------------------------------------------------------------------+

These changes will be overwritten with the next deploy. 
Do you have any idea why this deprecated port is used and how to fix this permanently?

Best regards
Nils

**Comment by Nils98Ar** [comment]
Just found this issue for ceph: https://github.com/osism/issues/issues/459
Seems to be related.

**Comment by berendt** [comment]
Can you please share the used upgrade command for Keystone.

**Comment by Nils98Ar** [comment]
@berendt Sure: `osism apply --action upgrade keystone`

**Comment by berendt** [comment]
Then port 35357 should actually still be enabled:

```
      # NOTE(yoctozepto): Admin port settings are kept only for upgrade compatibility.
      # TODO(yoctozepto): Remove after Zed.
      keystone_admin:
        enabled: "{{ enable_keystone and kolla_action == 'upgrade' }}"
        mode: "http"
        external: false
        tls_backend: "{{ keystone_enable_tls_backend }}"
        port: "{{ keystone_admin_port }}"
        listen_port: "{{ keystone_admin_listen_port }}"
```

**Comment by Nils98Ar** [comment]
I've copied the command from the history, so this is what we used... I will re-run the upgrade command and see what it does this time...

Maybe something with the `--action upgrade` is not working as aspected?

**Comment by berendt** [comment]
Try ``osism apply keystone -e kolla_action=upgrade``. Maybe the ``--action`` was broken in an older release.

**Comment by Nils98Ar** [comment]
Okay after re-running `osism apply --action upgrade keystone` and `osism apply --action upgrade loadbalancer` it seems to work.

The config it now slightly different compared to our manual added stuff but the port is still there and `nova-status upgrade check` in the nova-api container is clean.

Maybe it was due to the order in which we ran the upgrades...
