### ISSUE TITLE
Label all deployed images with OSISM release

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#523]
Would it be possible to add labels to all deployed images and maybe containers that indicate to which OSISM release it belongs to?

Currently that would be e.g. 5.1.0 for the latest zed kolla images or the manager containers, ceph containers, traefik etc.

An if you have still configured openstack_version yoga but but manager_version 5.1.0 you would have some with label 4.3.0 and some with 5.1.0.

Checking the update progress and finding not updated containers that need attention would be much easier.

**Comment by berendt** [comment]
That's not so easy in the way we consume our images. The images that we build ourselves are already provided with such a label. E.g. for kolla-ansible or all kolla images:

```
                "de.osism.version": "5.1.0",
                "org.opencontainers.image.version": "5.1.0"
```

It is not possible for images like traefik because we do not build them, we only consume them.

But I could add a command that shows all running containers with images with this label on a specific node.

In the future there will also be a validate command to check that all running containers are in the correct version.

**Comment by Nils98Ar** [comment]
Ah okay I have only seen the zed label in the containers.

Would it be an option to build the other images too and only add the label to the base image? Shouldn‘t be too hard when automated via CI and gives more control?

But I think such a validate command would also be sufficient. Currently we check the existing labels and the age of the containers via `ansible -m shell -a „docker ps | xyz“`.

**Comment by berendt** [comment]
There is already the ``osism docker ctl001 ps`` command. With the ``osism docker`` command you can execute Docker commands on a specific node. I should extend this to be able to run a command on all nodes at the same time. There is also ``osism console`` to run e.g. ansible or clush.

The base idea is to consume as many images from upstream as possible and to have a central SBOM with all available images. We want to avoid to care of a lot of self-build images.

**Comment by Nils98Ar** [comment]
However a private registry mirror with security scans (at least as pull through cache) would also be useful for security reasons. But I think this is covered by the air-gapped approach.

**Comment by Nils98Ar** [comment]
> There is already the `osism docker ctl001 ps` command. With the `osism docker` command you can execute Docker commands on a specific node. I should extend this to be able to run a command on all nodes at the same time. There is also `osism console` to run e.g. ansible or clush.

@berendt Is there something like `osism-ansible generic all -m shell -a "docker ps"` for the new `osism` client?

**Comment by berendt** [comment]
```

**Comment by berendt** [comment]
```
dragon@manager:~$ osism console --type ansible all
Welcome to the ansible console. Type help or ? to list commands.

dragon@all (1)[f:5]$ ansible.builtin.shell docker ps
```

**Comment by Nils98Ar** [comment]
Passing the command inline as argument is not possible?

Anyway very useful!
