### ISSUE TITLE
Ceph Upgrade: Pacific -> Quincy

### ISSUE THREAD

**Issue by berendt** [osism/issues#525]
Dublin (CW 22, CW 23):

- [x] https://github.com/osism/issues/issues/533 (CW 22, CW 23)
- [x] Upgrade all Ceph environments in REGIO.cloud (Pacific -> Quincy) (results in https://github.com/osism/issues/issues/534) (end of CW 23)

Edmonton (CW 24, CW 25):

- [x] https://github.com/osism/issues/issues/534 (CW 24)
- [x] Upgrade PS Test/Dev environments (end of CW 24 (proposal))
- [x] Upgrade PS gx-scs environment (start of CW 25 (proposal))
- [ ] Upgrade PS Prod environments (mid of CW 25 (proposal))

**Comment by berendt** [comment]
CI should have the following jobs:

- [ ] Deploy(Pacific -1) -> Update(Pacific) -> Upgrade(Quincy -1) -> Update(Quincy)
- [ ] Deploy(Quincy)

**Comment by frosty-geek** [comment]
@nerdicbynature is set to participate in the Ceph upgrades at REGIO.cloud on the PS side. Please make sure to actively connect with him for scheduling, noting that he won't be impacted by the German regional holidays in CW23 ;-)

Our current projection indicates that the completion of the scs1/gx-scs environments upgrade won't be possible in the imminent Edmonton sprint scheduled for CW25. Consequently, this assignment might be deferred to the F-Sprint commencing in CW26.

The schedule, however, will be influenced by the pace of testing on dev and stage platforms, a lesson we've adopted from the QA of the recent major release.

**Comment by nerdicbynature** [comment]
Is there already a scheduled date for the REGIO.cloud upgrade?

**Comment by berendt** [comment]
@nerdicbynature We are so far with the preparations that we can update a first cluster of the REGIO.cloud on Wednesday. Would it work for you after the SCS Weekly at 11 a.m.?

**Comment by nerdicbynature** [comment]
@berendt fine with me! How can I join?

**Comment by ppkuschy** [comment]
@nerdicbynature From my point (since I'll be the one doing the upgrade) I could offer Zoom or using the SCS Jitsi.

**Comment by nerdicbynature** [comment]
Both are fine, would prefer Jitsi.

**Comment by ppkuschy** [comment]
@nerdicbynature Allright, can you ping me via E-Mail (kuschy@osism.tech) , so I can send you a Jitsi link on Wednesday?

**Comment by nerdicbynature** [comment]
JTLYK: OSISM 5.2 with Ceph Quincy has been successfully rolled out in our pre-prod environments including gx-scs/scs1 last week

**Comment by berendt** [comment]
Closing this. From our point of view, it's all done. The PS Prod will come in the future
