### ISSUE TITLE
phpmyadmin PMA_HOST in docker-compose.yml empty

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#528]
Hi,

the `PMA_HOST` environment variable in `/opt/phpmyadmin/docker-compose.yml` was empty and therefore a connection to the database via phpmyadmin was not possible:

> mysqli::real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo for db failed: Temporary failure in name resolution

After copying the `kolla_internal_vip_address` line from `/opt/configuration/environments/kolla/configuration.yml` to `/opt/configuration/environments/configuration.yml` an re-deploying phpmyadmin the variable was set and phpmyadmin worked.

Should we make kolla_internal_vip_address available for all environments like this or is there a better option?

Best regards
Nils

**Comment by berendt** [comment]
Default value for ``phpmyadmin_database_host`` uses ``kolla_internal_vip_address``. ``kolla_internal_vip_address`` has to be added to ``environments/configuration.yml`` or ``phpmyadmin_database_host`` has to be added to ``environments/infrastructure/configuration.yml``.

```
all/099-infrastructure.yml:phpmyadmin_database_host: "{{ kolla_internal_vip_address }}"
```

In the cfg-cookiecutter repository we also do not have ``kolla_internal_vip_address: {{cookiecutter.ip_internal}}`` in ``environments/configuration.yml``. We probably should it there as well.

**Comment by berendt** [comment]
That‘s fixed.
