### ISSUE TITLE
fluentd container restart everytime

### ISSUE THREAD

**Issue by zach-b1** [osism/issues#531]
in the yoga contain for fluentd restart always.

in the log we found following message:

"/opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- fluent/log-ext (LoadError)
"

for this exist a bug report
https://bugs.launchpad.net/kolla/+bug/2019557
please update the container

**Comment by berendt** [comment]
We rebuild the container images for Yoga/Zed every night. Simply pull newer images with the rolling tag to get a newer version.

**Comment by zach-b1** [comment]
@berendt is pull/upgrade yesterday and today

**Comment by zach-b1** [comment]
@artificial-intelligence 
Hi 

yes, i have check my container:

```
docker run -it  ac.hub.msg.team/quay/osism/fluentd:yoga td-agent-gem list fluent

*** LOCAL GEMS ***

fluent-config-regexp-type (1.0.0)
fluent-diagtool (1.0.1)
fluent-logger (0.9.0)
fluent-plugin-calyptia-monitoring (0.1.3)
fluent-plugin-elasticsearch (5.3.0, 5.2.5)
fluent-plugin-flowcounter-simple (0.1.0)
fluent-plugin-grok-parser (2.6.2)
fluent-plugin-kafka (0.19.0)
fluent-plugin-metrics-cmetrics (0.1.2)
fluent-plugin-opensearch (1.1.0)
fluent-plugin-prometheus (2.0.3)
fluent-plugin-prometheus_pushgateway (0.1.0)
fluent-plugin-record-modifier (2.1.1)
fluent-plugin-rewrite-tag-filter (2.4.0)
fluent-plugin-s3 (1.7.2)
fluent-plugin-sd-dns (0.1.0)
fluent-plugin-systemd (1.0.5)
fluent-plugin-td (1.2.0)
fluent-plugin-utmpx (0.5.0)
fluent-plugin-webhdfs (1.5.0)
fluentd (1.16.1, 0.12.43)
```

**Comment by zach-b1** [comment]
The last tag was worked is 4.4.2.20230125

**Comment by artificial-intelligence** [comment]
should be fixed once https://review.opendev.org/c/openstack/kolla/+/884856 is merged

**Comment by artificial-intelligence** [comment]
this should be fixed now upstream. this fix should be included in the next container rebuild, so probably tomorrow.

It would be very kind if you could check if this issue is fixed for you @zach-b1 tomorrow , thanks!

**Comment by berendt** [comment]
Because we still have the problem with RabbitMQ/Erlang there are no new images available yet. They will be available later today.
