### ISSUE TITLE
Document how to deploy ceph rgw in osism

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#532]
I guess at least this is needed: https://github.com/osism/testbed/blob/f869d2c44494a96e9b4d01f3137dcf96382fcc23/scripts/deploy/300-openstack-services-basic.sh#L28.

**Comment by Nils98Ar** [comment]
`osism apply ceph-rgws` seemed to be the right one.
I will add the configuration parts!

Does this cover this stuff? https://github.com/osism/testbed/blob/0e2d77b246fe1c57d7b5b0ddff7290001a055096/environments/openstack/playbook-bootstrap-ceph-rgw.yml#L4

**Comment by berendt** [comment]
That's done.
