### ISSUE TITLE
Ceph: CI for Pacific -> Quincy

### ISSUE THREAD

**Issue by berendt** [osism/issues#533]
- [x] Test Ceph deployment (Quincy) in osism/testbed (3)
- [x] Test Ceph update (Quincy -> Quincy) in osism/testbed (3)
- [x] Test Ceph upgrade (Pacific -> Quincy) in osism/testbed (3)
- [x] Add a 2nd Ceph deployment job (Quincy) in osism/testbed (5)
- [x] Add a Ceph update job (Quincy) in osism/testbed (5)
- [x] Ensure that all available Ceph jobs in osism/testbed are working like expected (1)
- [x] Ensure that alll validate playbooks for Ceph are still usable with Quincy (1)

**Comment by berendt** [comment]
CI should have the following jobs:

- [ ] Deploy(Pacific -1, 16.2.9) -> Update(Pacific, 16.2.11) -> Upgrade(Quincy -1, 17.2.4) -> Update(Quincy, 17.2.6)
- [ ] Deploy(Quincy, 17.2.6)

**Comment by ppkuschy** [comment]
- [x] Test: Deploy testbed with Pacific and upgrade to Quincy -> Success, no issues
- [x] Test: Ceph Validator playbooks work with Quincy -> Success, no issues
Up next: Redeploy testbed with Quincy

**Comment by ppkuschy** [comment]
- [x] Test: Deploy testbed with Quincy -> Success, no issues
- [x] Test (repeat): Ceph Validator playbooks work with Quincy -> Success, no issues
Up next: Redeploy testbed with Quincy latest - X and update to Quincy latest

**Comment by ppkuschy** [comment]
- [x] Test: Deploy testbed with Quincy 17.2.4 and update to Quincy 17.2.6 -> Success, no issues
- [x] Test (repeat): Ceph Validator playbooks work with Quincy -> Success, no issues
Up next: Setup CI jobs
