### ISSUE TITLE
osism validate *-config

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#538]
`dragon@manager:~$ osism validate ceph-config`
leads to 
`run() missing 1 required positional argument: 'arguments'`

What is missing?

**Comment by Nils98Ar** [comment]
@berendt Thank you!

**Comment by Nils98Ar** [comment]
@berendt Is there already a workaround with OSISM 5.1.0?

**Comment by berendt** [comment]
Will be released with 5.2.0.

**Comment by Nils98Ar** [comment]
Okay!
