### ISSUE TITLE
osism validate ceph-osds / unable to find a keyring

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#539]
`auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory`

```
root@storage01:~# ll /etc/ceph/
total 24
drwxr-xr-x   2 64045 64045  4096 May 25 17:24 ./
drwxr-xr-x 117 root  root  12288 May 11 11:01 ../
-rw-------   1 64045 64045   131 May 25 16:06 ceph.client.crash.keyring
-rw-r--r--   1 64045 64045   364 May 25 17:24 ceph.conf
```
Ceph still works...

What should be done to place the keyring files on the storage nodes? And do you have any idea why the files aren't there?

**Comment by berendt** [comment]
Which task returns this error?

**Comment by Nils98Ar** [comment]
@berendt @ppkuschy Here is the complete task output:

> TASK [Get ceph osd tree] *******************************************************
> fatal: [storage01.xyz.ab]: FAILED! => {"changed": true, "rc": 13, "stderr": "2023-06-01T11:09:23.849+0200 7fc5e82c7700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory\n2023-06-01T11:09:23.849+0200 7fc5e82c7700 -1 AuthRegistry(0x7fc5e00604e0) no keyring found at /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,, disabling cephx\n2023-06-01T11:09:23.853+0200 7fc5e82c7700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory\n2023-06-01T11:09:23.853+0200 7fc5e82c7700 -1 AuthRegistry(0x7fc5e82c5e90) no keyring found at /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,, disabling cephx\n2023-06-01T11:09:23.853+0200 7fc5e6063700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [1]\n2023-06-01T11:09:23.853+0200 7fc5e5862700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [1]\n2023-06-01T11:09:23.853+0200 7fc5e6864700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [1]\n2023-06-01T11:09:23.853+0200 7fc5e82c7700 -1 monclient: authenticate NOTE: no keyring found; disabled cephx authentication\n[errno 13] RADOS permission denied (error connecting to the cluster)", "stderr_lines": ["2023-06-01T11:09:23.849+0200 7fc5e82c7700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory", "2023-06-01T11:09:23.849+0200 7fc5e82c7700 -1 AuthRegistry(0x7fc5e00604e0) no keyring found at /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,, disabling cephx", "2023-06-01T11:09:23.853+0200 7fc5e82c7700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory", "2023-06-01T11:09:23.853+0200 7fc5e82c7700 -1 AuthRegistry(0x7fc5e82c5e90) no keyring found at /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,, disabling cephx", "2023-06-01T11:09:23.853+0200 7fc5e6063700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [1]", "2023-06-01T11:09:23.853+0200 7fc5e5862700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [1]", "2023-06-01T11:09:23.853+0200 7fc5e6864700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [1]", "2023-06-01T11:09:23.853+0200 7fc5e82c7700 -1 monclient: authenticate NOTE: no keyring found; disabled cephx authentication", "[errno 13] RADOS permission denied (error connecting to the cluster)"], "stdout": "", "stdout_lines": []}

**Comment by ppkuschy** [comment]
@Nils98Ar 
Does the ceph-mons Validator run without errors?
(`osism validate ceph-mons`)

**Comment by Nils98Ar** [comment]
The mon and mgr  validators run without errors.

**Comment by ppkuschy** [comment]
@Nils98Ar Can you have a look at every node where a ceph-mon Container is running and confirm that there exists a `ceph.client.admin.keyring` file in `/etc/ceph`?
If thats the case then we have confirmed a bug in the OSD and RGW validators, which would mean that in your installation things are in fact correct, but my validators assume that the keyring always is rolled out, which turns out only to be the case on nodes where a ceph-mon is running.

**Comment by Nils98Ar** [comment]
That's the case on the ceph-mon nodes! The file is there.
