### ISSUE TITLE
Problems with not supported ansible version in osism-update-manager

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#543]
If ansible is not installed the script already installs it in the supported version. Why does the script not always use its own ansible version or gives an error if the installed version of ansible is not the supported one?

In the last two upgrades we had issues with this script that were due to a wrong ansible version in the end.

**Comment by berendt** [comment]
Yes, we currently assume that Ansible is not installed on the manager. I'm adding a check. Both that no Ansible is installed and that the correct Ansible version is used.
