### ISSUE TITLE
Clarification on the use of Hyper-V as hypervisor

### ISSUE THREAD

**Issue by berendt** [osism/issues#549]

**Comment by Nils98Ar** [comment]
What i've found:

- There is a OpenStack documentation for zed but it seems to be old as only Windows Server 2012 R2 is mentioned: https://docs.openstack.org/nova/zed/admin/configuration/hypervisor-hyper-v.html
- The old OpenStack documentation refers to the cloudbase website where versions for Windows Server 2022 can be found: https://cloudbase.it/openstack-hyperv-driver/
- Hyper-V support has been deprecated in kolla-ansible Victoria according to the release notes: https://docs.openstack.org/releasenotes/kolla-ansible/victoria.html

Maybe it is not supported by kolla-ansible itself but the cloudbase solution can still be used together with kolla-ansible?

**Comment by Nils98Ar** [comment]
But it seems that cloudbase will not continue maintaining this project: 

- https://lists.openstack.org/pipermail/openstack-discuss/2022-November/031044.html
- https://lists.openstack.org/pipermail/openstack-discuss/2023-March/032888.html

**Comment by berendt** [comment]
From https://lists.openstack.org/pipermail/openstack-discuss/2022-November/031044.html. Looks like a dead end to me.

```
Running Openstack on Windows has been driven by Cloudbase Solutions ever 
since Folsom (2012).

[...]

Due to a shift in business focus and the increased operational costs of 
maintaining the CI systems, we are no longer in a position to 
proactively support Openstack on Windows.
```

**Comment by fkr** [comment]
ack.
