### ISSUE TITLE
rabbitmq ssl library missing?

### ISSUE THREAD

**Issue by flyersa** [osism/issues#554]
We are running OSISM with ZED on a customer. Now trying to implement the rabbitmq ha changes we are unable to start rabbitmq (even with rolling back).

The error we get on rabbitmq containers trying to start:

=WARNING REPORT==== 15-Jun-2023::12:30:40.467622 ===
The on_load function for module crypto returned:
{error,{load_failed,"Failed to load NIF library /usr/lib/erlang/lib/crypto-5.1.3/priv/lib/crypto: 'libcrypto.so.1.1: cannot open shared object file: No such file or directory'"}}

**Comment by berendt** [comment]
Zed tag is broken at the moment.

**Comment by flyersa** [comment]
ok good to know

**Comment by flyersa** [comment]
i reversed to yoga image for now that seems to work

**Comment by berendt** [comment]
Upstream did something weird with the RabbitMQ/Erlang PPAs after the release of RabbitMQ 3.12. Working Yoga, Zed + 2023.1 tags are soon online.

**Comment by berendt** [comment]
Tags that are now online should be fixed. Testbed CI is still running at the moment.
