### ISSUE TITLE
High CPU Load on Manager

### ISSUE THREAD

**Issue by flyersa** [osism/issues#555]
We noticed on almost all of our deployments that we have a high load on the managers because there is constantly some playbook stuff running.

what is constantly running so far we found:

/usr/local/bin/python3 /usr/local/bin/celery -A osism.tasks.netbox worker -n netbox --loglevel=INFO -Q netbox

and:

/usr/local/bin/python3 /usr/local/bin/ansible-playbook -e @/opt/configuration/environments/configuration.yml -e @images.yml -e @configuration.yml --limit all:!ans /ansible/generic/facts.yml

Is it necessary to constantly have this playbooks running ? Also gunicorn constantly consuming alot of load. Maybe we can scale this down a bit?

**Comment by berendt** [comment]
Think this can be closed.
