### ISSUE TITLE
listener default broker URI dysfunctional

### ISSUE THREAD

**Issue by linwalth** [osism/issues#556]
related to https://github.com/osism/issues/issues/555

listener could not connect to the rmq which i provided because the `manager_listener_broker_uri` var in https://github.com/osism/ansible-collection-services/blob/190b0a771656991112d66cfd3d175608be2ee733/roles/manager/defaults/main.yml#L249 is just a static var and not template looping through `manager_listener_broker_hosts` like it is needed, see testbed:
https://github.com/osism/testbed/blob/900cca239cf510f1fc6dda95d80c41db58d7074e/environments/manager/configuration.yml#LL26C1-L27C1

**Comment by berendt** [comment]
You have to add the following lines to your configuration repository to be able to work with the listener.

https://github.com/osism/testbed/blob/900cca239cf510f1fc6dda95d80c41db58d7074e/environments/manager/configuration.yml#L21-L26C23

**Comment by berendt** [comment]
Cannot be related to load issues: https://github.com/osism/python-osism/blob/main/osism/services/listener.py#L184-L192

You can simply remove the listener service when you don't need it: ``enable_listener: false`` in ``environments/manager/configuration.yml``

**Comment by linwalth** [comment]
> You have to add the following lines to your configuration repository to be able to work with the listener.
> 
> https://github.com/osism/testbed/blob/900cca239cf510f1fc6dda95d80c41db58d7074e/environments/manager/configuration.yml#L21-L26C23

I had already fixed it, i was just letting you know via issue :)

**Comment by berendt** [comment]
Listener disabled by default.
