### ISSUE TITLE
Finalize Prometheus libvirt exporter ansible role

### ISSUE THREAD

**Issue by berendt** [osism/issues#56]
https://review.opendev.org/c/openstack/kolla-ansible/+/643568

**Comment by osfrickler** [comment]
Patch to create exporter image: https://review.opendev.org/c/openstack/kolla/+/642095, updated both patches with a variant that works in a local testbed deployment.

**Comment by osfrickler** [comment]
Both patches have been merged upstream, so the feature will be in Yoga. If we want to have it in earlier releases, we will likely have to backport downstream.

**Comment by berendt** [comment]
Let's discuss this tomorrow with Felix.

**Comment by berendt** [comment]
We are trying backport on stable/xena. If this does not work, a manual backport is made in OSISM.

**Comment by osfrickler** [comment]
https://review.opendev.org/c/openstack/kolla/+/831769
https://review.opendev.org/c/openstack/kolla-ansible/+/831850
