### ISSUE TITLE
Horizon UI Loadbalancer

### ISSUE THREAD

**Issue by zach-b1** [osism/issues#566]
The field for the ports when creating the pool member is missing on Chrome. Under Firefox works. 
![Bildschirmfoto vom 2023-06-23 11-39-55](https://github.com/osism/issues/assets/77446918/132e3851-4f48-40de-b4b1-7ede10213b65)

**Comment by berendt** [comment]
This is a known issue with latest Chrome. Upstream fix is in progress: https://bugs.launchpad.net/octavia/+bug/2024188
