### ISSUE TITLE
Senlin not working with Keystone Error

### ISSUE THREAD

**Issue by chrisschwa** [osism/issues#572]
After the Deployment of Senlin with `osism apply senlin` the Cluster Services via Horizon and Client are failing to retrieve any information.

Same Issue is reported to upstream for several months now our first information gathering showed.

https://bugs.launchpad.net/kolla-ansible/+bug/2015537
https://bugs.launchpad.net/senlin/+bug/1983812

`
HttpException: 500: Server Error for url: http://api-int.*******:8778/v1/clusters?global_project=False, The identity service for defaults: exists but does not have any supported versions.
`

> [Wed Jun 28 09:47:08.178571 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906] Failed to contact the endpoint at https://api.*********:8778 for discovery. Fallback to using that endpoint as the base url.
[Wed Jun 28 09:47:08.179616 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906] error invoking apiclient
[Wed Jun 28 09:47:08.179641 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906] Traceback (most recent call last):
[Wed Jun 28 09:47:08.179653 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]   File "/var/lib/kolla/venv/lib/python3.10/site-packages/horizon/utils/memoized.py", line 107, in wrapped
[Wed Jun 28 09:47:08.179664 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]     value = cache[key] = cache.pop(key)
[Wed Jun 28 09:47:08.179675 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906] KeyError: ((<weakref at 0x7fb375033330; to 'WSGIRequest' at 0x7fb3751ea950>,), ())
[Wed Jun 28 09:47:08.179686 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906] 
[Wed Jun 28 09:47:08.179696 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906] During handling of the above exception, another exception occurred:
[Wed Jun 28 09:47:08.179707 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906] 
[Wed Jun 28 09:47:08.179717 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906] Traceback (most recent call last):
[Wed Jun 28 09:47:08.179728 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]   File "/var/lib/kolla/venv/lib/python3.10/site-packages/openstack_dashboard/api/rest/utils.py", line 128, in _wrapped
[Wed Jun 28 09:47:08.179739 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]     data = function(self, request, *args, **kw)
[Wed Jun 28 09:47:08.179749 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]   File "/var/lib/kolla/venv/lib/python3.10/site-packages/senlin_dashboard/api/rest/senlin.py", line 140, in get
[Wed Jun 28 09:47:08.179760 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]     profiles, has_more_data, has_prev_data = senlin.profile_list(
[Wed Jun 28 09:47:08.179771 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]   File "/var/lib/kolla/venv/lib/python3.10/site-packages/senlin_dashboard/api/senlin.py", line 235, in profile_list
[Wed Jun 28 09:47:08.179782 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]     profiles_iter = senlinclient(request).profiles(**params)
[Wed Jun 28 09:47:08.179792 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]   File "/var/lib/kolla/venv/lib/python3.10/site-packages/horizon/utils/memoized.py", line 109, in wrapped
[Wed Jun 28 09:47:08.179803 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]     value = cache[key] = func(*args, **kwargs)
[Wed Jun 28 09:47:08.179830 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]   File "/var/lib/kolla/venv/lib/python3.10/site-packages/senlin_dashboard/api/senlin.py", line 91, in senlinclient
[Wed Jun 28 09:47:08.179843 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]     return senlin_client.Client(session=session,
[Wed Jun 28 09:47:08.179853 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]   File "/var/lib/kolla/venv/lib/python3.10/site-packages/senlinclient/v1/client.py", line 28, in __init__
[Wed Jun 28 09:47:08.179864 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]     self.service = self.conn.cluster
[Wed Jun 28 09:47:08.179874 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]   File "/var/lib/kolla/venv/lib/python3.10/site-packages/openstack/service_description.py", line 87, in __get__
[Wed Jun 28 09:47:08.179899 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]     proxy = self._make_proxy(instance)
[Wed Jun 28 09:47:08.179910 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]   File "/var/lib/kolla/venv/lib/python3.10/site-packages/openstack/service_description.py", line 266, in _make_proxy
[Wed Jun 28 09:47:08.179921 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906]     raise exceptions.NotSupported(
[Wed Jun 28 09:47:08.179932 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906] openstack.exceptions.NotSupported: The clustering service for api-int.**********:RegionOne exists but does not have any supported versions.
[Wed Jun 28 09:47:08.180408 2023] [wsgi:error] [pid 1071:tid 140409399006784] [remote 10.111.0.12:34906] Internal Server Error: /api/senlin/profiles/

**Comment by berendt** [comment]
We do not currently support or test Senlin as it is one of those OpenStack services whose future is very uncertain in our estimation. I will take this to one of the next SCS meetings, but I don't see a big potential to invest time in it to actively work on Senlin in Uptream.

**Comment by chrisschwa** [comment]
Thanks @berendt. I already thought so.
