### ISSUE TITLE
Increase tcp_mem in Octavia Image

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#573]
Moin,

the day before yesterday we had a serious Octavia loadbalancer problem. We are using this image:
```
https://minio.services.osism.tech/openstack-octavia-amphora-image/octavia-amphora-haproxy-2023.1.qcow2
```
Amongst other issues, we faced
```
Jun 27 14:05:51 amphora-aba7cf83-7f24-4ce4-bea2-9d72f9ad2a97 kernel: [6645481.403579] TCP: out of memory -- consider tuning tcp_mem
Jun 27 14:05:51 amphora-aba7cf83-7f24-4ce4-bea2-9d72f9ad2a97 kernel: [6645481.403595] TCP: out of memory -- consider tuning tcp_mem
Jun 27 14:05:51 amphora-aba7cf83-7f24-4ce4-bea2-9d72f9ad2a97 kernel: [6645481.403603] TCP: out of memory -- consider tuning tcp_mem
Jun 27 14:05:51 amphora-aba7cf83-7f24-4ce4-bea2-9d72f9ad2a97 kernel: [6645481.403660] TCP: out of memory -- consider tuning tcp_mem
Jun 27 14:05:51 amphora-aba7cf83-7f24-4ce4-bea2-9d72f9ad2a97 kernel: [6645481.403670] TCP: out of memory -- consider tuning tcp_mem
Jun 27 14:05:51 amphora-aba7cf83-7f24-4ce4-bea2-9d72f9ad2a97 kernel: [6645481.403680] TCP: out of memory -- consider tuning tcp_mem
Jun 27 14:05:51 amphora-aba7cf83-7f24-4ce4-bea2-9d72f9ad2a97 kernel: [6645481.403689] TCP: out of memory -- consider tuning tcp_mem
Jun 27 14:05:51 amphora-aba7cf83-7f24-4ce4-bea2-9d72f9ad2a97 kernel: [6645481.403735] TCP: out of memory -- consider tuning tcp_mem
Jun 27 14:05:51 amphora-aba7cf83-7f24-4ce4-bea2-9d72f9ad2a97 kernel: [6645481.403742] TCP: out of memory -- consider tuning tcp_mem
Jun 27 14:05:51 amphora-aba7cf83-7f24-4ce4-bea2-9d72f9ad2a97 kernel: [6645481.403748] TCP: out of memory -- consider tuning tcp_mem
```
Current settings as of https://opendev.org/openstack/octavia/src/branch/master/elements/haproxy-octavia/post-install.d/20-haproxy-tune-kernel

are 

```
sysctl-write-value net.core.rmem_max 67108864
sysctl-write-value net.core.wmem_max 67108864
sysctl-write-value net.ipv4.tcp_rmem "4096 87380 33554432"
sysctl-write-value net.ipv4.tcp_wmem "4096 87380 33554432"
```

This article (https://dzone.com/articles/tcp-out-of-memory-consider-tuning-tcp-mem) mentions those values:

```
net.core.rmem_max=134217728
net.core.wmem_max=134217728
net.ipv4.tcp_rmem=4096 87380 67108864
net.ipv4.tcp_wmem=4096 87380 67108864
```

Having this, I'd like to forward the Kernel's recommendation to you:
Can you consider increasing those values in the provided image?

Kind regards,
André.

**Comment by artificial-intelligence** [comment]
This needs to be seriously evaluated and I wouldn't like to copy verbatim values from an article that apparently has no understanding what e.g. `ipv4.tcp_rmem` even means, to quote them:

> Honestly, this is the first time, we are hearing about these properties.

plus, that article is from 2019, as far as I can see.

I'll check how recent the upstream config changes are and how they should be adjusted.

**Comment by artificial-intelligence** [comment]
I forgot a question: how much bandwith does your octavia loadbalancer manage when these errors occur?

**Comment by artificial-intelligence** [comment]
another question for @nerdicbynature : what where this other issues? even seemingly unrelated things can, in fact, be related.

I just don't want to introduce bufferbloat here, which would have the reverse effect and make the network slower, not faster.

also almost all tunables in this area translate directly to more used memory per connection, so it might be needed to resize the octavia amphora flavors ram amount afterwards.

**Comment by osfrickler** [comment]
I don't think tuning for such high loads makes sense for a generic image, as it would increase resource usage for most normal deployments unnecessarily. So I'd suggest that you build your own image for this special case. A patch documenting possible tuning options and the resulting performance options would of course be well received.

**Comment by Nils-Magnus** [comment]
I think tuning these values heavily depends on the balanced workloads. +1 for documenting how to tweak the image, and if further need persists, making this configurable during runtime.

**Comment by frosty-geek** [comment]
@osfrickler @artificial-intelligence could you estimate the workload (req/s + %-ssl) this image is intended for to better differentiate our requirements vs. the generic approach, please.

**Comment by osfrickler** [comment]
We don't have that data, we just built that image according to the parameters that upstream provides. The tuning data was last updated in https://review.opendev.org/c/openstack/octavia/+/809302 which mentions 10Gbps networking, so I would assume that that is the target range. Maybe better take this discussion upstream to the Octavia project?

**Comment by berendt** [comment]
I think this can be closed.
