### ISSUE TITLE
Amphora image: enable log vacuuming

### ISSUE THREAD

**Issue by berendt** [osism/issues#583]
Logs should deleted after 7 days or when there are more than 2G of logs.

**Comment by berendt** [comment]
```
-rw-r-----   1 syslog adm             209M Jul 12 20:27 haproxy.log
-rw-r-----   1 syslog adm             336M Jul 12 00:00 haproxy.log.1
```

**Comment by berendt** [comment]
/etc/logrotate.d/amphora-agent:

```
/var/log/amphora-agent.log {
    daily
    rotate 10
    missingok
    notifempty
    compress
    delaycompress
    sharedscripts
    postrotate
        # Signal name shall not have the SIG prefix in kill command
        # http://pubs.opengroup.org/onlinepubs/9699919799/utilities/kill.html
        kill -s USR1 $(cat /var/run/amphora-agent.pid)
    endscript
}
```

/etc/logrotate.d/haproxy:

```
/var/log/haproxy.log {
    daily
    rotate 7
    missingok
    notifempty
    compress
    delaycompress
    postrotate
        [ ! -x /usr/lib/rsyslog/rsyslog-rotate ] || /usr/lib/rsyslog/rsyslog-rotate
    endscript
}
```

**Comment by artificial-intelligence** [comment]
if nobody looks at these logs anyway this might be a more sustainable action to disable connection logging:

https://docs.openstack.org/octavia/latest/admin/log-offloading.html#disable-tenant-flow-logging

**Comment by berendt** [comment]
Good point. I think it makes sense to improve the log rotating in the Amphora image and to disable the tenant flow logging by default in the future.

**Comment by berendt** [comment]
in environments/kolla/files/overlays/octavia.conf:

```
[amphora_agent]
connection_logging = False
disable_local_log_storage = True
```

**Comment by artificial-intelligence** [comment]
notice that all amphoras have to be recreated for this change to take effect, that's not documented but I had to learn it the hard way.
