### ISSUE TITLE
Detect (and clean-up) orphans and/or errored resources

### ISSUE THREAD

**Issue by garloff** [osism/issues#589]
As a IaaS customer, I don't want to have broken resources in my projects that I can not clean up myself (and that the operator might even dare to charge me for).
As a IaaS operator, I want to avoid collecting broken or orphaned resources that eat database space, screen real estate or even block real hardware resources over time.

Error conditions can lead to broken resources -- these can end up in a state that the customer can not delete them, despite them belonging to her.
* Volumes in reserved, error_deleting state
* Volumes that OpenStack believes are attached to an instance (which does no longer exist)
* Loadbalancers with PENDING_UPDATE (or PENDING_CREATE/_DELETION) state
* [there are probably some more, but the above are the ones I have seen the most often]
A second class are resources belonging to a project that no longer exists (orphans).
A third class are processes, VMs, rbd volumes, ... that should have gone along with the matching OpenStack resource but for some reason have survived.
(Maybe there are more classes. One thing that might be done regularly is database maintenance where we might want to have a nightly database vacuuming (postgres) or so ...)

The job here is IMVHO two steps:
(1) identify which errored or orphaned resources exist and inform operators about them
(2) identify which of these are *always* safe to remove, so we can do automatic cleanup as opposed to only informing operators

**Comment by berendt** [comment]
Script is now part of https://github.com/osism/openstack-resource-manager.

**Comment by fkr** [comment]
@berendt does it make sense to intro this to the community in a blogpost? I'd like to advocate for that.
