### ISSUE TITLE
Create config that avoids / handles high load from cadvisor

### ISSUE THREAD

**Issue by berendt** [osism/issues#59]
https://review.opendev.org/c/openstack/kolla-ansible/+/800068
https://review.opendev.org/c/openstack/kolla-ansible/+/797195 <-- revert of 800068

Please check if there is a working solution for 800068 to reduce the load of cAdvisor by default.

**Comment by osfrickler** [comment]
https://review.opendev.org/c/openstack/kolla-ansible/+/800068 has not been reverted, https://review.opendev.org/c/openstack/kolla-ansible/+/797195 is a revert of https://review.opendev.org/c/openstack/kolla-ansible/+/783887 which was broken. So the load-reducing options should be in place for xena deployments.

**Comment by berendt** [comment]
Can you please suggest/prepare a ustpream backport to stable/wallaby?

**Comment by JohnGarbutt** [comment]
The discussion on the patch said no backport, but I don't think that was the correct decision: https://review.opendev.org/c/openstack/kolla-ansible/+/800068

FWIW, I think removing cadvisor on compute nodes, and only having it on controllers is probably a good idea. It can be useful on compute nodes, but its probably not worth the cost. I find very useful on controllers though.

**Comment by berendt** [comment]
Then we do it as a manual backport for OSISM/SCS. Doesn't matter in the end since we are going to Xena soon.

Cadvisor on compute nodes should be discussed. I think if the load is reduced you can let it run for now and make it optional later.
