### ISSUE TITLE
Add Kolla support for multiple external ceph clusters

### ISSUE THREAD

**Issue by linwalth** [osism/issues#592]
Kolla-Ansible now supports multiple external ceph clusters ( See Cinder Role here: https://github.com/openstack/kolla-ansible/tree/master/ansible/roles/cinder )

Since we use multiple Ceph cluster we would love you to backport this into OSISM soon!

**Comment by linwalth** [comment]
Thank you for the timeline! This helps us plan :)

**Comment by berendt** [comment]
This is now included in the upstream, but will only be usable with stable/2023.2.

**Comment by berendt** [comment]
That‘s done. It‘s part of our kolla-ansible:2023.2 image.
