### ISSUE TITLE
GitHub: remove "PR Labeler" workflow

### ISSUE THREAD

**Issue by berendt** [osism/issues#6]
The "PR Labeler" workflow should be removed everywhere.

Remove the `.github/pr-labeler.yml` file as well as the `.github/workflows/pr-labeler.yml` everywhere.

**Comment by tibeer** [comment]
@berendt done.

Affected repositories:
ansible-collection-commons
ansible-collection-services
ansible-playbooks
container-image-ara-server
container-image-awxclient
container-image-ceph-ansible
container-image-ceph-daemon
container-image-cephclient
container-image-kolla-ansible
container-image-manager
container-image-manager-runner
container-image-openstackclient
container-image-osism-ansible
container-image-patchman
container-images-kolla
documentation
infrastructure
release

Related PRs:
https://github.com/osism/ansible-collection-commons/pull/155
https://github.com/osism/ansible-collection-services/pull/206
https://github.com/osism/ansible-playbooks/pull/159
https://github.com/osism/container-image-ara-server/pull/61
https://github.com/osism/container-image-awxclient/pull/4
https://github.com/osism/container-image-ceph-ansible/pull/122
https://github.com/osism/container-image-ceph-daemon/pull/40
https://github.com/osism/container-image-cephclient/pull/17
https://github.com/osism/container-image-kolla-ansible/pull/161
https://github.com/osism/container-image-manager/pull/65
https://github.com/osism/container-image-manager-runner/pull/2
https://github.com/osism/container-image-openstackclient/pull/37
https://github.com/osism/container-image-osism-ansible/pull/147
https://github.com/osism/container-image-patchman/pull/4
https://github.com/osism/container-images-kolla/pull/62
https://github.com/osism/documentation/pull/202
https://github.com/osism/infrastructure/pull/2
https://github.com/osism/release/pull/73
