### ISSUE TITLE
chrony: use systemd-timesyncd instead

### ISSUE THREAD

**Issue by killermoehre** [osism/issues#602]
Hi,

I wasn't able to find any reason to use `chrony` instead of `sd-timesyncd`. Especially on Ubuntu, where `sd-timesyncd` is default.

Is there any good reason for `chrony`?

BR
Silvio

**Comment by osfrickler** [comment]
systemd-timesyncd is a very restricted NTP implementation, more like running ntpdate in a loop. Ubuntu itself recommends chrony https://ubuntu.com/server/docs/how-to-serve-the-network-time-protocol-with-chrony

**Comment by killermoehre** [comment]
As client Ubuntu suggest `sd-timesyncd` actually https://ubuntu.com/server/docs/network-ntp

**Comment by berendt** [comment]
Do not get the point at the moment . What's wrong with using Chrony for both? So where's the added value in touching and moving that on dozens of productions?

```
By default, Ubuntu uses timedatectl/timesyncd to synchronise time, and they are available by default. See our guide If you would like to know [how to configure timedatectl and timesyncd](https://ubuntu.com/server/docs/use-timedatectl-and-timesyncd).

Users can also optionally [use chrony to serve NTP](https://ubuntu.com/server/docs/how-to-serve-the-network-time-protocol-with-chrony).
```

**Comment by berendt** [comment]
@fkr Please decide if it is worth to change from chrony to timesyncd. While doing this we have to care about two separate services for providing and consuming NTP. And change that on all environments accordingly.

**Comment by fkr** [comment]
I'd stick with chrony. it is established, it serves the purpose well and is less complexity (instead of having different parts for client and serving).
