### ISSUE TITLE
Resource Recommendations

### ISSUE THREAD

**Issue by linwalth** [osism/issues#608]
We have found that with a growing OS deployment and extending of infrastructure on the manager itself the manager node will run into resource bottlenecks. When we deployed the manager there was seemingly no documentation on how much resources the manager ought to have. Thus, we would advise adding documentation of recommended resource allotment for the manager node (Might be helpful for other nodes, too)

**Comment by berendt** [comment]
That‘s done: https://osism.tech/docs/guides/deploy-guide/manager
