### ISSUE TITLE
mariadb version numbers seem wrong

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#609]
according to the osism release page, mariadb versions are as followed:
4.0.0 -> 10.9.2
4.1.0 -> 10.9.3
4.2.0 -> 10.9.3
4.3.0 -> 10.6.12
5.0.0 -> 10.6.12
5.1.0 -> 10.6.12
5.2.0 -> 10.6.14

is this correct? the change from 10.9.3 to 10.6.12 between osism 4.2.0 and 4.3.0 seems strange. when following the docu https://docs.osism.tech/upgrade/manager.html and doing the MANAGER_VERSION=4.3.0 gilt overlay command, the version changed in images.yml is also 10.9.3 for osism 4.3.0. (mariadb_tag: "10.9.3"). which version is correct?

**Comment by berendt** [comment]
* Control plane: https://quay.io/repository/osism/mariadb-server?tab=tags
* Management plane: https://hub.docker.com/_/mariadb

**Comment by schulze-b1** [comment]
after the manager osism update to 4.3.0 i saw that container manager-mariadb-1 was not running in version 10.9.3 as written in images.yml by gilt overlay, but in version 10.11.4. after digging through some ansible code, it seems the variable mariadb_tag: in images.yml has the false name and it defaults to the latest available version. but it works with the following variables:
`ara_server_mariadb_tag: "10.9.3"`
`mariadb_image: "{{ docker_registry }}/library/mariadb:{{ ara_server_mariadb_tag }}"`

could you please check if there is an error with gilt overlay or the environments/manager/images.yml?

**Comment by berendt** [comment]
Good point. Weird that no one has noticed it yet. Really seems wrong.
