### ISSUE TITLE
redis version numbers seem wrong

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#610]
according to the osism release page, redis versions are as followed:
4.0.0 -> 7.0.4-alpine
4.1.0 -> 7.0.5-alpine
4.2.0 -> 7.0.5-alpine
4.3.0 -> 5.0.7
5.0.0 -> 6.0.16

is this correct? the change from 7.0.5-alpine to 5.0.7 between osism 4.2.0 and 4.3.0 seems strange. when following the docu https://docs.osism.tech/upgrade/manager.html and doing the MANAGER_VERSION=4.3.0 gilt overlay command, the version changed in images.yml is also 7.0.5-alpine for osism 4.3.0. (redis_tag: "7.0.5-alpine"). which version is correct?

**Comment by berendt** [comment]
The redis image we have on the control plane is a different one than we have on the management plane.

Control plane: https://quay.io/repository/osism/redis?tab=tags (5.x for OSISM 4.x and 6.x for OSISM 5.x).
Management plane: https://hub.docker.com/_/redis (7.x for OSISM 4.x and OSISM 5.x)

**Comment by berendt** [comment]
On the release page we only list the versions of the Control Plane, not the Management Plane. Will change this with the 5.3.0 release and will list all versions there.

**Comment by schulze-b1** [comment]
after the manager osism update to 4.3.0 i saw that container manager-redis-1 was not running in version 7.0.5-alpine as written in images.yml by gilt overlay, but in version 7.0.12-alpine. after digging through some ansible code, it seems the variable redis_tag: in images.yml has the false name and it defaults to the latest available version. but it works with the following variables:
`manager_redis_tag: "7.0.5-alpine"`
`redis_image: "{{ docker_registry }}/library/redis:{{ manager_redis_tag }}"`

could you please check if there is an error with gilt overlay or the environments/manager/images.yml?

**Comment by berendt** [comment]
Good point. Weird that no one has noticed it yet. Really seems wrong.
