### ISSUE TITLE
Is OVN provider driver for Octavia available in Horizon?

### ISSUE THREAD

**Issue by mohaa7** [osism/issues#612]
1. I enabled OVN for Octavia and I can create loadbalancers using the command `openstack loadbalancer create` by adding `--provider ovn` and it works well.
But in the Horizon, there's no choice for choosing OVN while I deployed it by `octavia_provider_drivers: "ovn:OVN provider"`!
I get this error when I go through the default "Create Load Balancer" dialoge box in Horizon:
```
BadRequestException: 400: Client Error for url: http://172.16.14.2:9876/v2.0/lbaas/loadbalancers, Provider 'amphora' is not enabled.
```
The blue arrow in the picture below points to the Amphora stuff while OVN is in use.

---
2. Those which are created in the command line, are not shown in the Horizon (the pink arrow in the picture below points to the error)

![image](https://github.com/osism/issues/assets/118692398/99d20967-907e-47a5-8cd9-7cd4f1502406)

**Comment by berendt** [comment]
That's probably a missing feature in Horizon. Can you please deploy and test it with the Skyline service? Horizon's development has stalled quite a bit in recent years.

**Comment by mohaa7** [comment]
All our environments (Dev/Stage/Prod) are on the Xena version that does not support Skyline.

**Comment by berendt** [comment]
This is suboptimal since we only support from the Zed release upwards. Xena has not been supported for a long time from our side. From September/October onwards, approximately, we will only support Antelope. Make sure you update to Zed.

**Comment by mohaa7** [comment]
All our environments (Dev/Stage/Prod) are on the Xena version that does not support Skyline.
