### ISSUE TITLE
Mitogen Workaround for newer Ansible Versions

### ISSUE THREAD

**Issue by linwalth** [osism/issues#615]
After looking through the issues on Github pertaining to Mitogen, i found that there is a mitogen role that apparently works with newer versions of Ansible. Maybe we can utilize it.

https://github.com/mitogen-hq/mitogen/issues/996#issuecomment-1562760569

Galaxy Role in question:
https://galaxy.ansible.com/serverscom/mitogen

If you implement it, i can test it for you, if you want.

**Comment by berendt** [comment]
This looks like some code dump from mitogen-hq/mitogen. There was just a release of Mitogen a few days ago with Ansible 2.13 support. 2.14 and 2.15 will surely come soon as well.
