### ISSUE TITLE
osism-generic state role not working as expected

### ISSUE THREAD

**Issue by linwalth** [osism/issues#616]
osism-generic state --limit $HOST --extra-vars "state_bootstrap_status=False" does not work as intended, as in: the osism.fact will not be overwritten with the status=False like https://github.com/osism/ansible-collection-commons/blob/main/roles/state/tasks/main.yml#L11 intends to.

**Comment by berendt** [comment]
You cannot use the state role to overwrite the bootstrap status of a node. I will add a new command for this.
