### ISSUE TITLE
"The OVN provider only supports SOURCE_IP_PORT load balancer algorithm", true?

### ISSUE THREAD

**Issue by mohaa7** [osism/issues#621]
In the OVN provider part of the lenk below, it's given that: "The OVN provider only supports Layer 4 TCP and UDP network traffic and the SOURCE_IP_PORT load balancer algorithm. The OVN provider does not support health monitoring."

```
openstack loadbalancer pool create --protocol TCP --lb-algorithm SOURCE_IP_PORT --listener listener1 --name pool1
```

Ref: https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/13/html/using_octavia_for_load_balancing-as-a-service/create-other-kinds-lbs_rhosp-lbaas#create-ovn-lb_create-other-kinds-lbs

Do you approve of this? If yes, do you know if more algorithms will be supported in the future?

**Comment by berendt** [comment]
Please have a look at the limitations of the OVN provider driver in Octavia. Upstream is working on the limitations. But it will take time...

https://docs.openstack.org/ovn-octavia-provider/latest/admin/driver.html#limitations-of-the-ovn-provider-driver
