### ISSUE TITLE
libvirt secrets not generated correctly

### ISSUE THREAD

**Issue by linwalth** [osism/issues#631]
As we are using three different Ceph Clusters for RBD in three different AZs, we need three different keyrings for cinder and three different keyrings for nova respectively. We are using templated ceph.client.nova.keyring / ceph.client.cinder.keyring files for the vars to propagate correctly to the right AZ.

Our Problem is now as follows:

The Nova secret which is being deployed as files to the /etc/kolla/nova-libvirt/secrets/ is not deployed correctly, because while that task uses lookup(template) which works fine with our ceph.client.nova.keyring file that uses the variable differing between the AZ groups, the external_ceph playbook is broken by the patch, as the result: item key is not closed correctly with double handlebars:

https://github.com/osism/container-image-kolla-ansible/blob/9d89939142784613448522df3ef0da14b0750b04/patches/zed/external-ceph-host-specific.patch#L207

This then breaks the base64 file, because the key is written correctly to the secret, but then the letters `| default` are also written to the secret file which then causes the secret to be read incorrectly into the libvirt container

The Cinder secret which is being deployed as files to the /etc/kolla/nova-libvirt/secrets/ is not being deployed correctly, because the task uses lookup(file) which returns a value of "None".

https://github.com/osism/container-image-kolla-ansible/blob/9d89939142784613448522df3ef0da14b0750b04/patches/zed/external-ceph-host-specific.patch#L212

`{{ item.result }}` is thus "None" and written to the secret file.

https://github.com/openstack/kolla-ansible/blob/e0b212d72de8aac1d5fbbc6562f69ef0190a80b9/ansible/roles/nova-cell/templates/libvirt-secret.j2

What we need:

- Missing Handlebars added
- lookup(template) instead of lookup(file) for cinder key

Please fix this in a timely fashion - we need it ASAP :)

**Comment by chschilling** [comment]
Is there any way, we can help here?
I don't know how to update the patchfile, as the default is not part of that project.

Greetings,
Christian

**Comment by berendt** [comment]
We are working on it, but I already told Linus yesterday that we can't expect a solution before Friday. Just takes its time until we have processed it.

**Comment by berendt** [comment]
CI looks good.

@chschilling @linwalth Please test.

**Comment by chschilling** [comment]
Still an issue with the nova keyring unfortunatly ;)
We did not see it as well, but for the novakeyring, you didn't miss the }}. you've put the "| default" outside the clambs

**Comment by berendt** [comment]
@chschilling have you already done another test after the second adjustment?

**Comment by chschilling** [comment]
I am off today, need to test that tomorrow

**Comment by chschilling** [comment]
That looks promising now!

Thank you for the fast response!

Greetings,

Christian

**Comment by berendt** [comment]
Then I would close this. If there are still problems, please open again.
