### ISSUE TITLE
Write an article about how we implemented IPv6 in REGIO.cloud

### ISSUE THREAD

**Issue by berendt** [osism/issues#636]

**Comment by osfrickler** [comment]
Upstream doc created: https://review.opendev.org/c/openstack/neutron-dynamic-routing/+/891038

**Comment by osfrickler** [comment]
Upstream doc merged https://docs.openstack.org/neutron-dynamic-routing/latest/install/usecase-ipv6.html
Please re-open if you think something is missing.
