### ISSUE TITLE
Refactor/rework Ceph documentation

### ISSUE THREAD

**Issue by ppkuschy** [osism/issues#642]
The Ceph documentation for OSISM/SCS is currently not really well-structured, in some regards outdated and is missing a lot of things and details related to operating Ceph deployed with OSISM (and Ceph in general). Therefore this issue was created to put all these issues under one umbrella to rework and enhance the documentation.

**Comment by fkr** [comment]
Adding/removal of OSDs with ceph-ansible still needs to be documented.
