### ISSUE TITLE
rsyslog conf update failure

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#646]
we were following the docu at https://docs.osism.tech/services/generic.html#update-rsyslog-configuration to update rsyslog conf, since we changed the variables "rsyslog_additional_host:" and "rsyslog_additional_port:" in environments/generic/configuration.yml. but we get the following error:
$ osism-generic common --skip-tags always --tags logging
ERROR! Unable to retrieve file contents
Could not find or access '/ansible/generic/generic-systohc.yml' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option

how can we update the rsyslog settings? is there another command?

**Comment by Nils98Ar** [comment]
@berendt Can rsyslog be used to send all kolla logs to a syslog server?

**Comment by berendt** [comment]
Sure. You can use the 71-additional-log-server.conf for this by setting rsyslog_additional_host and rsyslog_additional_port.

https://github.com/osism/ansible-collection-services/blob/main/roles/rsyslog/templates/71-additional-log-server.conf.j2

**Comment by schulze-b1** [comment]
@berendt this only defaults to UDP in 71-additional-log-server.conf.j2 with one @ - how can we send logs over TCP (*.* @@...) as the customer requires this. a flag or variable for this would be good. or can we put the whole 71-additional-log-server.conf in environments/kolla/files/overlays/rsyslog/ to overwrite the default UDP setting?

**Comment by berendt** [comment]
The rsyslog role is not related to kolla-ansible. It is part of the osism.services collection.

You can open a PR for the template @ https://github.com/osism/ansible-collection-services/blob/main/roles/rsyslog/templates/71-additional-log-server.conf.j2 and add a new parameter that keeps the "@". This way you can modify it via environments/generic/configuration.yml (or environments/configuration.yml).
