### ISSUE TITLE
deployment of Ceph-RGWS for Swift

### ISSUE THREAD

**Issue by rmueller-b1** [osism/issues#652]
Hi,
I am trying to deploy ceph-rgws prior to deploy Swift. I have the issue that there is absolutely no documentation from OSISM. When trying to use the documentation provided by Openstack and Ceph themselves, I am running into an error because `rgws_instances` is not defined. What is that variable and where should it be defined with what?

Please provide a proper documentation how to deploy Ceph-RGWs and Swift.

Kind regards.

**Comment by berendt** [comment]
The documentation is currently being revised. It will take some time until we deliver the content there.

Please take the osism/testbed for the moment as a reference. S3 is being rolled out there with RGW.

https://github.com/osism/testbed/blob/main/environments/ceph/configuration.yml#L41-L57
https://github.com/osism/testbed/blob/main/scripts/deploy/100-ceph-services-basic.sh#L18
https://github.com/osism/testbed/blob/main/environments/openstack/playbook-bootstrap-ceph-rgw.yml
https://github.com/osism/testbed/blob/main/scripts/bootstrap/300-openstack-services.sh#L11

Also please share the failed tasks + the log output of this task 

You have to set ``[ceph-rgw:children]`` in inventory/99-overwrite to defined the RGW nodes.

**Comment by rmueller-b1** [comment]
The failed task is this:
```
TASK [ceph-config : create rados gateway instance directories] *******************************************************************************************************************************************************************************
task path: /ansible/roles/ceph-config/tasks/rgw_systemd_environment_file.yml:2
fatal: [Control-Node-1]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'instance_name'\n\nThe error appears to be in '/ansible/roles/ceph-config/tasks/rgw_systemd_environment_file.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: create rados gateway instance directories\n  ^ here\n"
}
fatal: [Control-Node-2]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'instance_name'\n\nThe error appears to be in '/ansible/roles/ceph-config/tasks/rgw_systemd_environment_file.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: create rados gateway instance directories\n  ^ here\n"
}
fatal: [Control-Node-3]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'instance_name'\n\nThe error appears to be in '/ansible/roles/ceph-config/tasks/rgw_systemd_environment_file.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: create rados gateway instance directories\n  ^ here\n"
}

```
I changed the node names. In this run the playbook was running with `-vvvv`.
According to what I saw in the playbooks the variable `rgw_instances` has to be defined. I don't know where to set that with what. The documentation from Ceph and Kolla does not provide any insides to that.
Setting the `[ceph-rgw]` was no issue.

**Comment by berendt** [comment]
There is a task that sets rgw_instances as fact. The task is part of the ceph-facts role. Which is part of the ceph-rwgs play.

Have a look for the result of this task in the Ansible logs.

```
- name: set_fact rgw_instances without rgw multisite
  set_fact:
    rgw_instances: "{{ rgw_instances|default([]) | union([{'instance_name': 'rgw' + item|string, 'radosgw_address': hostvars[ceph_dashboard_call_item | default(inventory_hostname)]['_radosgw_address'], 'radosgw_frontend_port': radosgw_frontend_port|int + item|int }]) }}"
  with_sequence: start=0 end={{ radosgw_num_instances|int - 1 }}
  delegate_to: "{{ ceph_dashboard_call_item if ceph_dashboard_call_item is defined else inventory_hostname }}"
  delegate_facts: "{{ true if ceph_dashboard_call_item is defined else false }}"
  when:
    - ceph_dashboard_call_item is defined or
      inventory_hostname in groups.get(rgw_group_name, [])
    - not rgw_multisite | bool
```

**Comment by Nils98Ar** [comment]
I had the same issue and for me the `radosgw_address` in the storage nodes host_vars was missing (see `AnsibleUndefined`). 
Adding it fixed it.
```
{
    "rgw_instances": "[{'instance_name': 'rgw0', 'radosgw_address': AnsibleUndefined, 'radosgw_frontend_port': 8081}]"
}
```

In the end the `restart ceph osds daemon(s)` task never reported back that its finished but it seems to work anyway.
![image](https://github.com/osism/issues/assets/48221746/bfe34832-8884-4231-9a60-27db51fc8443)

**Comment by Nils98Ar** [comment]
@berendt One problem is left.

I accidentally created the internal swift endpoint via `playbook-bootstrap-ceph-rgw.yml` with `https` first.

Afterwards I deleted and recreated it with `http` but now cannot convince horizon to use the new endpoint. It still uses `https` but the internal swift endpoint in keystone is `http`. Deleting and re-deploying the horizon containers did not help.

Any idea?

**Comment by Nils98Ar** [comment]
Okay I missed this one: https://github.com/osism/testbed/blob/50cdb22dd641428e2801eb3750ebc0f7839c9ff0/environments/ceph/configuration.yml#L52

Maybe this is alreay the solution... we will see.

**Comment by Nils98Ar** [comment]
My workaround was enabling TLS for internal API in the end... now it works.

**Comment by berendt** [comment]
Deployment of Ceph RGW is now documented.

**Comment by Nils98Ar** [comment]
@berendt According to the documentation at https://osism.github.io/docs/guides/deploy-guide/ceph#rgw-service the "manual" steps from [playbook-bootstrap-ceph-rgw.yml](https://github.com/osism/testbed/blob/main/environments/openstack/playbook-bootstrap-ceph-rgw.yml) which are used in the testbed are not needed anymore right?

**Comment by Nils98Ar** [comment]
And additional question: is the `osism apply ceph-rgw` play only available in 6.0.0? At least not in 5.3.0. I guess this one does the things from [playbook-bootstrap-ceph-rgw.yml](https://github.com/osism/testbed/blob/main/environments/openstack/playbook-bootstrap-ceph-rgw.yml)?

**Comment by berendt** [comment]
That's now part of the osism apply ceph-rgw command. Naming is a little bit confusing. osism apply ceph-rgws will deploy the RGW services and osism-apply ceph-rgw is a Kolla-Ansible play preparing the endpoint.

**Comment by Nils98Ar** [comment]
But only in 6.0.0?

**Comment by berendt** [comment]
Should work with Zed + 2023.1.

**Comment by Nils98Ar** [comment]
It's not available in our 5.3.0 / Zed deployment. But I can check again tomorrow with 6.0.0 ;)

```
dragon@manager01:/opt/configuration$ osism apply | grep ceph-rgw
| ceph-rgw-add-users-buckets                                       | ceph           |
| ceph-rgws                                                        | ceph           |
| kolla-ceph-rgw                                                   | kolla          |
| loadbalancer-ceph-rgw                                            | kolla          |
```
Running `osism apply ceph-rgw` does nothing.

**Comment by Nils98Ar** [comment]
Maybe it's the `kolla-ceph-rgw` one?

**Comment by berendt** [comment]
It's probably kolla-ceph-rgw there.
