### ISSUE TITLE
Compute node local SSD storage

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#655]
Hi,

we are currently planning the implementation of local SSD storage in our OSISM/SCS cloud.

As far as I know local storage with the LVM driver does not support instance migration and now we are wondering if there are other options.

What about this:
- add SSDs to the compute nodes
- configure `nova_backend_ceph: "no"`
- configure `docker_runtime_directory` to new SSDs and move contents of `/var/lib/docker` to the new location
- ensure that the SSD flavors are the only ones with root disk

Then I would expect that:
- root disks of the SSD flavor instances (managed by nova) are located on the compute nodes new local SSDs somewhere in the `volumes/nova_compute/_data` directory
- root disks of non-SSD flavor instances (created with `--block-device` of `openstack server create` and managed by cinder) are located in ceph
- live migration of instances with SSD flavors works with `--block-migration`

I have no idea if this could work. What do you think? @garloff @berendt @maliblatt

**Comment by berendt** [comment]
We do it this way.

* sample nova.conf overlay file ``environments/kolla/files/overlays/nova/com1017.conf``

```
[libvirt]
images_type = raw

[glance]
enable_rbd_download = true
```

* sample parameters from ``inventory/host_vars/com1017.yml``

```
nova_instance_datadir_volume: /var/lib/nova
nova_backend_ceph: no
```

* we use ext4 on a single NVMe SSD

```
dragon@com1017:~$ mount | grep nova
/dev/nvme1n1p1 on /var/lib/nova type ext4 (rw,relatime)
```

I don't know if live migration works with it. By definition, we have instances with local storage flavors that can be stopped/restarted at any time.

**Comment by Nils98Ar** [comment]
Ahh `enable_nova_libvirt_container` is disabled by default so we do not need to move the `/var/lib/docker` directory right?

- Is it possible to resize these volumes? 
- Can you check if live migration works with `--block-migration`?
- Can this compute node local storage be used in K8s for (ephemeral) volumes somehow?

**Comment by Nils98Ar** [comment]
Ok I think `enable_nova_libvirt_container` is enabled. Can we define a path outside of the docker container `for nova_instance_datadir_volume` anyway?
By default this seems to be in the `nova_compute` docker volume.

**Comment by berendt** [comment]
> Ahh `enable_nova_libvirt_container` is disabled by default so we do not need to move the `/var/lib/docker` directory right?

I think the datadir parameter is the better way.

> * Is it possible to resize these volumes?

These are not volumes. Resize is not possible.


> * Can you check if live migration works with `--block-migration`?

We only have instances on these nodes that also use local storage.  We do not migrate from there.


> * Can this compute node local storage be used in K8s for (ephemeral) volumes somehow?

Yes. Just create an instance with a flavor with ephemeral > 0 on such a node.

We use host aggregates for this purpose:

```
dragon@mgr001:~$ openstack --os-cloud admin aggregate show regiocloud-local
+-------------------+--------------------------------------+
| Field             | Value                                |
+-------------------+--------------------------------------+
[...]
| name              | regiocloud-local                     |
| properties        | local_storage='true'                 |
[...]
+-------------------+--------------------------------------+
```

We than place all instances with the local storage flavors on the nodes in this host aggregate.

```
dragon@mgr001:~$ openstack --os-cloud admin flavor show SCS-4V-16-100s
+----------------------------+---------------------------------------------+
| Field                      | Value                                       |
+----------------------------+---------------------------------------------+
[...]
| name                       | SCS-4V-16-100s                              |
| os-flavor-access:is_public | True                                        |
| properties                 | hw_rng:allowed='True', local_storage='true' |
[...]
+----------------------------+---------------------------------------------+
```

**Comment by berendt** [comment]
> Ok I think `enable_nova_libvirt_container` is enabled. Can we define a path outside of the docker container for `nova_instance_datadir_volume` anyway?
> By default this seems to be in the `nova_compute` docker volume.

The ``/var/lib/nova`` directory above is outside of the container.

```
dragon@com1017:~$ cat /etc/fstab
# /etc/fstab: static file system information.
[...]
/dev/nvme1n1p1 /var/lib/nova ext4 defaults 0 2
```

**Comment by berendt** [comment]
On a node with local storage:

```
$ docker inspect nova_libvirt
[...]
            {
                "Type": "bind",
                "Source": "/var/lib/nova",
                "Destination": "/var/lib/nova",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
[...]
```

On a node without local storage:

```
$ docker inspect nova_libvirt
[...]
            {
                "Type": "volume",
                "Name": "nova_compute",
                "Source": "/var/lib/docker/volumes/nova_compute/_data",
                "Destination": "/var/lib/nova",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
[...]
```

**Comment by Nils98Ar** [comment]
> On a node with local storage:
> 
> ```
> $ docker inspect nova_libvirt
> [...]
>             {
>                 "Type": "bind",
>                 "Source": "/var/lib/nova",
>                 "Destination": "/var/lib/nova",
>                 "Mode": "rw",
>                 "RW": true,
>                 "Propagation": "rprivate"
>             },
> [...]
> ```
> 
> On a node without local storage:
> 
> ```
> $ docker inspect nova_libvirt
> [...]
>             {
>                 "Type": "volume",
>                 "Name": "nova_compute",
>                 "Source": "/var/lib/docker/volumes/nova_compute/_data",
>                 "Destination": "/var/lib/nova",
>                 "Driver": "local",
>                 "Mode": "rw",
>                 "RW": true,
>                 "Propagation": ""
>             },
> [...]
> ```

Ah okay that makes sense, then it uses a bind mount instead of a volume!

But I guess we can still recreate the K8s control plane/worker node with another SSD flavor to increase the root disk size...

We cannot provide dedicated compute nodes for SSD flavors. But I also don't see why this is necessary if the SSD flavors are the only ones with root disks.

So you are not able to test a live migration in a SSD flavor host aggregate?

**Comment by berendt** [comment]
> We cannot provide dedicated compute nodes for SSD flavors. But I also don't see why this is necessary if the SSD flavors are the only ones with root disks.

We have dedicated compute nodes with NVMe SSDs in them that we only use for this type of flavors. In our environment each compute node is meant for a specific use case. Local storage, GPU, ...

> So you are not able to test a live migration in a SSD flavor host aggregate?

No, we only have these nodes in production and no test systems for them. You would have to test this at your site if you need live migrations for this.

**Comment by Nils98Ar** [comment]
But SSD flavors (with root disk) and non-SSD flavors (without root disk) on the same compute node should also be possible or do I miss something?

**Comment by berendt** [comment]
I did not write that it is not possible. We just don't do it that way on our environment.

**Comment by Nils98Ar** [comment]
Is K8s happy if control planes go down during OpenStack compute node maintenance and come back later? And the same for K8s workloads with ephemeral volumes if worker nodes go down for some time?

**Comment by Nils98Ar** [comment]
> I did not write that it is not possible. We just don't do it that way in our environment.

Okay I just wasn‘t sure.

**Comment by Nils98Ar** [comment]
@berendt Do you think the running instances will continue working with its ceph root disks after changing `nova_backend_ceph: "yes"` to `nova_backend_ceph: "no"` and re-deploying nova?

The only instances that have nova root disks are amphoras and k8s control planes/nodes.
After changing the nova backend I would initiate a rolling update for the k8s instances and a failover for the octavias.

My hope would be that the instances are then recreated with local root disks on the compute host.

**Comment by berendt** [comment]
I'm pretty sure it's not a good idea and that it will not work. I wouldn't even try it if it's only the amphorae and K8s nodes. You can simply rotate them.

**Comment by Nils98Ar** [comment]
What do you mean by roating?

My idea was to
 - change the setting
 - re-deploying nova
 - recreating the k8s instances and amphoras with rolling updates and octavia failovers (what would I call rotating)

What would you do in which order or what exactly would you do differently?

**Comment by berendt** [comment]
This way. But node by node. Deactivate node, make node empty, change configuration, activate node, next node.

**Comment by berendt** [comment]
I think it‘s all documented here: https://osism.tech/docs/guides/configuration-guide/openstack/nova#local-ssd-storage

**Comment by Nils98Ar** [comment]
@berendt 

Should the host aggregate and flavor part be added to the docs?

And maybe a hint which overlay file should be used if local storage is deployed for all nodes?
