### ISSUE TITLE
Allow vm.swappiness to be set individually (or just to 1)

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#656]
Hi,

We are running a hyper-converged setup with Nova and Ceph in the same physical hosts. Ceph-ansible unfortunately sets sysctl's swappiness to 10. This leads to swapping issues on our system. We need this value to be set to 1.

Problem:
ceph-ansible creates 

```
 root@compute1:/etc/sysctl.d# cat ceph-tuning.conf
 fs.aio-max-nr=1048576
 fs.file-max=26234859
 vm.zone_reclaim_mode=0
 vm.swappiness=10
 vm.min_free_kbytes=4194303
```

based on this Ansible default variable:

```
os_tuning_params:
  - { name: fs.file-max, value: 26234859 }
  - { name: vm.zone_reclaim_mode, value: 0 }
  - { name: vm.swappiness, value: 10 }
  - { name: vm.min_free_kbytes, value: "{{ vm_min_free_kbytes }}" }
```

Further problem: 
/etc/sysctl.d/ceph-tuning.conf has a very high alphanumerical position.

We just want to override vm.swappiness and not the other values. In the past it turned out to be a bad solution to override a bunch of settings if you just need to override one of them as the others might change over time as well without notice.

Kind regards,
André.

**Comment by berendt** [comment]
With the proposed change it is possible to overwrite the vm.swappiness value without touching the other values. I do not want to change the default value of vm.swappiness.

Only disadvantage: This way we have to track changes of os_tuning_params in upstream. But I think this is okay.

**Comment by nerdicbynature** [comment]
Is there a technical reason why you don’t want this value to be changed? On our side the Swap is filling up.

**Comment by berendt** [comment]
Let's talk briefly in a moment in the Weekly. In the end, I don't have much of an opinion about it. We can also change the default.

**Comment by artificial-intelligence** [comment]
> This leads to swapping issues on our system.

Can you specify what exactly these issues are? Do you see performance degradation that you can pin to the pagecache? If yes, how did you track this down, that is, how do you know that the swapping is the root cause of the issue, whatever the issue is?

Thanks.

**Comment by nerdicbynature** [comment]
Our monitoring indicates high usage of swap space on normal operation. This alone is not a problem at all. However, disabling monitorig is not the best option. So we want to set it from currently 10 to 1 (aka "nearly disable swap") to leave the swap space free for emergency situations in which a monitoring can assist us in detecting those critical situations properly. 

While investigating the best option for doing so we found out that ceph-tuning.conf sets this value. Overriding this override is not the best option in my opinion. Also, I think this setting might be useful for others as well. That's the reason for opening this issue.

**Comment by fkr** [comment]
> Our monitoring indicates high usage of swap space on normal operation. 

Which processes are being paged? And what is 'high usage'?

**Comment by nerdicbynature** [comment]
I am out of office today, so can’t check rn

With high usage I mean 50%+

From my experience setting swappiness to 1 is quite a normal thing. So I am wondering about the questions.
If you think this is not useful for others we will write custom Ansible code to set it. So it’s not a big issue.

**Comment by artificial-intelligence** [comment]
I was just trying to better understand the problem, no judging on my part.

I'd like to point out though that monitoring != alerting. So I'd like to ask if you have alerts firing because of the high swap usage? I'm still just trying to better understand the problem here.

Thanks for all the useful information provided so far.

**Comment by nerdicbynature** [comment]
No worries, Felix :)

Yes indeed, we have an increasing number of warning alerts from our monitoring. In the past we ignored those occasional warnings. But since they increase we decided to act on them.

**Comment by berendt** [comment]
As discussed in the SCS team call: We will not change the default + we will not introduce additional parameters. Please use ``os_tuning_params`` to overwrite the value of ``vm.swappiness``.
