### ISSUE TITLE
Prepare 6.0.0 pre-release

### ISSUE THREAD

**Issue by berendt** [osism/issues#657]

**Comment by berendt** [comment]
- [ ] wrong tag for opensearch-dashboards image (2023.1 instead of 2.9.0.202309XX.0)

**Comment by osfrickler** [comment]
The lb-mgmt-net is created with a gateway IP when it should not have one. In combination with OVN this leads to nodes received an invalid default route. Workaround in kolla-ansible: https://review.opendev.org/c/openstack/kolla-ansible/+/894219

The root-cause for this issue lies in ansible-collections-openstack, verified in https://review.opendev.org/c/openstack/ansible-collections-openstack/+/894254. Will create bug report and a fix next.

**Comment by berendt** [comment]
- [ ] backport senlin bugfix: https://review.opendev.org/c/openstack/kolla-ansible/+/894383

**Comment by berendt** [comment]
Refstack is happy with the exclude test:

```
2023-09-08 18:46:32.787838 | orchestrator | ======
2023-09-08 18:46:32.787842 | orchestrator | Totals
2023-09-08 18:46:32.787845 | orchestrator | ======
2023-09-08 18:46:32.787848 | orchestrator | Ran: 299 tests in 2179.1327 sec.
2023-09-08 18:46:32.787852 | orchestrator |  - Passed: 294
2023-09-08 18:46:32.787855 | orchestrator |  - Skipped: 5
2023-09-08 18:46:32.787857 | orchestrator |  - Expected Fail: 0
2023-09-08 18:46:32.787860 | orchestrator |  - Unexpected Success: 0
2023-09-08 18:46:32.787863 | orchestrator |  - Failed: 0
2023-09-08 18:46:32.787866 | orchestrator | Sum of execute time for each test: 1547.7080 sec.
```

**Comment by berendt** [comment]
> The lb-mgmt-net is created with a gateway IP when it should not have one. In combination with OVN this leads to nodes received an invalid default route. Workaround in kolla-ansible: https://review.opendev.org/c/openstack/kolla-ansible/+/894219
> 
> The root-cause for this issue lies in ansible-collections-openstack, verified in https://review.opendev.org/c/openstack/ansible-collections-openstack/+/894254. Will create bug report and a fix next.

Temp backport is available and part of 6.0.0a: https://github.com/osism/container-image-kolla-ansible/commit/74b1d560c7c2b99d3053b5b02a2c4a60fce792f8

**Comment by berendt** [comment]
Cloud in a box now also on 6.0.0a: https://github.com/osism/cloud-in-a-box/commit/9f2531cc4788c5a461a74cdfdd14f57d11fe461b

**Comment by berendt** [comment]
- [ ] Cloud in a Box Upgrade test (5.3.0 -> 6.0.0a)

**Comment by berendt** [comment]
Close this as done. All the little things are done so far.
