### ISSUE TITLE
Find the primary source of the SCS flavors

### ISSUE THREAD

**Issue by berendt** [osism/issues#660]
Avoid the use of more additional repositories like the planned openstack-flavors repository. the SCS flavors.yaml should have exactly one place.

**Comment by garloff** [comment]
https://github.com/SovereignCloudStack/standards/blob/main/Tests/iaas/scs-0103-v1-flavors.yaml

**Comment by berendt** [comment]
Removed the openstack-flavors repository again. This URL is already in use in the openstack-flavor-manager. Nothing to change there.
