### ISSUE TITLE
Multiple CEPH-instances

### ISSUE THREAD

**Issue by killermoehre** [osism/issues#665]
Hi,

can one OSISM manager deploy multiple CEPH instances?

We have the requirement, that we need three CEPH environments (complete with manager, monitor and nodes) on different sets of nodes.

**Comment by berendt** [comment]
Yes, this is possible with sub environments. You only have to create a new e.g. ``ceph.foobar`` directory in the ``environments`` directory. Inside the ``ceph.foobar`` directory you need the same files like in a normal ceph environment directory. 

You have to overwrite the used host groups and to add those host groups to the inventory (``10-custom``).

```
##########################
# groups

ceph_group_name: ceph.rgw

client_group_name: ceph.rgw
grafana_server_group_name: ceph.rgw
iscsi_gw_group_name: ceph.rgw
mds_group_name: ceph.rgw
mgr_group_name: ceph.rgw
mon_group_name: ceph.rgw
nfs_group_name: ceph.rgw
osd_group_name: ceph.rgw
rbdmirror_group_name: ceph.rgw
restapi_group_name: ceph.rgw
rgw_group_name: ceph.rgw
rgwloadbalancer_group_name: ceph.rgw
```

You can choose this sub environment via the ``--sub`` parameter.

E.g. to deploy the mon service in the ``ceph.rgw`` environment use ``osism apply --sub rgw ceph-mons``.

This way you can manage as many Ceph clusters you want to.

**Comment by berendt** [comment]
Sub environments are also usable with Kolla. This way you can also manage multiple OpenStack environments with a single manager instance.

**Comment by killermoehre** [comment]
@berendt can you elaborate a bit more on how this works with the inventory? Are we supposed to create a `10-custom` in `/opt/configuration/environments/ceph.foobar/`?

Or do we create custom groups in `/opt/configuration/inventory/10-custom` and then configure in `/opt/configuration/environments/ceph.foobar/configuration.yml` which group is to use?

Is there some command/search to check wherever the groups are mentioned? Can we assume your list is exhaustive? Also, we switched to OSISM 7.0.2 since I asked my question, so how does this apply to the new Ceph rollout tooling?
