### ISSUE TITLE
Use ansible_facts in configuration repository

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#669]
```
Kolla upgrade 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_<storage_interface/monitor_interface>'
```

This happens during the OSISM 5.3.0 updates for several  `Copy over ceph.conf for XY` and `Copying over prometheus config file` tasks.
Actions are `merge_yaml`,  `merge_configs` or `template`.

I ran `osism apply facts && osism apply configuration && osism reconciler sync` before.

**Comment by Nils98Ar** [comment]
Seems to be an issue in the overlay files/templates?

**Comment by Nils98Ar** [comment]
Seems like for cookiecutter now `ansible_facts` are used at least in the `ceph.conf` overlay files:

- https://github.com/osism/cfg-cookiecutter/commit/a5859834c409d50457bef61f98657ab04a9d0ef0

And in the testbed `ansible_facts` is not used but `monitor_address` instead of `storage_interface`.

- https://github.com/osism/testbed/blob/50cdb22dd641428e2801eb3750ebc0f7839c9ff0/environments/kolla/files/overlays/glance/ceph.conf#L2

**Comment by Nils98Ar** [comment]
I guess these changes will fix it:

- https://github.com/osism/testbed/commit/2d73cc37e7415d53fba072c54d17f3a348bc145e
- https://github.com/osism/cfg-cookiecutter/commit/a5859834c409d50457bef61f98657ab04a9d0ef0

**Comment by Nils98Ar** [comment]
Yes it does. @berendt Should this be mentioned in the release notes?

**Comment by berendt** [comment]
Yes, I will mention this in the release note.
