### ISSUE TITLE
ceph-rgw as swift backend via kolla

### ISSUE THREAD

**Issue by linwalth** [osism/issues#67]
Hello everyone,

As Kolla-Ansible allows to use ceph-rgw as a backend instead of swift (https://docs.openstack.org/kolla-ansible/latest/reference/storage/external-ceph-guide.html#radosgw) i have tried to deploy it. 

I did not find the the referenced role in the osism_kolla_ansible container, though. What I did find was the rgw-endpoint role, but HAproxy does not create the :8080 endpoint.

What is the recommended course of action to use an external RGW instead of swift in OSISM?

**Comment by berendt** [comment]
For the moment please check the testbed:

* https://github.com/osism/testbed/blob/main/environments/openstack/playbook-bootstrap-ceph-rgw.yml
* https://github.com/osism/testbed/blob/main/environments/ceph/configuration.yml#L225-L241
* https://github.com/osism/testbed/blob/main/environments/kolla/files/overlays/haproxy/services.d/haproxy.cfg#L9-L30

**Comment by linwalth** [comment]
Thank you very much!

**Comment by linwalth** [comment]
So the solution to this, as I understand it, is to build a custom playbook to roll it out in the fashion laid out above?

**Comment by berendt** [comment]
For now, yes. But that will be integrated properly in the near future.

**Comment by berendt** [comment]
Is available in stable/xena.
