### ISSUE TITLE
Major Bugreport Opensearch

### ISSUE THREAD

**Issue by rmueller-b1** [osism/issues#678]
Hello,
I found some bugs in the config of Opensearch:
In the container `kolla-ansible` is a file `roles/opensearch/templates/opensearch.yml.j2`. In that file is a variable defined called `network.host`. According to the official documentation of Opensearch that variable has to be called `network.bind_host`. 
The other issue is that the created config file is not loaded into the application. In the Opensearch container the config file is located at `/var/lib/kolla/config_files/opensearch.yml` but that file does not show up in the application that is running in the container. The config that will be loaded is a demo config and NOT the actual config needed for the cluster to get healthy.
Due to those issues the Opensearch cluster will never become healthy.

I found a workaround for the first issue: you have to create a file at `enviornments/kolla/files/overlay/opensearch/opensearch.yml` and insert the line `network.bind_host: "{{ 'api' | kolla_address | put_address_in_context('url') }}"`.

Kind regards.

**Comment by artificial-intelligence** [comment]
when I look at the [upstream docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#common-network-settings) I find `network.host`?

**Comment by rmueller-b1** [comment]
according to that documentation https://opensearch.org/docs/latest/tuning-your-cluster/index/ (step 3) it should be called `network.bind_host`.

**Comment by artificial-intelligence** [comment]
well that's not entirely correct, unfortunately:

> network.bind_host
    ([Static](https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html#static-cluster-setting), string) The network address(es) to which the node should bind in order to listen for incoming connections. Accepts a list of IP addresses, hostnames, and [special values](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#network-interface-values). **Defaults to the address given by `network.host`. Use this setting only if binding to multiple addresses or using different addresses for publishing and binding.**
    
also kolla-ansible set's this already to:

```yaml
network.host: "{{ 'api' | kolla_address | put_address_in_context('url') }}"
```

so it's not listening on localhost.

how did you check that the opensearch.yml path doesn't end up in the container and is not used?

**Comment by rmueller-b1** [comment]
The naming of the variable is not the main issue because there is an easy workaround.

To check for the config you have to check the process `java` that is running inside the container. When running `ps waux | grep java` as root in the container you will find that the file `/var/lib/kolla/config_files/opensearch.yml` is missing. That is the file that contains all the configs needed for the cluster.
You can also check the container logs and see that the config is never loaded into the conainer.

Btw. the loaded config is in `/etc/opensearch/opensearch.yml` and the only not commented part is after `######## Start OpenSearch Security Demo Configuration ########` at the end of the file.

Here is a part of our docker logs of the opensearch container:
```
[2023-09-20T12:55:18,644][INFO ][o.o.i.i.ManagedIndexCoordinator] [lbctr00lwq] Cache cluster manager node onClusterManager time: 1695214518644
[2023-09-20T12:55:18,651][WARN ][o.o.p.c.s.h.ConfigOverridesClusterSettingHandler] [lbctr00lwq] Config override setting update called with empty string. Ignoring.
[2023-09-20T12:55:18,655][INFO ][o.o.d.PeerFinder ] [lbctr00lwq] setting findPeersInterval to [1s] as node commission status = [true] for local node [{lbctr00lwq}{oJekmvwPSBez0_u_kL_9KA}{Npk50li7S5GS2CLfJqn_Qg}{127.0.0.1}{127.0.0.1:9300}{dimr}{shard_indexing_pressure_enabled=true}]
[2023-09-20T12:55:18,661][INFO ][o.o.h.AbstractHttpServerTransport] [lbctr00lwq] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
```
There you see that `localhost` is loaded but as we have a multiple node cluster, that is not correct.

**Comment by rmueller-b1** [comment]
We deployed opensearch via `osism-kolla deploy opensearch`. Due to the issue with the variable name I ran a reconfigure command 3 times today and I saw that the config file was changed successfully but the config used by the container did not change at all.

**Comment by berendt** [comment]
The final destination of the configuration files inside a running container is defined in the config.json file. In the case of open search the opensearch.yml in /etc/kolla/opensearch/opensearch.yml on the node itself will be available at /var/lib/kolla/config_files/opensearch.ym inside the container. During the start of the container the file will be copied from /var/lib/kolla/config_files/opensearch.yml to /etc/opensearch/opensearch.yml. /etc/opensearch/opensearch.yml is the default location for the opensearch service.

You can simply check this by adding some invalid YAML in /etc/kolla/opensearch/opensearch.yml. After a restart of the service you will get something like ``Exception in thread "main" SettingsException[Failed to load settings from [opensearch.yml]]; nested: ParsingException[Failed to parse object: expecting token of type [START_OBJECT] but found [VALUE_STRING]];`` in the logs.

```
# cat /etc/kolla/opensearch/config.json
{
    "command": "/usr/share/opensearch/bin/opensearch",
    "config_files": [
        {
            "source": "/var/lib/kolla/config_files/opensearch.yml",
            "dest": "/etc/opensearch/opensearch.yml",
            "owner": "opensearch",
            "perm": "0600"
        }
    ],
    "permissions": [
        {
            "path": "/var/lib/opensearch",
            "owner": "opensearch:opensearch",
            "recurse": true
        },
        {
            "path": "/var/log/kolla/opensearch",
            "owner": "opensearch:opensearch",
            "recurse": true
        }
    ]
}
```

On my local test system the network.host is working like expected:

```
dragon@manager:~$ sudo netstat -tulpen | grep 9200
tcp        0      0 192.168.16.254:9200     0.0.0.0:*               LISTEN      0          75105      31490/haproxy
tcp6       0      0 192.168.16.10:9200      :::*                    LISTEN      42490      3463572    691475/java
dragon@manager:~$ curl 192.168.16.10:9200
{
  "name" : "192.168.16.10",
  "cluster_name" : "kolla_logging",
  "cluster_uuid" : "PiUgww_OTHiTV7d1sEmZaw",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.9.0",
    "build_type" : "deb",
    "build_hash" : "1164221ee2b8ba3560f0ff492309867beea28433",
    "build_date" : "2023-07-18T21:22:32.045158091Z",
    "build_snapshot" : false,
    "lucene_version" : "9.7.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

**Comment by berendt** [comment]
Btw. please do not use the deprecated scripts like osism-kolla. They will be soon removed. Only use the osism CLI. E.g. to deploy the opensearch service use osism apply opensearch.

**Comment by berendt** [comment]
New docs for the configuration process in Kolla: https://osism.github.io/docs/guides/configuration-guides/openstack/#how-does-the-configuration-get-into-services

**Comment by berendt** [comment]
I think that's done. Process is documented.
