### ISSUE TITLE
6.0.0b {{ docker_restart_policy_retry }} is 0 (ByZeroDivisionException)

### ISSUE THREAD

**Issue by chrisschwa** [osism/issues#682]
In the Upgrade from 5.3.0 to 6.0.0b there is a bug where the 01-Kolla Defaults {{ docker_restart_policy_retry }} is overriden by 099 Kolla Defaults which sets the Value to 0. 
This will bring the "apply common" Step to fail because it will be a ZeroDivisionException.

**Comment by berendt** [comment]
Missing sync of `environments/manager/images.yml`. I tried to improve the docs for the manager upgrade.

**Comment by berendt** [comment]
That's documented and fixed.
