### ISSUE TITLE
6.0.0 docker upgrade restarts all containers - is it by purpose?

### ISSUE THREAD

**Issue by maliblatt** [osism/issues#683]
we successfully upgraded one of our environments to 6.0.0. In general I can say the upgrade was very fluffy and we did not encounter any problems.
But we recognized one thing, when upgrading the docker version with `osism apply --action upgrade docker` every running container on every host bas been restarted. In the past we could only see the ceph related containers restarting, but this time also all of the kolla containers did a restart.

Is that by purpose? Is it somehow configurable? 

In our case we have to do the restarts later again after applying outstanding os upgrades together with a reboot of every machine so it would be nice if the docker upgrade would not restart anything.

**Comment by fkr** [comment]
> I think it's a good idea to run osism apply docker with serial = 1 to avoid the restart of e.g. all RabbitMQ containers at once.

does it make sense to track that as a best practice somewhere?

**Comment by berendt** [comment]
Looks like there is already a parameter to avoid restarts during an upgrade: Set ``docker_allow_restart: false`` in ``environments/configuration.yml``.

I will add some Docker upgrade notes to the new documentation. The parameter itself is already documented in the Ansible role docs.

**Comment by berendt** [comment]
Other option: Set ``docker_ignore_restart_groupname`` to ``generic``. Hosts in the ``docker_ignore_restart_groupname`` will not be restarted.

**Comment by berendt** [comment]
@maliblatt I tried to explain the restart behaviour here: https://osism.github.io/docs/guides/upgrade-guides/docker#restart-behaviour. Please have a look on it.

**Comment by maliblatt** [comment]
Thanks @berendt for the new documentation, that is very helpful.
But even with all settings set to docker_allow_restart=false our containers get restarted, but we can handle it with the serial=1 option. Also testing directly on a machine with live-restore on true and manual docker minor upgrade results in restarting every container, so that seems to be docker thing and not a problem in OSISM.

**Comment by berendt** [comment]
I think it is because the containerd service  is still in the docker role and is not pinned. The containerd package is only locked so that it is only updated when the role is executed.

I had once started to move runc and conatinerd into their own roles and remove them from the docker role so that you can simply prevent the restarts of it and also pin the versions.

I think that should be finalized so that we can handle this better in the future.
