### ISSUE TITLE
inventory: use netplan template

### ISSUE THREAD

**Issue by killermoehre** [osism/issues#702]
Hi,

at $customer we have many different host_vars files, which only differ in the assigned IP addresses.

Is there a way to use some netplan template file instead of duplicating code all over the place?

**Comment by berendt** [comment]
I think you should use group_vars for this purpose.

Have a look at https://github.com/osism/testbed/tree/main/inventory/group_vars for one example.

We work there with a node_id (this one is defined in the host_vars of each host).

**Comment by killermoehre** [comment]
I was able to actually setup your idea with the node_id. Really nice idea.

Maybe you should document more prominent that `group_vars/all.yaml` is *not* parsed, but one has to use `group_vars/generic.yaml`.

**Comment by berendt** [comment]
> I was able to actually setup your idea with the node_id. Really nice idea.

Will add this approach to the docs.

> Maybe you should document more prominent that `group_vars/all.yaml` is _not_ parsed, but one has to use `group_vars/generic.yaml`.

This is now documented. Sorry for the confusions. This is special in the OSISM framework.
