### ISSUE TITLE
docker_live_restore breaks docker

### ISSUE THREAD

**Issue by MarRio81** [osism/issues#703]
Hi,

If we use docker_live_restore: true in configuration/environments.yml Jinja2 interprets this as "real bool" and writes it with a capitalized T to /etc/docker/daemon.json. This prevents docker from starting.

Oct 05 14:50:52 compute1-dev2-az1 dockerd[3031572]: unable to configure the Docker daemon with file /etc/docker/daemon.json: invalid character 'T' looking for beginning of value
Oct 05 14:50:52 compute1-dev2-az1 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE

I think you should be aware of this: https://github.com/ansible/ansible/issues/63510#issuecomment-542337629

Also the Documentation (https://osism.github.io/docs/guides/upgrade-guides/docker) says, that you set live-restore by default to true but it isn't set in /etc/docker/daemon.json until we define it in configuration/environments.yml.

**Comment by berendt** [comment]
It's a string by default: https://github.com/osism/ansible-collection-services/blob/main/roles/docker/defaults/main.yml#L9

On one of the test environments here it's true in the daemon.json after the deployment:

```
$ cat /etc/docker/daemon.json
{
    "debug": false,
    "experimental": false,
    "hosts": ["unix:///var/run/docker.sock"],
    "insecure-registries": [],
    "ipv6": false,
    "live-restore": true,
    "log-driver": "json-file",
    "log-level": "info",
    "log-opts": {
      "max-file": "3",
      "max-size": "10m"
    },
    "registry-mirrors": [],
    "storage-driver": "overlay2",
    "default-runtime": "runc"
}
```
