### ISSUE TITLE
network connection to workload not working after osism apply docker

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#704]
Containers seem be running again but instances are not reachable via network.

**Comment by Nils98Ar** [comment]
Re-deploying rabbitmq with `osism apply rabbitmq` and restarting all rabbitmq client containers solved it.
Maybe the `osism apply docker -l 'docker:!manager'` restarted the controllers to fast in a row?

Was probably related to neutron security groups queue in RabbitMQ.
```
operation basic.consume caused a channel exception not_found: no queue 'neutron-vo-SecurityGroupRule-1.2.compute02' in vhost '/'.
```

**Comment by Nils98Ar** [comment]
> Maybe the `osism apply docker -l 'docker:!manager'` restarted the containers on each controller (namely rabbitmq) to fast in a row?

I leave the issue open for now to check this.

**Comment by berendt** [comment]
Actually, there is nothing more to be done here. I have documented that it is not a good idea to change the default of serial for the Docker play.

**Comment by Nils98Ar** [comment]
We have not changed the serial... does the play wait for the containers to be restarted and healthy?

**Comment by berendt** [comment]
The play goes through host by host and does not currently wait for containers. It's a good idea though, will build this in.

**Comment by Nils98Ar** [comment]
> The play goes through host by host and does not currently wait for containers. It's a good idea though, will build this in.

@berendt Have you built this in in the meantime?
