### ISSUE TITLE
osism validate kernel-version still expects the Ubuntu 20.04 Kernel

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#705]
```
dragon@manager01:~$ osism validate kernel-version

PLAY [Run kernel_version validator] ********************************************

TASK [osism.validations.kernel_version : Check kernel version] *****************
fatal: [manager01.xyz.cloud]: FAILED! => {"changed": false, "msg": "5.4 does not match configured kernel_version 5.15.0-79-generic"}
```

**Comment by berendt** [comment]
You have to set ``kernel_version_expected`` in ``environments/configuration.yml``. We do not enforce specific Kernel series at the moment. Because of this you have to track the expected kernel version on your own.

**Comment by Nils98Ar** [comment]
So the default is not maintained? Is it expected that we have
- 5.10 here: https://github.com/osism/ansible-collection-validations/blob/8b9a5a15efc282edfa524bdb7ad34d453d7b130f/molecule/delegated/vars/kernel_version.yml#L2
- and here 5.4 https://github.com/osism/ansible-collection-validations/blob/8b9a5a15efc282edfa524bdb7ad34d453d7b130f/roles/kernel_version/defaults/main.yml#L2

?

I would expect that the Ubuntu 22.04 kernel (5.15) is default.

**Comment by berendt** [comment]
The default is simply set. Feel free to open a PR to change it to the default kernel of Ubuntu 22.04. But since you can also use HWE etc., the version there should not give the impression that exactly this version is necessary.

**Comment by berendt** [comment]
That's fixed. New default is 6.2.
