### ISSUE TITLE
osism-update-manager error

### ISSUE THREAD

**Issue by linwalth** [osism/issues#71]
the osism-update-manager script throws an error when i run it, even though it does not fail ultimately.

ERROR! - command /usr/bin/git checkout master failed in directory /root/.ansible/tmp/ansible-local-2289012t_6iusc_/tmpqaazqox6/ansible-collection-services (rc=1) - error: pathspec 'master' did not match any file(s) known to git

i suspect it to be linked to this var in the script: MANAGER_VERSION=${MANAGER_VERSION:-master} 

which in turn is called here:

ansible-galaxy collection install git+https://github.com/osism/ansible-collection-services,$MANAGER_VERSION

as this (https://github.com/osism/ansible-collection-services) repository's master branch has been renamed to main, that may be the cause of the issue at hand here.

edit: as suspected, it does not throw this error when i change master to main.

**Comment by linwalth** [comment]
addendum: now i cant roll out further configuration, because the playbooks are missing in the manager container.

`ERROR! the role 'osism.operator' was not found in /ansible/roles:/ansible/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/ansible`

**Comment by berendt** [comment]
Please manually sync the file with https://github.com/osism/ansible-collection-services/blob/main/roles/manager/templates/wrapper/osism-update-manager.j2 or use the run.sh script inside the environments/manager directory as an alternative way to update the manager.
