### ISSUE TITLE
testbed make prepare failes

### ISSUE THREAD

**Issue by maliblatt** [osism/issues#715]
What am I doing wrong when trying to prepare the testbed installation:

```:~/src/github.com/osism/testbed$ make prepare
ansible-playbook -i localhost, ansible/check-local-versions.yml

PLAY [Check local versions] ******************************************************************************************************************************************************************************

TASK [Fail if ansible-core version is lower than 2.15.0] *************************************************************************************************************************************************
skipping: [localhost]

TASK [Get terraform version] *****************************************************************************************************************************************************************************
ok: [localhost]

TASK [Fail if terraform version is lower than 1.5.0] *****************************************************************************************************************************************************
skipping: [localhost]

PLAY RECAP ***********************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   

REPOSITORY_SERVER=$(yq '.repository_server' playbooks/vars/repositories.yml)
TESTBED_PATH=$(yq '.repositories.testbed.path' playbooks/vars/repositories.yml)
TESTBED_REPO=$(yq '.repositories.testbed.repo' playbooks/vars/repositories.yml)
mkdir -p $(dirname )
dirname: missing operand
Try 'dirname --help' for more information.
mkdir: missing operand
Try 'mkdir --help' for more information.
make: *** [Makefile:86: prepare] Error 1```

local installed versions:
Terraform v1.5.0
ansible 8.5.0

**Comment by maliblatt** [comment]
when going back to commit 2eeee1f8292fccc454ab22e7496993c520436948 everything works as expected :-)

**Comment by berendt** [comment]
It's then probably related to d7ac36c6215d2e079bf15928b2a3ed038fe44081.

**Comment by reqa** [comment]
For me, the commit https://github.com/osism/testbed/pull/1797 didn't fix the issue. I still get
```
mkdir -p $(dirname )
dirname: missing operand
```
The ubuntu host I used does have neither "`shell`" nor "`yq`". Maybe this dependency needs to be addressed. Make prepare is one of the first commands mentioned in the quickstart guide.

**Comment by berendt** [comment]
@reqa You have to install yq: https://osism.github.io/docs/advanced-guides/testbed#software

**Comment by reqa** [comment]
I didn't see that referenced in https://docs.osism.tech/testbed/quickstart.html

**Comment by berendt** [comment]
@reqa Those docs are archived. Please note the box on the landing page: https://docs.osism.tech. I will check if it is possible to add a box or a header on all pages. New docs are here: https://osism.github.io/docs/intro/

**Comment by reqa** [comment]
Ok, `yq` is clear, what is this `shell` command? Googling `Command 'shell' not found, did you mean:` doesn't give any clues. If it's supposed to improve portability, it didn't.

**Comment by berendt** [comment]
Can you try it without the shell in front?

**Comment by reqa** [comment]
Well, that will work for sure, but I've just reverted to `19484b7330ad30e3abea7e174479e5e352f792b7` (the 6.0.0 commit and started re-deploying that, so can only try at some later point.

**Comment by reqa** [comment]
Btw, git tags would be great.

**Comment by berendt** [comment]
As the testbed supports different versions at the same time, there are no tags here.

**Comment by berendt** [comment]
shell is a Makefile funktion, not a command: https://www.gnu.org/software/make/manual/html_node/Shell-Function.html

What kind of make are you using?

**Comment by reqa** [comment]
Ah, ok, thanks for the explanation, didn't know!

**Comment by fkr** [comment]
thanks @berendt for testbed/#1843 - 'shell' invokes the shell of the current user as such behaviour is unpredictable and due to the shell the user has.

**Comment by reqa** [comment]
I should be noted that the minimal required version if yq is `4.18.1`. As a consequence, the Ubuntu/Debian package from `ppa:rmescandon/yq` doesn't cut it currently, otherwise this happens::
```
root@ubuntu:~/src/github.com/osism/testbed# yq -V
yq (https://github.com/mikefarah/yq/) version 4.16.2

root@ubuntu:~/src/github.com/osism/testbed# OS_CLOUD=gx-scs make prepare ENVIRONMENT=gx-scs 
Error: unknown command ".repositories.ansible-collection-commons.path" for "yq"
Run 'yq --help' for usage.
Error: unknown command ".repositories.ansible-collection-commons.repo" for "yq"
Run 'yq --help' for usage.
Error: unknown command ".repositories.ansible-collection-services.path" for "yq"
Run 'yq --help' for usage.
Error: unknown command ".repositories.ansible-collection-services.repo" for "yq"
Run 'yq --help' for usage.
Error: unknown command ".repository_server" for "yq"
Run 'yq --help' for usage.
Error: unknown command ".repositories.terraform-base.path" for "yq"
Run 'yq --help' for usage.
Error: unknown command ".repositories.terraform-base.repo" for "yq"
Run 'yq --help' for usage.
Error: unknown command ".repositories.testbed.path" for "yq"
Run 'yq --help' for usage.
Error: unknown command ".repositories.testbed.repo" for "yq"
Run 'yq --help' for usage.
ansible-playbook -i localhost, ansible/check-local-versions.yml
```

Installing via snap worked though (currently at v4.35.2).
