### ISSUE TITLE
Possibility to define manager images with one variable

### ISSUE THREAD

**Issue by chschilling** [osism/issues#724]
At the moment, if we want to update our whole environment, we have to set image versions in `environments/manager/images.yml`  manually to  get the manager stuff itself updated.

It would be nice if that could be handled like the rest of the images, which are mapped via "manager_version"

if we keep the images file "dummy empty", latest versions are applied which shouldn't be right.

Greetings,

Christian

**Comment by berendt** [comment]
That's already possible with ``gilt``. Set ``manager_version`` and run ``MANAGER_VERSION=x gilt overlay`` (2 times) afterwards.

https://osism.github.io/docs/guides/configuration-guides/manager#stable-release

**Comment by berendt** [comment]
@chschilling Does that work? Then I would close this.

It is not possible via manager_version because we have different versions of the individual images. These are defined in osism/release (https://github.com/osism/release/blob/main/6.0.1/base.yml) and are synced in environments/manager/images.yml.

**Comment by chschilling** [comment]
Thanks for that clarification.
Is it possible to create some kind of validation, that the images.yml is on the correct state?
We had that issue that, even with two times gilt, somehow that file has not been updated.

Some Kind of check would be nice here.

Greets,
Christian

**Comment by berendt** [comment]
> Thanks for that clarification. Is it possible to create some kind of validation, that the images.yml is on the correct state? We had that issue that, even with two times gilt, somehow that file has not been updated.

How did you do it? Looks like you hit some bug then. This gilt thing simply calls a few Python scripts to generate the images.yml. I could build a separate python script to throw the images.yml into and check if the generated versions match. This could then be built into the osism.services.manager role and would be an opt-in as the role then needs to communicate with Github.

**Comment by chschilling** [comment]
Hey, sorry for not responiding-

unfortunatly I can't say how we did it correctly - Thought about simply two times running gilt overlay via cli.
Thank you for adding a script for validation
