### ISSUE TITLE
R6 Upgrade - Horizon has wrong python paths (again!)

### ISSUE THREAD

**Issue by flyersa** [osism/issues#725]
Like last upgrade you have the same bug again but in reverse,

horizon container is broken. It demands /var/lib/python3.8 paths but the new containers have 3.10 

Fix the container please to point the apache configuration to 3.10 paths

**Comment by flyersa** [comment]
and btw it is a riddle to me how this can happen all over again, We had the same issue last time already. Stop doing your damn testing with the testbed which as a completly different deployment scheme then any normal user of this product. You would catch this stuff yourself if you use your own toolchain and normal deployment process or environments!

**Comment by berendt** [comment]
I just did a fresh Cloud in a Box deployment with OSISM 6.0.1 and the Horizon works there without any problems. What was the problem earlier with Python 3.8?

**Comment by berendt** [comment]
I found the patch in Zed (https://github.com/osism/container-image-kolla-ansible/blob/main/patches/zed/horizon-use-static-python-version.patch). It works like expected as we dropped the patch in the 2023.1 builds because of this note in the SCS R4 notes (https://github.com/SovereignCloudStack/release-notes/blob/main/Release4.md):

```
For new deployments of the IaaS reference implementation Ubuntu 22.04 is recommended while existing installations can be upgraded to R4 while staying on Ubuntu 20.04. With Release 5, upgrading to Ubuntu 22.04 will be required.
```

**Comment by flyersa** [comment]
Well what can i say. It is ubuntu 22.04 

```
/home/sxp-ekern# cat /etc/issue
Ubuntu 22.04.3 LTS \n \l
```

```
/home/sxp-ekern# docker ps |grep horizon
36c9a818cb5f   quay.io/osism/horizon:23.1.1.20230919                            "dumb-init --single-…"   24 hours ago   Up 24 hours (healthy)             horizon

```

stil in conf-enabled/000-default.conf in the horizon container by default it is pointing to python3.8 for WSCGI 

`WSGIScriptAlias / /var/lib/kolla/venv/lib/python3.8/site-packages/openstack_dashboard/wsgi.py`

**Comment by berendt** [comment]
This is the used template: https://github.com/openstack/kolla-ansible/blob/stable/2023.1/ansible/roles/horizon/templates/horizon.conf.j2

``distro_python_version`` is the used Python version. This is 3.10 on Ubuntu 22.04 (Python 3.10.12 at the moment).

On our Ubuntu 22.04 test system we than have ``WSGIScriptAlias / /var/lib/kolla/venv/lib/python3.10/site-packages/openstack_dashboard/wsgi.py`` in the generated horizon.conf file.

Not sure why it does not work on your local environment. Please use a modified horizon.conf in your environments/kolla/files/overlays for the moment to fix the issue. This way you do not have to edit anything inside the running container.

For 6.0.1: https://release.osism.tech/notes/6.0.1.html. Was necessary because of a bug in the Neutron/Octavia/OVN integration.

**Comment by berendt** [comment]
Double checked the behaviour.

It depends on the value of ``kolla_base_distro`` (https://github.com/osism/defaults/blob/main/all/099-kolla.yml#L25). It's ``ubuntu`` in our case.

The definition of  ``distro_python_version = "{{ distro_python_version_map[kolla_base_distro] }}" (https://github.com/osism/defaults/blob/main/all/001-kolla-defaults.yml#L1185).

This is ``distro_python_version_map``: (https://github.com/osism/defaults/blob/main/all/001-kolla-defaults.yml#L1171-L1176)

```
distro_python_version_map: {
  "centos": "3.9",
  "debian": "3.9",
  "rocky": "3.9",
  "ubuntu": "3.10"
}
```

Please add the following play to ``environments/custom/playbook-gh725.yml`` and run ``osism apply -e custom gh725

```
---
- name: Debug GH725
  hosts: all
  gather_facts: true

  tasks:
    - debug: var=kolla_base_distro
    - debug: var=distro_python_version
```

Looks like this on the test system:

```
PLAY [Debug GH725] *************************************************************

TASK [debug] *******************************************************************
Tuesday 24 October 2023  13:07:24 +0000 (0:00:00.641)       0:00:00.641 *******
ok: [manager.systems.in-a-box.cloud] => {
    "kolla_base_distro": "ubuntu"
}

TASK [debug] *******************************************************************
Tuesday 24 October 2023  13:07:25 +0000 (0:00:00.615)       0:00:01.256 *******
ok: [manager.systems.in-a-box.cloud] => {
    "distro_python_version": "3.10"
}

PLAY RECAP *********************************************************************
manager.systems.in-a-box.cloud : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by flyersa** [comment]
i did this and it outputs for all hosts:

```
"kolla_base_distro": "ubuntu"
"distro_python_version": "3.10"
```

**Comment by berendt** [comment]
This is the template inside the container image. When you have 3.8 instead of 3.10 in the parsed template you overwrite distro_python_version somewhere in environments/kolla or environments in the configuration repository. That's the only way to end up with a 3.8 in this line in the parsed template when you have distro_python_version in the host facts.

```
dragon@53155d467816:~/roles/horizon/templates$ cat horizon.conf.j2
{% set python_path = '/var/lib/kolla/venv/lib/python' + distro_python_version + '/site-packages' %}

{% if horizon_enable_tls_backend | bool %}
{% if kolla_base_distro in ['centos', 'rocky']  %}
LoadModule ssl_module /usr/lib64/httpd/modules/mod_ssl.so
{% else %}
LoadModule ssl_module /usr/lib/apache2/modules/mod_ssl.so
{% endif %}
{% endif %}
Listen {{ api_interface_address | put_address_in_context('url') }}:{{ horizon_listen_port }}

ServerSignature Off
ServerTokens Prod
TraceEnable off

<VirtualHost {{ api_interface_address }}:{{ horizon_listen_port }}>
    LogLevel warn
    ErrorLog /var/log/kolla/horizon/horizon.log
    LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b %D \"%{Referer}i\" \"%{User-Agent}i\"" logformat
    CustomLog /var/log/kolla/horizon/horizon-access.log logformat

    WSGIScriptReloading On
    WSGIDaemonProcess horizon-http processes={{ horizon_wsgi_processes }} threads={{ horizon_wsgi_threads }} user=horizon group=horizon display-name=horizon
    WSGIProcessGroup horizon-http
    WSGIScriptAlias / {{ python_path }}/openstack_dashboard/wsgi.py
    WSGIPassAuthorization On
    WSGIApplicationGroup %{GLOBAL}

    <Location "/">
        Require all granted
    </Location>

    <Location "/server-status">
        Require local
    </Location>

    Alias /static {{ python_path }}/static
    <Location "/static">
        SetHandler None
    </Location>

{% if horizon_enable_tls_backend | bool %}
    SSLEngine On
    SSLCertificateFile /etc/horizon/certs/horizon-cert.pem
    SSLCertificateKeyFile /etc/horizon/certs/horizon-key.pem
{% endif %}
{% if horizon_httpd_limitrequestbody is defined %}
    LimitRequestBody {{ horizon_httpd_limitrequestbody }}
{% endif %}
</VirtualHost>

<IfModule mod_deflate.c>
    # Compress HTML, CSS, JavaScript, Json, Text, XML and fonts
    AddOutputFilterByType DEFLATE application/javascript
    AddOutputFilterByType DEFLATE application/json
    AddOutputFilterByType DEFLATE application/rss+xml
    AddOutputFilterByType DEFLATE application/vnd.ms-fontobject
    AddOutputFilterByType DEFLATE application/x-font
    AddOutputFilterByType DEFLATE application/x-font-opentype
    AddOutputFilterByType DEFLATE application/x-font-otf
    AddOutputFilterByType DEFLATE application/x-font-truetype
    AddOutputFilterByType DEFLATE application/x-font-ttf
    AddOutputFilterByType DEFLATE application/x-javascript
    AddOutputFilterByType DEFLATE application/xhtml+xml
    AddOutputFilterByType DEFLATE application/xml
    AddOutputFilterByType DEFLATE font/opentype
    AddOutputFilterByType DEFLATE font/otf
    AddOutputFilterByType DEFLATE font/ttf
    AddOutputFilterByType DEFLATE image/svg+xml
    AddOutputFilterByType DEFLATE image/x-icon
    AddOutputFilterByType DEFLATE text/css
    AddOutputFilterByType DEFLATE text/html
    AddOutputFilterByType DEFLATE text/javascript
    AddOutputFilterByType DEFLATE text/plain
    AddOutputFilterByType DEFLATE text/xml
</IfModule>

<IfModule mod_expires.c>
    <Filesmatch "\.(jpg|jpeg|png|gif|js|css|swf|ico|woff)$">
        ExpiresActive on
        ExpiresDefault "access plus 1 month"
        ExpiresByType application/javascript "access plus 1 year"
        ExpiresByType text/css "access plus 1 year"
        ExpiresByType image/x-ico "access plus 1 year"
        ExpiresByType image/jpg "access plus 1 year"
        ExpiresByType image/jpeg "access plus 1 year"
        ExpiresByType image/gif "access plus 1 year"
        ExpiresByType image/png "access plus 1 year"
        Header merge Cache-Control public
        Header unset ETag
    </Filesmatch>
</IfModule>
```

**Comment by flyersa** [comment]
i get this but stil it is a fact and we observed this behavior on 2 different upgrades now. And it is not overriden anywhere.

```
/opt/configuration# fgrep -R distro_python *
environments/custom/playbook-gh725.yml:    - debug: var=distro_python_version
```

same with searching for 3.8 or something. We do another upgrade tomorrow then lets see.

**Comment by flyersa** [comment]
Our upgrade today did not show the issue with Horizon and the python paths. I really expect some issue with the toolbox/ansible containers not being up2date before the rollout.
