### ISSUE TITLE
missing vitrage prometheus_conf.yml in osism/kolla-operations

### ISSUE THREAD

**Issue by linwalth** [osism/issues#73]
We are deploying Vitrage via OSISM for RCA.
Vitrage needs a prometheus.yml to deploy correctly. Since we are using kolla-operations it would be good to have a prometheus_conf.yml to mirror the prometheus rules already present in kolla-operations.

**Comment by berendt** [comment]
We currently do not support Vitrage as a service in OSISM and do not provide images and integration for it.
