### ISSUE TITLE
`osism log opensearch` requires TLS endpoint

### ISSUE THREAD

**Issue by killermoehre** [osism/issues#731]
Hi,

as the title says, `osism log opensearch` requires a TLS enabled endpoint.

Now, at $customer, the api-internal endpoint configured is _not_ TLS secured, but plain text HTTP.

Is there a way to configure `osism log opensearch` to not expect TLS? Especially since the `opensearch` provider can't listen on the public interface.

BR  
Silvio

**Comment by berendt** [comment]
It would be better to also use TLS for internal services. But it should be no big deal to allow both in the client.

**Comment by berendt** [comment]
@killermoehre You can now set `opensearch_protocol: http` in `environments/manager/configuration.yml`. Run `osism update manager` afterwards to reconfigure & update the manager service.

You have to wait for https://github.com/osism/python-osism/pull/661. New image will be available in appr. 1 hour.

Is then included in the stable release as of OSISM 6.1.0.

**Comment by killermoehre** [comment]
@berendt so there won't be a backport to 6.0.0, right? I *have to* update to 6.1.0 for this feature?

**Comment by berendt** [comment]
We do not do any backports. We have a point in time release model, not a stable branch based release model. This means that we tag at a given time all repositories with the next tag and list all used versions in https://github.com/osism/release and https://github.com/osism/sbom. This is then a release. We do that even if a hotfix is necessary. This is not implemented as a backport, we add a new release for this. As an example: In interaction with OVN, Neutron and Octavia there was a problem in 6.0.0. We have therefore made a 6.0.1 but only the version of the neutron-server image has changed. Plus the version of the manager images like kolla-ansible or osism-ansible.

While updating the manager itself to 6.1.0 does not mean that you have to also update all included services (OpenStack, Ceph, ..). You can also update the manager to 6.1.0 and leave everything else at 6.0.0.

We can make a call if there is any confusion about how we do a release and how exactly to apply it.

**Comment by berendt** [comment]
Started with the import of the release process documentation at https://osism.github.io/docs/advanced-guides/developer-guide/#how-do-you-do-a-release

**Comment by killermoehre** [comment]
> We do not do any backports. We have a point in time release model, not a stable branch based release model. This means that we tag at a given time all repositories with the next tag and list all used versions in https://github.com/osism/release and https://github.com/osism/sbom. This is then a release. We do that even if a hotfix is necessary. This is not implemented as a backport, we add a new release for this. As an example: In interaction with OVN, Neutron and Octavia there was a problem in 6.0.0. We have therefore made a 6.0.1 but only the version of the neutron-server image has changed. Plus the version of the manager images like kolla-ansible or osism-ansible.
> 
> While updating the manager itself to 6.1.0 does not mean that you have to also update all included services (OpenStack, Ceph, ..). You can also update the manager to 6.1.0 and leave everything else at 6.0.0.
> 
> We can make a call if there is any confusion about how we do a release and how exactly to apply it.

No confusion here, just wanna make sure I understand the procedure.

I think we will just add TLS to the internal endpoint. Probably the better solution in general.
