### ISSUE TITLE
osism client runs into 300 second timeout

### ISSUE THREAD

**Issue by maliblatt** [osism/issues#746]
While upgrading one of our larger environments to OSISM 6.0.1, we ran into the problem, that several tasks which needs more than 300 seconds to finish, were processed until the end, but the user gets a timeout message from the osismclient, for example:

`RUNNING HANDLER [nova-cell : Restart nova-libvirt container] *******************`
`2023-11-06 12:19:43 | INFO     | No further output after 300 seconds. Therefore finish.`
`dragon@manager01:/opt/configuration$ `

the task will continue in the kolla-ansible container, but the user could be irritated and does not know if the task will continue.

Is that timeout configurable somewhere?

**Comment by berendt** [comment]
The whole implementation with Redis PubSub is not so great. I have completely rewritten this in Redis Streams and this is already available from 6.1.0. I'm planning a release after the SCS hackathon this week. Are you in Dresden? Then we can take another look there on this topic.

**Comment by maliblatt** [comment]
sadly I am not in dresden. But if you have already prepared something in 6.1.0 it will be fine for me to wait until then and take a look into it. Thanks!

**Comment by berendt** [comment]
This one: https://github.com/osism/python-osism/commit/3cb213d9807b1f1d4fa1af8e548c1d835d8ae5f8

At the moment it looks more stable than with the pub sub approach.
