### ISSUE TITLE
Add python-black job to all repositories that contain Python files

### ISSUE THREAD

**Issue by berendt** [osism/issues#753]
As check + periodic-daily job.

**Comment by sbstnnmnn** [comment]
|  Role  |  PR | Note  |
| -- | -- | -- |
|  ``ansible-collection-commons`` | #528 | :heavy_check_mark: |
| ``ansible-collection-services`` | #1184 | :heavy_check_mark: |
| … | | |

**Comment by sbstnnmnn** [comment]
@berendt documentation, sbom and python-harborclient are still missing and may not require Python black, otherwise I should have caught all repositories with Python files.

**Comment by berendt** [comment]
Documentation can be skipped.

We should add it to python-harborclient. But I think we can archive python-harborclient in the near future and can use some Go or Rust based client.
