### ISSUE TITLE
osism apply <kolla service> not working / wrong ansible-playbook usage

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#764]
For some reason wrong arguments are passed to the `ansible-playbook` command.

E.g.:

```
dragon@manager01:/opt/configuration$ osism apply neutron
usage: ansible-playbook [-h] [--version] [-v] [--private-key PRIVATE_KEY_FILE]
                        [-u REMOTE_USER] [-c CONNECTION] [-T TIMEOUT]
                        [--ssh-common-args SSH_COMMON_ARGS]
                        [--sftp-extra-args SFTP_EXTRA_ARGS]
                        [--scp-extra-args SCP_EXTRA_ARGS]
                        [--ssh-extra-args SSH_EXTRA_ARGS]
                        [-k | --connection-password-file CONNECTION_PASSWORD_FILE]
```

**Comment by Nils98Ar** [comment]
I've added some debug output to the `/run.sh` in the `kolla-ansible` container. In the end the `ansible-playbook` command returned:
`ERROR! Invalid extra vars data supplied. '@/opt/configuration/environments/kolla/images.yml' could not be made into a dictionary`

Turned out that the dummy entry in the `images.yml` was commented out, commenting it in fixed it:
```
---
# Dummy variable to avoid error because ansible does not recognize the
# file as a good configuration file when no variable in it.
dummy:
```

@berendt Could we maybe make osismclient output the stderr from ansible-playbook in kolla-ansible?

**Comment by berendt** [comment]
This should now be the case so that STDERR is also visible.
