### ISSUE TITLE
Make Cookiecutter hook failure aware

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#766]
Hi,

I would like you to add failure handling to  https://github.com/osism/cfg-cookiecutter/blob/main/hooks/post_gen_project.sh.

Currently any error within the hook is ignored except for the last.

One solution might be in the top:
```
set -ueo pipefail
```

Kind regards,
Andre.

**Comment by berendt** [comment]
Closed by af49e85e0e74e876146b8c900efdf27b02d1674c.
