### ISSUE TITLE
Creating ceph keyring for manila

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#768]
What should I run to make ceph-ansible create the manila user and place the keyring in /etc/ceph on der ceph mons/mgrs?

Currently there are only keyrings for the other OpenStack services.

After that I would run `osism apply ceph-fetch-keys` etc.

**Comment by Nils98Ar** [comment]
I think this part should be done by some ansible playbook?
https://docs.openstack.org/manila/latest/admin/cephfs_driver.html#authorizing-the-driver-to-communicate-with-ceph

**Comment by Nils98Ar** [comment]
I have now done this manually on the first ceph mon node:
```
dragon@mon01:~$ docker exec ceph-mon-mon01 ceph auth get-or-create client.manila -o /etc/ceph/ceph.client.manila.keyring mgr 'allow rw' mon 'allow r'
```

And then on the manager:
```
dragon@manager01:~$ osism apply copy-ceph-keys
```

After that the manila deployment with native cephfs backend finished successfully.

**Comment by berendt** [comment]
I think you can use `osism apply ceph-fetch-keys` to fetch all defined keys from the Ceph cluster.

**Comment by berendt** [comment]
Yes. But I added a dedicated play for the management of the Ceph pools to be able to manage them in the future independent of the ceph-osd play: https://github.com/osism/container-image-ceph-ansible/blob/main/files/playbooks/quincy/ceph-pools.yml

Will be available in the next OSISM release.

**Comment by Nils98Ar** [comment]
And this one can create all needed ceph users für OpenStack?

I am asking myself which play would normally create the OpenStack ceph users and keyring files and why the manila keyring file wasn't there in our case. Is it maybe dependent on the kolla configuration?
