### ISSUE TITLE
investigate kernel/qemu issue on compute nodes

### ISSUE THREAD

**Issue by artificial-intelligence** [osism/issues#772]
dmesg:

```
12345[3579432.962837] x86/split lock detection: #AC: CPU 0/KVM/3324070 took a split_lock trap at address: 0xfffff805742147bf
```

currently found links/information:

workaround from kernel 6.2. might be to set:

```
kernel.split_lock_mitigate=0
```

for older kernels this might mitigate this issue (everything here is currently untested!):

```
split_lock_detect=off
```

**Comment by artificial-intelligence** [comment]
investigating:

https://gitlab.com/qemu-project/qemu/-/issues/1069

**Comment by berendt** [comment]
1. Upgrade to linux-generic-hwe-22.04 (Linux Kernel 6.2.0)

**Comment by artificial-intelligence** [comment]
as was pointed out this is more of an application issue, the mitigation from the kernel side is documented above. in the general case the application should be fixed.
