### ISSUE TITLE
"osism apply bootstrap" sometimes does not install Docker and still returns successful

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#785]
Hi,

today i stumbled in the problem that "osism apply bootstrap" sometimes fails for some hosts to install Docker. However, the returncode is still 0. 

This leads to problems in the later installation process when applying services fail due to missing Docker module.

Kind regards,
André.

**Comment by nerdicbynature** [comment]
Just as a note: On our side this happens everytime that some nodes (20%) are not configured properly

**Comment by berendt** [comment]
Are there any logs of the failed task in the osism.services.docker role?

**Comment by nerdicbynature** [comment]
Unfortunately not. Logs are not persisted. Maybe its related to slow package installation issue we face on some node that may lead running into a timeout on osismclient side. Maybe it just disconnects after some time regardless of the result?

**Comment by berendt** [comment]
Probably fixed. Please re-open if this still happens.
