### ISSUE TITLE
Duplicate keys for ceph-rgw

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#786]
Hi,

Ceph-RGW configuration creates duplicate keys.

As from Cookiecutter (https://github.com/osism/cfg-cookiecutter/blob/5630c1cc78ce8bb78084fff7156b44a7c6d76ef2/%7B%7Bcookiecutter.project_name%7D%7D/environments/kolla/configuration.yml#L44) this comes:
```
enable_ceph_rgw: true
enable_ceph_rgw_keystone: true

ceph_rgw_swift_compatibility: false
ceph_rgw_swift_account_in_url: true

```

And as from reconciler this comes as well in /opt/configuration/environments/kolla/configuration.yml:
```
# BEGIN ANSIBLE MANAGED BLOCK
enable_ceph_rgw: true
enable_ceph_rgw_keystone: true

ceph_rgw_swift_compatibility: false
ceph_rgw_swift_account_in_url: true

ceph_rgw_hosts:
...

# END ANSIBLE MANAGED BLOCK
```
Kind regards,
André.

**Comment by berendt** [comment]
That's on purpose. The necessary change to automatically generate ceph_rgw_hosts is only included in 6.0.2, which has yet to be finalised. Then ceph_rgw_hosts will be removed from the cookiecutter repository.

**Comment by nerdicbynature** [comment]
Ack

**Comment by berendt** [comment]
Fixed with https://github.com/osism/cfg-cookiecutter/commit/a164f20ae2a13cd279359566d511ad46291addb5
