### ISSUE TITLE
Grafana home dashboard / Prometheus rules copy task fails

### ISSUE THREAD

**Issue by linwalth** [osism/issues#79]
`Task: grafana : Copying over grafana home dashboard if exists
`
fails with
`Failed to get information on remote file (/etc/kolla/grafana/grafana_home_dashboard.json): Permission denied
`

**Comment by linwalth** [comment]
I am running osism-kolla deploy grafana with the grafana_home_dashboard.json from kolla-operations copied into the kolla overlay grafana folder.

**Comment by grawert** [comment]
This should have been fixed with: https://review.opendev.org/c/openstack/kolla-ansible/+/813185/4/ansible/roles/grafana/tasks/config.yml.

@linwalth Could you try with *quay.io/osism/osism-ansible:latest*? The 1.0.0 release will not have this patch!

**Comment by linwalth** [comment]
I upgraded the manager suite and now it runs through. Just needed some time to catch up with the upstream, it seems. Thank you!
