### ISSUE TITLE
Github: Use "on" and avoid yamllint disable-line rule:truthy

### ISSUE THREAD

**Issue by berendt** [osism/issues#8]
In many workflows the construct ``on:  # yamllint disable-line rule:truthy`` is used. This should be replaced by ``"on"``.

**Comment by tibeer** [comment]
@berendt done.

Releated PRs:
https://github.com/osism/documentation/pull/203
https://github.com/osism/container-images-kolla/pull/63
https://github.com/osism/cfg-generics/pull/107
https://github.com/osism/cfg-cookiecutter/pull/180
https://github.com/osism/ansible-collection-commons/pull/157
https://github.com/osism/testbed/pull/694
