### ISSUE TITLE
new image versiondo not get pulled during upgrade and  on check containers end in error

### ISSUE THREAD

**Issue by traskat** [osism/issues#802]
Hey,

while i was trying to upgrade today from zed to 2023.1/antilope a weird error appeared. As an example while upgrading commons with either the command `osism apply -a upgrade common` or `osism-kolla upgrade common`.  Here is the error:
```
failed: [host.example.com] (item={'key': 'cron', 'value': {'container_name': 'cron', 'group': 'cron', 'enabled': True, 'image': 'quay.io/osism/cron:zed', 'environment': {'KOLLA_LOGROTATE_SCHEDULE': 'daily'}, 'volumes': ['/etc/kolla/cron/:/var/lib/kolla/config_files/:ro', '/etc/localtime:/etc/localtime:ro', '/etc/timezone:/etc/timezone:ro', 'kolla_logs:/var/log/kolla/'], 'dimensions': {}}}) => {"ansible_loop_var": "item", "changed": true, "item": {"key": "cron", "value": {"container_name": "cron", "dimensions": {}, "enabled": true, "environment": {"KOLLA_LOGROTATE_SCHEDULE": "daily"}, "group": "cron", "image": "quay.io/osism/cron:zed", "volumes": ["/etc/kolla/cron/:/var/lib/kolla/config_files/:ro", "/etc/localtime:/etc/localtime:ro", "/etc/timezone:/etc/timezone:ro", "kolla_logs:/var/log/kolla/"]}}, "msg": "'Traceback (most recent call last):\\n  File \"/tmp/ansible_kolla_docker_payload_g7l2m519/ansible_kolla_docker_payload.zip/ansible/modules/kolla_docker.py\", line 404, in main\\n  File \"/tmp/ansible_kolla_docker_payload_g7l2m519/ansible_kolla_docker_payload.zip/ansible/module_utils/kolla_docker_worker.py\", line 34, in __init__\\n    super().__init__(module)\\n  File \"/tmp/ansible_kolla_docker_payload_g7l2m519/ansible_kolla_docker_payload.zip/ansible/module_utils/kolla_container_worker.py\", line 31, in __init__\\n    self.systemd = SystemdWorker(self.params)\\n  File \"/tmp/ansible_kolla_docker_payload_g7l2m519/ansible_kolla_docker_payload.zip/ansible/module_utils/kolla_systemd_worker.py\", line 59, in __init__\\n    restart_duration = (restart_timeout // restart_retries) - 1\\nZeroDivisionError: integer division or modulo by zero\\n'"}


```

The second problem is that after the manager was upgraded the upgrade commands did not pull the new image versions or better the image versions stayed on zed and did not changed to 2023.1/antilope. 

my configuration for the in the manager configuration.yml:
```
manager_version: 6.0.2
```
I also tried to put *openstack_version: 2023.1* into the  configuration.yml did not work either.

It seems that it is related to version 6.0.2. I switched to the manager_version 6.0.1 and that worked without problems to upgrade the commons

**Comment by berendt** [comment]
In the future please open one issue for one problem.

> while i was trying to upgrade today from zed to 2023.1/antilope a weird error appeared. As an example while upgrading commons with either the command `osism apply -a upgrade common` or `osism-kolla upgrade common`. Here is the error:
> 
> ```
> failed: [host.example.com] (item={'key': 'cron', 'value': {'container_name': 'cron', 'group': 'cron', 'enabled': True, 'image': 'quay.io/osism/cron:zed', 'environment': {'KOLLA_LOGROTATE_SCHEDULE': 'daily'}, 'volumes': ['/etc/kolla/cron/:/var/lib/kolla/config_files/:ro', '/etc/localtime:/etc/localtime:ro', '/etc/timezone:/etc/timezone:ro', 'kolla_logs:/var/log/kolla/'], 'dimensions': {}}}) => {"ansible_loop_var": "item", "changed": true, "item": {"key": "cron", "value": {"container_name": "cron", "dimensions": {}, "enabled": true, "environment": {"KOLLA_LOGROTATE_SCHEDULE": "daily"}, "group": "cron", "image": "quay.io/osism/cron:zed", "volumes": ["/etc/kolla/cron/:/var/lib/kolla/config_files/:ro", "/etc/localtime:/etc/localtime:ro", "/etc/timezone:/etc/timezone:ro", "kolla_logs:/var/log/kolla/"]}}, "msg": "'Traceback (most recent call last):\\n  File \"/tmp/ansible_kolla_docker_payload_g7l2m519/ansible_kolla_docker_payload.zip/ansible/modules/kolla_docker.py\", line 404, in main\\n  File \"/tmp/ansible_kolla_docker_payload_g7l2m519/ansible_kolla_docker_payload.zip/ansible/module_utils/kolla_docker_worker.py\", line 34, in __init__\\n    super().__init__(module)\\n  File \"/tmp/ansible_kolla_docker_payload_g7l2m519/ansible_kolla_docker_payload.zip/ansible/module_utils/kolla_container_worker.py\", line 31, in __init__\\n    self.systemd = SystemdWorker(self.params)\\n  File \"/tmp/ansible_kolla_docker_payload_g7l2m519/ansible_kolla_docker_payload.zip/ansible/module_utils/kolla_systemd_worker.py\", line 59, in __init__\\n    restart_duration = (restart_timeout // restart_retries) - 1\\nZeroDivisionError: integer division or modulo by zero\\n'"}
> ```

Check if you have set ``docker_restart_policy_retry`` in your configuration repository.

> The second problem is that after the manager was upgraded the upgrade commands did not pull the new image versions or better the image versions stayed on zed and did not changed to 2023.1/antilope.
> 
> my configuration for the in the manager configuration.yml:
> 
> ```
> manager_version: 6.0.2
> ```

Please paste the output of ``docker compose --project-directory /opt/manager ps``.

**Comment by traskat** [comment]
`docker_restart_policy_retry` is not set in the configuration repository

The output from the docker compose command

```
docker compose --project-directory /opt/manager ps
NAME                             IMAGE                                        COMMAND                                                SERVICE                CREATED          STATUS                      PORTS
kolla-ansible                    quay.io/osism/kolla-ansible:6.0.2            "/entrypoint.sh osism worker kolla-ansible"            kolla-ansible          22 minutes ago   Up 21 minutes (healthy)     
manager-api-1                    quay.io/osism/osism:0.20230919.0             "osism service api"                                    api                    44 hours ago     Up 22 minutes (healthy)     10.172.4.100:8000->8000/tcp
manager-ara-server-1             quay.io/osism/ara-server:1.7.0               "sh -c '/wait && /run.sh'"                             ara-server             2 days ago       Up 21 minutes (healthy)     10.172.4.100:8120->8000/tcp
manager-beat-1                   quay.io/osism/osism:0.20230919.0             "osism service beat"                                   beat                   44 hours ago     Up 22 minutes (healthy)     
manager-conductor-1              quay.io/osism/osism:0.20230919.0             "osism worker conductor"                               conductor              44 hours ago     Up 22 minutes (healthy)     
manager-inventory_reconciler-1   quay.io/osism/inventory-reconciler:6.0.1     "/sbin/tini -- /entrypoint.sh"                         inventory_reconciler   44 hours ago     Up 22 minutes (unhealthy)   
manager-mariadb-1                index.docker.io/library/mariadb:10.11.5      "docker-entrypoint.sh mariadbd"                        mariadb                47 hours ago     Up 22 minutes (healthy)     3306/tcp
manager-netbox-1                 quay.io/osism/osism-netbox:0.20230919.0      "osism worker netbox"                                  netbox                 44 hours ago     Up 22 minutes (healthy)     
manager-openstack-1              quay.io/osism/osism:0.20230919.0             "osism worker openstack"                               openstack              44 hours ago     Up 22 minutes (healthy)     
manager-redis-1                  index.docker.io/library/redis:7.2.0-alpine   "docker-entrypoint.sh redis-server --appendonly yes"   redis                  44 hours ago     Up 22 minutes (healthy)     6379/tcp
manager-watchdog-1               quay.io/osism/osism:0.20230919.0             "osism service watchdog"                               watchdog               44 hours ago     Up 22 minutes (healthy)     
osism-ansible                    quay.io/osism/osism-ansible:6.0.2            "/entrypoint.sh osism worker osism-ansible"            osism-ansible          22 minutes ago   Up 21 minutes (healthy)     
osismclient                      quay.io/osism/osism:0.20230919.0             "sleep infinity"                                       osismclient            44 hours ago     Up 22 minutes 
```

**Comment by berendt** [comment]
Output of the following commands:

```
osism get hostvars YOUR_MANAGER_HOSTNAME manager_version
osism get hostvars YOUR_MANAGER_HOSTNAME openstack_version
osism get hostvars YOUR_MANAGER_HOSTNAME ceph_version
osism get hostvars YOUR_MANAGER_HOSTNAME docker_restart_policy_retry
```

**Comment by berendt** [comment]
Stale. I will close. Please open if there is still a need.
