### ISSUE TITLE
openstack exporter: metric openstack_nova_server_status reports <nil> for flavor_id

### ISSUE THREAD

**Issue by mario-minners** [osism/issues#808]
Hi,

The Openstack exporter is very old and can therefore no longer handle newer nova api microversions. This is shown by the fact that some data is no longer available in the metrics, for example the flavor_id is missing in the openstack_nova_server_status metric. Unfortunately, this is not the only example as the pull list shows: https://github.com/openstack-exporter/openstack-exporter/pulls?q=is%3Apr+is%3Aclosed . Is it somehow possible that we can prevent the openstack exporter from being rolled out with prometheus so that we can deploy it ourselves until the project releases a new version that you can build with kolla?

**Comment by berendt** [comment]
You can disable the deployment of the openstack-exporter with `enable_prometheus_openstack_exporter: false` in `environments/kolla/configuration.yml`.

**Comment by berendt** [comment]
A release will be made this week. We can then make the change in the upstream and a backport of it. Then we will have a current version at the beginning of January. Maybe even at the end of December.

**Comment by mario-minners** [comment]
Thar are good news!
