### ISSUE TITLE
testbed: fix referenced URIs by the testbed documentation

### ISSUE THREAD

**Issue by scoopex** [osism/issues#814]
Some of the [linked URLs](https://osism.github.io/docs/guides/deploy-guide/examples/testbed/#webinterfaces) either go nowhere or do not behave correctly.

We should fix that, remove URIs (if they are not relevant anymore) or add a description if a URI is not always available.

- [x] Ceph redirects to another URL with a different port (http://192.168.16.10:7000)
- [x] Flower redirects to the Ceph dashboard
- [x] Grafana throws a 503
- [x] Kibana does not work with the password, 
- [x] Netdata does not work at all
- [x] Patchman throws a 404
- [x] Prometheus throws a 503
- [x] PhpMyAdmin throws a "php_network_getaddresses: getaddrinfo for db failed: Temporary failure in name resolution")

**Comment by berendt** [comment]
Grafana/Prometheus fixed by https://github.com/osism/terraform-base/commit/f799e089f0c2af429197c36dec5dfd0d1968b3a8
