### ISSUE TITLE
cannot run osism-openstack command due to wrong ansible directory of container

### ISSUE THREAD

**Issue by linwalth** [osism/issues#82]
I want to deploy osism-openstack services as swift per ceph-rgw (see: https://github.com/osism/issues/issues/67) and flavors for openstack with osism-openstack. But the playbooks are not found, as the /run-openstack.sh script in the osism-ansible container uses the var ANSIBLE_DIRECTORY=/ansible - so it will not be able to find my adapted playbooks at all, as it never tries to find them in /opt/configuration/environments/openstack/playbook-_____.yml.

**Comment by berendt** [comment]
You have to use osism-run openstack xxx to run custom playbooks placed inside environments/openstack. With osism-openstack you can run playbooks included in the osism-ansible container in the context of the Openstack environment.
