### ISSUE TITLE
libvirt cpu_models: Unacceptable CPU info: CPU doesn't have compatibility.

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#824]
We are trying to configure a libvirt cpu model that works with both our old Intel Cascade Lake and our new Ice Lake compute hosts.

After spawning two instances, one on an old host and one on a new, there were only flags added.
However nova-compute on a new host does not start with model CascadeLake-Server-noTSX and says the following:

```
2024-01-16 13:38:34.782 7 ERROR oslo_service.service nova.exception.InvalidCPUInfo: Configured CPU model: Cascadelake-Server-noTSX and CPU Flags [] ar not compatible with host CPU. Please correct your config and try again. Unacceptable CPU info: CPU doesn't have compatibility.
```

But the model should be usable:

```
(nova-libvirt)[root@compute-new /]#  virsh domcapabilities | grep Casc
      <model fallback='forbid'>Cascadelake-Server</model>
      <model usable='yes'>Cascadelake-Server-noTSX</model>
      <model usable='no'>Cascadelake-Server</model>
```

Maybe setting check=none instead of check=partial could help according to this issue?
https://gitlab.com/libvirt/libvirt/-/issues/304

Any idea how to set check=none?

**Comment by artificial-intelligence** [comment]
In addition to our exchange via matrix chat, let me add something regarding your question:

> Maybe setting check=none instead of check=partial could help according to this issue?
https://gitlab.com/libvirt/libvirt/-/issues/304
> Any idea how to set check=none?

I'm not sure if this is even possible, but in any case, I think it is not a good idea, because it could in theory lead to guest machines crashing, software inside the machine crashing or other security issues because CPU flags are not correctly enforced.

**Comment by Nils98Ar** [comment]
For some reason 43% of the instances have `cpu_mode='custom'` and 57% have `cpu_mode='host-model'` according to the yamls in `/etc/libvirt/qemu`.  Different instances spread across different hosts. I would have expected host-model for all instances.

**Comment by Nils98Ar** [comment]
No cpu-related properties are configured in any of our flavors or images at it seems...

Both commands do not return anything:

```
dragon@manager01:~$ openstack flavor list -c ID -f value | tr -d "\r" | while read flavor; do openstack flavor show $flavor -c name -c properties;done | grep -i cpu
dragon@manager01:~$ 
```

```
dragon@manager01:~$ openstack image list -c ID -f value | tr -d "\r" | while read image; do openstack image show $image -c name -c properties;done | grep -i cpu
dragon@manager01:~$ 
```

**Comment by Nils98Ar** [comment]
If I'm understanding it right it's a feature? Then I ask myself why still have instances with `cpu_mode='host-model'`.

https://github.com/libvirt/libvirt/blob/3a45455558d74b2cb351c74cab472ac654f54708/NEWS.rst#L3317

**Comment by Nils98Ar** [comment]
We've have figured out that the `cpu_mode` switches from `host-model` to `custom` and explicit model after live-migration of the instance although host-model is still configured in the nova.conf.

Interesting but this seems to be no problem.

**Comment by Nils98Ar** [comment]
Our configuration...
```
cpu_mode = custom
cpu_models: Cascadelake-Server-noTSX
cpu_model_extra_flags: -mpx
```

.... still differs from the cpu_mode custom configuration that libvirt configures on live migration based on the host-model "auto configuration" (the `hle` and `rtm` disables are what `-noTSX` does in our configuration so only the 19 requires are additional):

```
  <cpu mode='custom' match='exact' check='partial'>
    <model fallback='forbid'>Cascadelake-Server</model>
    <vendor>Intel</vendor>
    <topology sockets='2' dies='1' cores='1' threads='1'/>
    <feature policy='require' name='ss'/>
    <feature policy='require' name='vmx'/>
    <feature policy='require' name='hypervisor'/>
    <feature policy='require' name='tsc_adjust'/>
    <feature policy='require' name='umip'/>
    <feature policy='require' name='pku'/>
    <feature policy='require' name='md-clear'/>
    <feature policy='require' name='stibp'/>
    <feature policy='require' name='arch-capabilities'/>
    <feature policy='require' name='xsaves'/>
    <feature policy='require' name='ibpb'/>
    <feature policy='require' name='ibrs'/>
    <feature policy='require' name='amd-stibp'/>
    <feature policy='require' name='amd-ssbd'/>
    <feature policy='require' name='rdctl-no'/>
    <feature policy='require' name='ibrs-all'/>
    <feature policy='require' name='skip-l1dfl-vmentry'/>
    <feature policy='require' name='mds-no'/>
    <feature policy='require' name='pschange-mc-no'/>
    <feature policy='disable' name='hle'/>
    <feature policy='disable' name='rtm'/>
  </cpu>
```

But only 11 of them are visible via lscpu in the instance spawned on an old hypervisor with host-model config (mpx is not for example):
```
ss
vmx
hypervisor
ibrs
ibpb
stibp
tsc_adjust
xsaves
umip
pku
arch-capabilities
```

2 of the flags visible in the instance are not even visible on the old hypervisors with lscpu:
```
hypervisor
umip
```
At least umip is available on the new hypervisors according to lscpu.

5 of these 11 flags are missing in instances spawned on the new hypervisors with our new custom config but still supported on both the old and new hypervisors:
```
ss
stibp
tsc_adjust
vmx
xsaves
```

These flags are configured via the host-model auto-configure mechanism on the old hypervisors but not visible within the instances or on any of the hypervisors via lscpu:
```
amd-ssbd
amd-stibp
ibrs-all
md-clear
mds-no
pschange-mc-no
rdctl-no
skip-l1dfl-vmentry
```

Conclusion: I ask myself why the umip and hypervisor flags are added on the old hypervisors with host-model although it's not supported by the hypervisor and why the last 8 flags are configured in the xml but not visible in the vms or supported by any hypervisor.

**Comment by Nils98Ar** [comment]
Config is now:
```
[libvirt]
cpu_mode = custom
cpu_models: Cascadelake-Server-noTSX
cpu_model_extra_flags: -mpx,ss,stibp,tsc_adjust,vmx,xsaves
```

The remaining flags are either not visible in any VMs or not available on the old or new hypervisors.
