### ISSUE TITLE
2023.2  (Bobcat)  Testbed nova/ceph issues

### ISSUE THREAD

**Issue by matfechner** [osism/issues#825]
Hi @berendt, hi @fkr, 

i've try the first run to upgrade a testbed to 2023.2, and it works but  some issues was fixed manually:

1. in kolla/configuration.yml  this variable is missing: `external_ceph_cephx_enabled: false`
2. in the  nova_compute container the ceph config is strange. The file "ceph.ceph.client.nova.keyring" should name   "ceph.client.nova.keyring"

**Comment by berendt** [comment]
> i've try the first run to upgrade a testbed to 2023.2, and it works but some issues was fixed manually:

Thanks for testing!

> 1. in kolla/configuration.yml  this variable is missing: `external_ceph_cephx_enabled: false`

`external_ceph_cephx_enabled: "yes"` is set by default in `001-kolla-defaults.yml`. Why do you want to use `false`?

> 2. in the  nova_compute container the ceph config is strange. The file "ceph.ceph.client.nova.keyring" should name   "ceph.client.nova.keyring"

You have to remove `ceph_nova_keyring: ceph.client.nova.keyring` from `environments/ceph/configuration.yml`. This is one of the required changes when you upgrade from 6.x to 7.x.
