### ISSUE TITLE
Fix all ansible-lint issues after upgrade to ansible-lint 6.22.2

### ISSUE THREAD

**Issue by berendt** [osism/issues#829]
We have updated ansible-lint to ansible-lint 6.22.2. All Ansible collections and playbooks must be checked and corrected if necessary.

The following new rule has to be added to the ignored rules in the .ansible-lint file:

- var-naming[no-role-prefix]

**Comment by sbstnnmnn** [comment]
housekeeping completed

**Comment by berendt** [comment]
Close this as done. The variables will be changed after the next release (7.0.0). We ignore the no-role-prefix rule for the moment.
