### ISSUE TITLE
Redis service of the manager is broken after node reboot

### ISSUE THREAD

**Issue by rmueller-b1** [osism/issues#833]
Hello,

in one customer environment the OSISM Redis container broke with the following message:
`Bad file format reading the append only file appendonly.aof.1423.incr.aof: make a backup of your AOF file, then use ./redis-check-aof --fix <filename.manifest>`

I cannot execute that suggested command as the container is constantly rebooting. It happened after the customer rebooted that node.
That issue causes the manager-netbox, manager-listener and the manager-openstack container to having dns issues which causes all OSISM commands not to be executable.

Is there a way to resolve that issue and to prevent something like that happening again in the future?

Kind regards,
Robert Müller

**Comment by berendt** [comment]
We have 2 Redis services. On the manager and on the control plane. Which Redis service is broken?

**Comment by berendt** [comment]
The Redis service on the Manager can be easily reset.

```
cd /opt/manager
docker compose down
docker rm -f redis
docker volume rm manager_redis
docker compose up -d
```

**Comment by berendt** [comment]
Perhaps it also makes sense to make the Redis service completely stateless so that it is sufficient in future when the service is restarted. We only use Redis as a broker in the backend and have no state on it that needs to be persistent.

**Comment by rmueller-b1** [comment]
The reset was successful as provided.
Thanks for the quick response.
