### ISSUE TITLE
Feedback on the 7.0.0 pre-releases

### ISSUE THREAD

**Issue by berendt** [osism/issues#841]

**Comment by berendt** [comment]
Upload of Glance images via Horizon is not possible (tested in the Cloud in a Box).

**Comment by maliblatt** [comment]
when upgrading the manager from 6.0.2 to 7.0.0b I am encountering the problem, that manager-mariadb-1 is not getting healthy, so the manager update is failing.
The problem seems that this file with the healthcheck credentials is missing:
`/var/lib/docker/volumes/manager_mariadb/_data/.my-healthcheck.cnf`
this leads to:
`2024-02-23  8:07:09 66 [Warning] Access denied for user 'root'@'localhost' (using password: NO)`

how to generate the missing file?

**Comment by berendt** [comment]
> when upgrading the manager from 6.0.2 to 7.0.0b I am encountering the problem, that manager-mariadb-1 is not getting healthy, so the manager update is failing. The problem seems that this file with the healthcheck credentials is missing: `/var/lib/docker/volumes/manager_mariadb/_data/.my-healthcheck.cnf` this leads to: `2024-02-23 8:07:09 66 [Warning] Access denied for user 'root'@'localhost' (using password: NO)`
> 
> how to generate the missing file?

I'll fix that. For now, comment the healtcheck for the MariaDB container in /opt/manager/docker-compose.yml and then run docker compose up -d in /opt/manager. Followed by osism reconciler sync.

You also have to change the depends_on of the are-server service:

```
    depends_on:
      - mariadb
```

**Comment by maliblatt** [comment]
for the new octavia persistence feature an additional secret is needed, may be this could be written in the release notes:
`octavia_persistence_database_password`

After defining the password in the kolla secrets I get an other error when doing the octavia bootstrap:
`ERROR octavia-db-manage sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, \"ProxySQL Error: Access denied for user 'octavia'@'10.70.194.81' (using password: YES)`

**Comment by maliblatt** [comment]
For the release notes this could be very useful:
the certificate location in haproxy has been changed. In our case we have some additional entries that are not longer working, so the haproxy has been stopped in the upgrade process but did not start again.
old location:
`/etc/haproxy/haproxy.pem`
new location:
`/etc/haproxy/certificates/haproxy.pem`

**Comment by maliblatt** [comment]
While ceph upgrade from 17.2.6 to 17.2.7 we are running in that error, may be this is related to our environment, at the moment I am still not sure, have to investigate further, but it seems, a secret is missing:

`TASK [create potentially missing keys (rbd and rbd-mirror)] ********************`
`failed: [control1-dev2-az0.pco.ps-intern.de] (item=['bootstrap-rbd', 'control1-dev2-az0.pco.ps-intern.de']) => {"ansible_loop_var": "item", "changed": false, "delta": "", "end": "", "item": ["bootstrap-rbd", "control1-dev2-az0.pco.ps-intern.de"], "rc": 1, "start": "", "stderr": "", "stderr_lines": [], "stdout": "Couldn't fetch the key client.bootstrap-rbd at /var/lib/ceph/bootstrap-rbd/.", "stdout_lines": ["Couldn't fetch the key client.bootstrap-rbd at /var/lib/ceph/bootstrap-rbd/."]}`

**Comment by maliblatt** [comment]
> After defining the password in the kolla secrets I get an other error when doing the octavia bootstrap: `ERROR octavia-db-manage sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, \"ProxySQL Error: Access denied for user 'octavia'@'10.70.194.81' (using password: YES)`

it seems, that here is the octavia user definition in the proxysql missing, so octavia ist not allowed to connect, there is no octavia.yaml under /etc/kolla/proxysql in our dev environment ...

**Comment by berendt** [comment]
Release done. I'm closing that. Thanks for the input, @maliblatt
