### ISSUE TITLE
Nova Deployment fault

### ISSUE THREAD

**Issue by rmueller-b1** [osism/issues#851]
Hello,

during the deployment of Nova on a new Hypervisor I receive the following error during `TASK [nova-cell : Copying over nova.conf]`:
```
    "msg": "An unhandled exception occurred while templating '{'auth_url': '{{ keystone_internal_url }}', 'domain_name': 'default', 'password': '{{ keystone_admin_password }}', 'project_name': '{{ keystone_admin_project }}', 'user_domain_name': 'default', 'username': '{{ keystone_admin_user }}'}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ keystone_internal_fqdn | kolla_url(internal_protocol, keystone_internal_port) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while templating string: No filter named 'kolla_url'.. String: {{ keystone_internal_fqdn | kolla_url(internal_protocol, keystone_internal_port) }}"
```

I was looking into the used template for this task and the mentioned variable doesn't even show up. Is that error pointing to a different issue? I also used `-vvvv` at one point but the message doesn't get any different.

We have the following setup:
- OSISM v 5.2.0
- Openstack release Zed
- 3 Controller, 2 Compute as VMs in VMWare
- the mentioned HV is a physical Server that should be added to the Cloud

**Comment by berendt** [comment]
Can you check if openstack_version is set in environments/manager/configuration.yml?

**Comment by rmueller-b1** [comment]
openstack_version is set to 5.2.0

**Comment by berendt** [comment]
> openstack_version is set to 5.2.0

You have to remove openstack_version (as well as ceph_version) from environments/manager/configuration.yml when you want to use a stable release of OSISM (1.3 in https://osism.github.io/docs/guides/upgrade-guide/manager). If you want to use a stable OSISM version only set manager_version in environments/manager/configuration.yml. If you set openstack_version (or ceph_version) you have a combination that may not fit.

Please note that 5.3.0 is the last available stable version in OSISM series 5 and that OSISM series 6 is already available. The first pre-release of OSISM series 7 is also already available.

**Comment by berendt** [comment]
What's strange is that we only introduced kolla_url filter plugin in January 2024 in the Kolla defaults. The default values come from the inventory reconciler.

In quay.io/osism/inventory-reconciler:5.2.0 we have:

```
all/001-kolla-defaults.yml:keystone_internal_url: "{{ internal_protocol }}://{{ keystone_internal_fqdn | put_address_in_context('url') }}:{{ keystone_public_port }}"
```

```
quay.io/osism/inventory-reconciler                        5.2.0            621968b1ee80   8 months ago    309MB
```

**Comment by berendt** [comment]
Since the kolla_url was only added in January 2024, you must have a container image somewhere that is quite new. The keystone_internal_url is set in the defaults and these are in the inventory reconciler.

This is the PR that added kolla_url: https://github.com/osism/defaults/pull/154

**Comment by berendt** [comment]
Issue because of network trouble (missing VLAN).
