### ISSUE TITLE
OSISM 6.0.2 doesn't deploy newest neutron container

### ISSUE THREAD

**Issue by costelter** [osism/issues#857]
While deploying a new region we stumpled upon an outdated neutron container.

We deployed with manager version set to 6.0.2 and got .20230919 instead of .20231012 as introduced with 6.0.1.

While testing the new env we run into the "A virtual logical switch port cannot be bound to a host." error.

**Comment by berendt** [comment]
We only changed the tag of the neutron-server image. Not of  all neutron images. Is the neutron server on the 20231012 tag?

https://github.com/osism/sbom/blob/main/6.0.2/openstack.yml#L306

**Comment by berendt** [comment]
Since there was no further input here, I assume that the problem no longer exists. Otherwise please re-open the issue.
