### ISSUE TITLE
Revision of Prometheus exporters

### ISSUE THREAD

**Issue by berendt** [osism/issues#860]

**Comment by rhizoet** [comment]
Can explain what should I do here?

**Comment by berendt** [comment]
We use the Kolla container images for the prometheus exporter. Check all versions in https://github.com/openstack/kolla/blob/master/kolla/common/sources.py#L311-L430. Are they up to date? Are the used exporters are still alive?

**Comment by rhizoet** [comment]
Alright I will check

**Comment by rhizoet** [comment]
Review is open: https://review.opendev.org/c/openstack/kolla/+/910719
