### ISSUE TITLE
Configuration Templates should have ipwrap filter for IPv6 deployments

### ISSUE THREAD

**Issue by fzakfeld** [osism/issues#862]
When using IPv6 addresses in most configs, e.g. docker-compose.yml they need to be wrapped in square brackets to be distinguishable from port numbering.

Current workaround is something like this:

```
osism_api_host: "{{ '2a00:12e8:f123:167:4e38:d5ff:fe17:3192' | ansible.utils.ipwrap }}"
```

IMO the variables should contain the actual IP address. I suggest to add the ipwrap filter where needed (e.g. in configuration file templates), like [here](https://github.com/osism/ansible-collection-services/blob/main/roles/manager/templates/docker-compose.yml.j2#L235)

Legacy IPv4 Addresses will simply be returned as it (without brackets) from the filter, so it should not impact any existing deployments which use IPv4.

**Comment by berendt** [comment]
@fzakfeld Is this something you want to contribute as PR in ansible-collection-services?

If not, we would plan and tackle it after the next OSISM release (end of March).

**Comment by fzakfeld** [comment]
Yes, this is something we are going to need soon and I can contribute it

**Comment by berendt** [comment]
@fzakfeld Any update here?

**Comment by fzakfeld** [comment]
Unfortunately not, I'll try to get it done by eow
