### ISSUE TITLE
7.0.0b: permission denied error in fluentd service

### ISSUE THREAD

**Issue by berendt** [osism/issues#864]
While upgrading fluentd we encounter two problems, may be the first is caused by ourself, we used an old overlay file which contains some swift section:
`[error]: config error file="/etc/fluentd/fluentd.conf" error_class=Fluent::ConfigError error="out_file: `/var/log/kolla/swift/swift_latest.log` is not writable"`

second problem I did not have further looked into, but the fluentd is not starting because of:
`[error]: #0 unexpected error error_class=Errno::EACCES error="Permission denied @ dir_s_mkdir - /var/run/td-agent"`

_Originally posted by @maliblatt in https://github.com/osism/issues/issues/841#issuecomment-1961548758_

**Comment by berendt** [comment]
Behaviour cannot yet be reproduced in the testbed when upgrading from fluentd:4.5.1.20230919 (OSISM 6.0.2) to fluentd:5.0.2.20240221 (OSISM 7.0.0b).

**Comment by maliblatt** [comment]
I found the reason for the problem, in our overlay files we hat the following paths for the pos files:
`pos_file /var/run/td-agent/$FILE.pos`

This seems to have changed in the new release to:
`/var/run/fluentd/$FILE.pos`

We will have to review all our fluentd overlay files.

**Comment by berendt** [comment]
> I found the reason for the problem, in our overlay files we hat the following paths for the pos files: `pos_file /var/run/td-agent/$FILE.pos`
> 
> This seems to have changed in the new release to: `/var/run/fluentd/$FILE.pos`
> 
> We will have to review all our fluentd overlay files.

I'll add it to the upgrade nodes.
