### ISSUE TITLE
7.0.0b: couldn't fetch the key client.bootstrap-rbd error in ceph-rolling_update play

### ISSUE THREAD

**Issue by berendt** [osism/issues#865]
While ceph upgrade from 17.2.6 to 17.2.7 we are running in that error, may be this is related to our environment, at the moment I am still not sure, have to investigate further, but it seems, a secret is missing:

`TASK [create potentially missing keys (rbd and rbd-mirror)] ********************`
`failed: [control1-dev2-az0.pco.ps-intern.de] (item=['bootstrap-rbd', 'control1-dev2-az0.pco.ps-intern.de']) => {"ansible_loop_var": "item", "changed": false, "delta": "", "end": "", "item": ["bootstrap-rbd", "control1-dev2-az0.pco.ps-intern.de"], "rc": 1, "start": "", "stderr": "", "stderr_lines": [], "stdout": "Couldn't fetch the key client.bootstrap-rbd at /var/lib/ceph/bootstrap-rbd/.", "stdout_lines": ["Couldn't fetch the key client.bootstrap-rbd at /var/lib/ceph/bootstrap-rbd/."]}`

_Originally posted by @maliblatt in https://github.com/osism/issues/issues/841#issuecomment-1961543336_

**Comment by berendt** [comment]
Could not be reproduced in the testbed so far when upgrading from Ceph 17.2.6 (OSISM 6.0.2) to Ceph 17.2.7 (OSSIM 7.0.0b).

**Comment by maliblatt** [comment]
I found the reason for the problem, in our overlay files we hat the following paths for the pos files:
`pos_file /var/run/td-agent/$FILE.pos`

This seems to have changed in the new release to:
`/var/run/fluentd/$FILE.pos`

We will have to review all our fluentd overlay files.

**Comment by fkr** [comment]
@berendt is this something relevant for the upgrade notices?

**Comment by maliblatt** [comment]
I have successfully upgraded the ceph cluster to 17.2.7 after creating an empty directory for the key (outside the container):
`mkdir /var/lib/ceph/bootstrap-rbd`
