### ISSUE TITLE
2023.2 image interfaces error with CAPI deployment

### ISSUE THREAD

**Issue by mathgonzlez** [osism/issues#867]
Hi,

I'm encountering an issue with a deployment of an Amphora using CAPI (Magnum). The cluster configuration creates a load balancer (LB) with two interfaces that work great initially. However, after restarting or shutting down the LB VM, I can no longer reach my cluster. I've identified a couple of issues:

- After the LB creation, the VM only has one of the two interfaces inside the operating system.
- After a reboot, the second interface appears in the LB VM but without an IP address and in a DOWN state.

Due to these issues, I'm unable to use the Magnum cluster effectively. If the VM is restarted, I lose access to my cluster and can't reestablish it.

im in 2023.2 using the latest image for this version

Thanks

**Comment by berendt** [comment]
Which CAPI plugin do you use in Magnum? So far we have pre-installed the plugin from Vexxhost and recently changed it to the plugin from StackHPC because it should become an intree plugin in the future.

**Comment by mathgonzlez** [comment]
> Which CAPI plugin do you use in Magnum? So far we have pre-installed the plugin from Vexxhost and recently changed it to the plugin from StackHPC because it should become an intree plugin in the future.

Hi, thanks for reply. Im using vexxhost, but idk if is something related with plugin itself because the lb work in the first boot of the image. i lost access after a reboot.

Thanks!

**Comment by mathgonzlez** [comment]
I think is very long for document the procedure here but i can share a guide to configure CAPI and OSP:
https://satishdotpatel.github.io/openstack-magnum-capi/

With this youre able to reproduce 100% because i try in differents openstack env.
