### ISSUE TITLE
Using `openstack` in custom playbooks

### ISSUE THREAD

**Issue by killermoehre** [osism/issues#868]
Hi,

how would I use `openstack` with the `admin` cloud in a custom playbook?

Setting up drölfzig baremetal hosts and making sure, that DNS zones and names are defined for the infrastructure is something I want to automate.

**Comment by killermoehre** [comment]
So, I built the custom OpenStack playbook, but `openstack.cloud.dns_zone` fails with a generic

```
keystoneauth1.exceptions.connection.SSLError: SSL exception connecting to https://api-intern.customer.tld:5000/v3/auth/tokens: HTTPSConnectionPool(host='api-intern.customer.tld', port=5000): Max retries exceeded with url:
 /v3/auth/tokens (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
```

Seems like the Ansible module inside the container (which container?) doesn't use the custom Root-CA.

I verified with `openssl s_client -connect api-intern.customer.tld:5000 < /dev/null` from both the manager host itself as well from inside the `openstackclient` container that the connection itself works.

This seems to be `python` issue, because if I specify `ca_cert: /etc/ssl/certs/ca-certificates.crt` it starts to work. I think implementing [`truststore`](https://pypi.org/project/truststore/) would be the right solution here.

**Comment by berendt** [comment]
> This seems to be `python` issue, because if I specify `ca_cert: /etc/ssl/certs/ca-certificates.crt` it starts to work. I think implementing [`truststore`](https://pypi.org/project/truststore/) would be the right solution here.

Yes, that should be solved in a generic way.

We are currently doing it via clouds.yaml. Then you only have it in one place: https://github.com/osism/testbed/blob/main/environments/openstack/clouds.yml#L9

**Comment by killermoehre** [comment]
Interesting enough, it works as expected if I use `openstack --os-cloud admin` on the manager itself. Only from inside the playbook when I use the OpenStack Ansible module I see the CA-error.

**Comment by berendt** [comment]
I think that‘s done. CA certificates will be follwed up in the linked issue.
