### ISSUE TITLE
Timeout for custom playbooks

### ISSUE THREAD

**Issue by killermoehre** [osism/issues#870]
Hi,

I'm writing a custom playbook with a longer running command in it. Can I somehow increase/disable the 60-second timeout?

```console
$ osism apply --format script -e custom create-ironic-agent-image                                                                                                                                                           
2024-02-27 15:35:20 | INFO     | Task was prepared for execution. It takes a moment until the task has been started and output is visible here.                                                                                                
2024-02-27 15:35:20 | INFO     | An attempt is made to execute a role that is provided in the configuration repository. If there is no further output following this output, the role create-ironic-agent-image in the environment custom was not found. The timeout is explicitly set to 60 seconds. 
```

I'm really sure the command running there is printing lines, so `ansible` should actually be able to check the liveliness.

**Comment by berendt** [comment]
Which OSISM version are you using?

**Comment by killermoehre** [comment]
> Which OSISM version are you using?

6.0.2

**Comment by berendt** [comment]
There is a new plugin (osism.commons.still_alive) in latest and from 7 onwards with which you can avoid timeouts if an Ansible task runs longer without output.

In environments/ansible.cfg:

```
[defaults]
stdout_callback = osism.commons.still_alive
```

The 60 seconds on custom plays has been fixed with https://github.com/osism/python-osism/pull/745. Also available from OSISM 7 on or in latest.

**Comment by killermoehre** [comment]
We can't just update to OSISM 7. Also, my Ansible task _does_ produce output.

**Comment by berendt** [comment]
Yes, it's a bug that's fixed on latest and will be fixed in OSISM 7. There will be no more OSISM 6 releases.

**Comment by killermoehre** [comment]
@berendt but there is no stable 7 release yet, right?

**Comment by berendt** [comment]
> @berendt but there is no stable 7 release yet, right?

Release date of OSISM 7 is 20.03.2024.

**Comment by berendt** [comment]
This is possible in latest stable OSISM.
