### ISSUE TITLE
001-kolla-defaults.yml vs. https://opendev.org/openstack/kolla-ansible/src/branch/master/ansible/group_vars/all.yml

### ISSUE THREAD

**Issue by uwej711** [osism/issues#875]
Hi, 

this is more a question than an issue. I've been working on changes to kolla-ansible and updated there the group_vars/all.yml. Now I created patches and build my own osism/container-image-kolla-ansible image to apply those patches to our environment. But my changes to group_vars/all.yml are not taken into consideration when I run osism apply.

Is this by design? Do you have to update the defaults here every time or am I missing something?

Kind regards
Uwe

**Comment by berendt** [comment]
I'll reply later, I don't have time right now. Adding the defaults is no problem, the review looks good now and I think it will be merged soon. After that we can update and merge the open backport PR.

**Comment by uwej711** [comment]
No problem, I closed the related PR on container-image-kolla-ansible and will create a new one with the accepted change.

**Comment by uwej711** [comment]
We have a few other changes upstream that would make the experience with Skyline much better:

- https://review.opendev.org/c/openstack/kolla-ansible/+/910514 (Fixes Monitor Center not working)
- https://review.opendev.org/c/openstack/kolla-ansible/+/909482 (Fixes broken Certificates)
- https://review.opendev.org/c/openstack/kolla-ansible/+/905860 (mentioned SSO configuration)
- https://review.opendev.org/c/openstack/kolla-ansible/+/909481 (minimal look customisation)

I have backports for 2023.1 and can create a PR, but yet not for 2023.2 since I have no environment to test this version.

**Comment by berendt** [comment]
We only back port what is already included upstream on master. Otherwise we are constantly lagging behind the changes and have to update them.

**Comment by berendt** [comment]
The defaults have been adjusted accordingly. If further defaults are still missing, please open a follow up issue.
