### ISSUE TITLE
Where to configure Grafana?

### ISSUE THREAD

**Issue by b1knoll** [osism/issues#876]
Hello,

rolling out a Ceph cluster.

Disabled ara and Openstack under:

```
#ara
configuration/environments# vim manager/configuration.yml

# openstack
configuration/environments/kolla/configuration.yml
```

When trying to deploy Grafana I get the following:

```
osism apply grafana
2024-02-28 12:03:51 | INFO     | Task was prepared for execution. It takes a moment until the task has been started and output is visible here.
[WARNING]: Skipping callback 'ara_default', unable to load due to: The server
dependencies must be installed to record data offline or run the API server.
[WARNING]: Could not match supplied host pattern, ignoring: enable_grafana_True

PLAY [Group hosts based on configuration] **************************************
skipping: no hosts matched

PLAY [Apply role grafana] ******************************************************
skipping: no hosts matched

PLAY RECAP *********************************************************************
```

Where do I have to configure the Grafana service?

Best,
Marc

**Comment by berendt** [comment]
Grafana is deployed on all nodes in the monitoring host group (defined in inventory/20-roles). Are there hosts in the monitoring group?

**Comment by b1knoll** [comment]
No, I only added the manager node to the monitoring definition:

# Nodes which are intended for monitoring services belong to
# this group
[monitoring]
managernode

**Comment by b1knoll** [comment]
No, I only added the manager node to the monitoring definition:

[monitoring]
managernode

**Comment by berendt** [comment]
Please use code blocks for code. Try it this way:

```
[monitoring:children]
manager
```

Run the reconciler after making changes to the inventory: ``osism reconciler sync``

**Comment by berendt** [comment]
For Grafana the node has to be part of the control group.

**Comment by berendt** [comment]
No longer relevant.
