### ISSUE TITLE
ceph-rook - [docs] analyze and document old deployment method

### ISSUE THREAD

**Issue by yeoldegrove** [osism/issues#878]
Analyze and document the old deployment method (via `ceph-ansible`) in a way that we can use it as input to design the new deployment method. This is not about the deployed features (see #879) but about the pieces method and code itself.

**Comment by b1-huebner** [comment]
I just added the pdf which includes the analysis of the old deployment methods
[issue-878-analyze-old-deployment-method.pdf](https://github.com/user-attachments/files/17015090/issue-878-analyze-old-deployment-method.pdf)
