### ISSUE TITLE
ceph-rook - [docs] analyze and document old deployed features

### ISSUE THREAD

**Issue by yeoldegrove** [osism/issues#879]
Analyze and document the features that are deployed by `ceph-ansible` so that we can adapt this for the new deployment method.

**Comment by yeoldegrove** [comment]
A collection of settings for the old and new deployment method is in this pad:
https://input.scs.community/iONqFJduQS-aN0URauTxqA#

This will help us later understanding which exact settings we need to replicate in the new deployment method.

**Comment by berendt** [comment]
Can you please persist the relevant part from the pad here in the issue. Perhaps the content in the pad will no longer exist in the future.

**Comment by yeoldegrove** [comment]
https://input.scs.community/s/bzi6nwI-L# is a shortened version of https://input.scs.community/iONqFJduQS-aN0URauTxqA# that gives a more structured view of the different default settings of ceph-ansible and rook in a default configuration.
