### ISSUE TITLE
Copy ceph keys - just for Ceph

### ISSUE THREAD

**Issue by b1knoll** [osism/issues#893]
Hello,

if someone wants to install _only_ Ceph with OSISM, the step

```
osism apply copy-ceph-keys
```

https://osism.github.io/docs/guides/deploy-guide/services/ceph/

fails, because there is no kolla, no Openstack.

Copying the admin key to

```
environments/infrastructure/files/ceph/ceph.client.admin.keyring
```

works, however the script fails complaining the missing kolla folders.

Please adjust the script to just grep the ceph admin keyring for Ceph.

Best,
Marc

**Comment by berendt** [comment]
Play should not fail because of `ignore_errors: true`. But makes sense to do some overall improvements in the play.

**Comment by b1knoll** [comment]
Yes, but it fails. I attached the error output to this message.

**Comment by berendt** [comment]
It works like expected.

```
changed: [manager] => (item={'src': 'ceph.client.admin.keyring', 'dest': '/opt/configuration/environments/infrastructure/files/ceph/ceph.client.admin.keyring'})
```

Failed tasks are ignored. I will improve the play to avoid the failed tasks.

```
manager                  : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1
```

**Comment by b1knoll** [comment]
Sounds good.
