### ISSUE TITLE
Cleanup container labels

### ISSUE THREAD

**Issue by berendt** [osism/issues#894]
At the moment we use the following label in all/most of our container images:

```
LABEL "org.opencontainers.image.documentation"="https://docs.osism.de" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://www.osism.de" \
      "org.opencontainers.image.vendor"="Betacloud Solutions GmbH"
```

* replace https://docs.osism.tech with https://osism.github.io/docs/intro/
* replace https://www.osism.de (org.opencontainer.image.url) with https://quay.io/organization/osism
* replace Betacloud Solutions GmbH with OSISM GmbH

Find and check all container images.

**Comment by janhorstmann** [comment]
I have liberally interpreted the assignment to always replace  the value of the given keys no matter what is currently set.

`osism/container-images/cgit/Containerfile` did not contain any label yet. I have taken the liberty to add them.

There are more repositories defining containers, but none of them are labeled yet:
* [container-image-ceph-ansible](https://github.com/osism/container-image-ceph-ansible)
* [container-image-osism-ansible](https://github.com/osism/container-image-osism-ansible)
* [container-image-kolla-ansible](https://github.com/osism/container-image-kolla-ansible)
* [container-image-inventory-reconciler](https://github.com/osism/container-image-inventory-reconciler)

Should the same set of labels be added there?

**Comment by berendt** [comment]
> There are more repositories defining containers, but none of them are labeled yet:
> 
> * [container-image-ceph-ansible](https://github.com/osism/container-image-ceph-ansible)
> * [container-image-osism-ansible](https://github.com/osism/container-image-osism-ansible)
> * [container-image-kolla-ansible](https://github.com/osism/container-image-kolla-ansible)
> * [container-image-inventory-reconciler](https://github.com/osism/container-image-inventory-reconciler)
> 
> Should the same set of labels be added there?

The labels are a little bit hidden there. Check the playbooks/build.yml file.

**Comment by berendt** [comment]
Should have been all of them.
