### ISSUE TITLE
Horizon Sign-Out-URL astray after switching to custom theme

### ISSUE THREAD

**Issue by gravityscout** [osism/issues#898]
Hello there,

after deploying a custom theme (simply adding custom logos + favicon) via `osism-kolla deploy horizon` we would encounter the following issue:

- after enabling / switching to the newly added theme the sign-out-url would no longer match the default pattern https://horizon-dashboard.de/auth/logout/ 
- hence it would no longer redirect to the login-screen https://horizon-dashboard.de/auth/login/
- instead we were redirected to a blank page

unfortunately I can't recall the wrong pattern.
Maybe someone else has encountered this aswell?

Thanks and kind regards.

**Comment by berendt** [comment]
How exactly did you do that? We also use a custom theme and we have there are no problems.

It could make sense to add your custom theme here: https://github.com/osism/openstack-themes. This way the theme will be available in our Horizon container images without any local modifications

**Comment by berendt** [comment]
Since there was no more feedback here, I assume it is done. Otherwise open again.
