### ISSUE TITLE
Doc: Use good [initial]_cpu_allocation_ratio in example

### ISSUE THREAD

**Issue by garloff** [osism/issues#902]
Looking at the OSISM docs:
https://osism.github.io/docs/guides/configuration-guide/openstack/#customization-of-the-service-configurations
The example specifies
```ini
[DEFAULT]
cpu_allocation_ratio = 16.0
ram_allocation_ratio = 5.0
```
Two comments:
* According to [`nova.conf` documentation](https://docs.openstack.org/nova/latest/configuration/config.html), we probably don't want to specify `XXX_allocation_ratio`, as that overrides all specific settings that we might want to apply in the placement service (if we e.g. want to have host aggregates that allow insanely high oversubscription for `L` flavors or no oversubscription for `C` flavors). I think we should rather specify `initial_XXX_allocation_ratio` here. (This was changed in ~2018.)
* The numbers don't conform with [SCS requirements](https://docs.scs.community/standards/scs-0100-v3-flavor-naming). We don't want ram oversubscription and would limit cpu to 3x (when hyperthreading is enabled) resp. 5x (without hyperthreading). This is close to the modern OpenStack defaults (which is 4x, used to be 16x).

So here would be my proposed text:
8<------------------------
```ini
[DEFAULT]
initial_cpu_allocation_ratio = 3.0
initial_ram_allocation_ratio = 1.0
initial_disk_allocation_ratio = 1.0
```
Note that the numbers shown here with an `initial_cpu_allocation_ratio` of 3.0 do match the requirements of the `SCS-nV-*` (moderate oversubscription) flavors. If you do not use SMT/hyperthreading, SCS would allow 5.0 here (for the `V` flavors). 
8<------------------------

Sidenote: We should of course also make sure that the defaults in the config repos have reasonable numbers.
I see 4/1/1 on my CiaB system which is at least close. (I have HT enabled, so I will change it to 3/1/1)

PS: Thanks to @frosty-geek for pointing me to this.

**Comment by berendt** [comment]
It's a random example to describe how to use an overlay configuration for an OpenStack service. Feel free to change to other values. If it is confusing, perhaps take totally absurd values (999.0)?

**Comment by frosty-geek** [comment]
Well I would rather have "good" examples in there which could be just copy&pasted or have XYZ in there if they are not to be taken from the documentation. 

Being a Debian Guy, I remember my "admin experience" differed alot when I just installed a software on debian compared to other distros. Debian "most of the time" (to not say always) gave me a "production" ready config which was 90% there where I wanted it compared to other distros having me to fix the config before I could start up the service.

So either go with XYZ if you don't want CSPs to use the values in the config and let them look it up upstream or provide examples which are 90% there already (if we already have standards or best practices touching that topic).

HTH,
Ralf
