### ISSUE TITLE
ceph: add playbook to create openstack pools

### ISSUE THREAD

**Issue by berendt** [osism/issues#909]
Required because of https://github.com/ceph/ceph-ansible/commit/9c467e41b39af63dec9a0b237b550edb9c57da85.

**Comment by killermoehre** [comment]
@berendt because this topic matches: how does one create additional ceph keys for additional ceph pools? `osism apply copy-ceph-keys` fails, as we don't use the default key names in the configuration, but something like `manila_s1` and `manila_s2` to distinguish between stages.

**Comment by berendt** [comment]
> @berendt because this topic matches: how does one create additional ceph keys for additional ceph pools? `osism apply copy-ceph-keys` fails, as we don't use the default key names in the configuration, but something like `manila_s1` and `manila_s2` to distinguish between stages.

That's not possible at the moment. It's a good extension. But we would have to introduce some kind of naming scheme for this to work. Otherwise we can't assign the keys to the right locations.

At the moment it's already possible to fetch all keys with ceph-fetch-keys. They are available in the /share/FSID/etc/ceph directory inside the manager service. Maybe we should add an option to the copy-ceph-keys play that only copies all keys from there to the outside?

The playbook for creating pools only already exists: ceph-pools.

**Comment by killermoehre** [comment]
I'm happy to write my own playbook for creating ceph client keys. I already did for automating OpenStack zone creation.

I assume I create the appropriate `/opt/configuration/environment/ceph/playbook-create-custom-ceph-keys.yml`?

**Comment by killermoehre** [comment]
Do I have access to the ansible ceph module in custom? Or is this some extra dependency I need to install? How would I call the appropriate actions?

**Comment by berendt** [comment]
> Do I have access to the ansible ceph module in custom? Or is this some extra dependency I need to install? How would I call the appropriate actions?

I'm not sure. You have to try it. It probably won't work. Can you replace the run.sh script in ceph-ansible and test it?
