### ISSUE TITLE
OVN-Probe Interval  options 

### ISSUE THREAD

**Issue by matfechner** [osism/issues#91]
Hi @berendt 

here are some Issues which will improve the OVN behavior

[OVN]

ovn controller:

ovn-openflow-probe-interval="60"
external_ids:ovn-remote-probe-interval="60"

ovn-sb

inactivity_probe="60"

ovn-nb

inactivity_probe="60"

i think we should set the settings here:

https://opendev.org/openstack/kolla-ansible/src/branch/master/ansible/roles/ovn/templates

[OVS]

in  ovs

seems to set inactivity_probe="60"

**Comment by matfechner** [comment]
ovn-openflow-probe-interval="60" is (optional)

**Comment by berendt** [comment]
@matfechner Should we tackle this directly in the Kolla-Ansible upstream or in our ansible-defaults?

**Comment by matfechner** [comment]
Hi @berendt, that is a good question but i think, we should bring it upstream !

**Comment by frosty-geek** [comment]
looks like https://bugs.launchpad.net/neutron/+bug/1935842 adresses this already and has been back ported to victoria + wallaby
