### ISSUE TITLE
scs-compliance-check image source mismatch: https://swift.services.a.regiocloud.tech/xyz matches none of these prefixes

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#913]
Images installed via OSISM CLI do not pass the v4 IaaS compliance check:
```
dragon@manager01:~$ osism manage images --hide --hypervisor kvm --cloud admin --latest --filter "Debian 11|Ubuntu 22.04|Ubuntu 22.04 Minimal|Cirros|Debian 12"
```

```
dragon@manager01:~$ ./scs-compliance-check.py -V v4  ./scs-compatible-iaas.yaml --os-cloud=xyz

[...]
Testing standard Standard images ...
Reference: https://raw.githubusercontent.com/SovereignCloudStack/standards/main/Standards/scs-0104-v1-standard-images.md ...
ERROR: Image 'Ubuntu 22.04' source mismatch: https://swift.services.a.regiocloud.tech/swift/v1/AUTH_b182637428444b9aa302bb8d5a5a
ERROR: Image 'Debian 12' source mismatch: https://swift.services.a.regiocloud.tech/swift/v1/AUTH_b182637428444b9aa302bb8d5a5a418c/openstack-images/debian-12/20230826-debian-12.qcow2 matches none of these prefixes: https://cloud.debian.org/images/cloud/bookworm/, https://cdimage.debian.org/cdimage/cloud/bookworm/
ERROR: Image 'Debian 11' source mismatch: https://swift.services.a.regiocloud.tech/swift/v1/AUTH_b182637428444b9aa302bb8d5a5a418c/openstack-images/debian-11/20230802-debian-11.qcow2 matches none of these prefixes: https://cloud.debian.org/images/cloud/bullseye/, https://cdimage.debian.org/cdimage/cloud/bullseye/
[...]
```

Should the https://swift.services.a.regiocloud.tech URL be added to the allowed prefixes?

**Comment by berendt** [comment]
Probably makes sense. We mirror the images there.

**Comment by Nils98Ar** [comment]
@mbuechse What do you think?

**Comment by mbuechse** [comment]
No, the original source is necessary. We have talked about this at length and even changed the image manager accordingly. I will look up the corresponding issues and link them here.

**Comment by berendt** [comment]
> No, the original source is necessary. We have talked about this at length and even changed the image manager accordingly. I will look up the corresponding issues and link them here.

I remember and that's why I added the original sources to the image definitions. However, these are not yet stored in the image itself after the upload. This then needs to be fixed.

`image_source` is the mirror URL at the moment and should be the `latest_url‎`.

**Comment by berendt** [comment]
> This is the issue that addressed preserving the original URL: [osism/openstack-image-manager#634](https://github.com/osism/openstack-image-manager/issues/634) This is the corresponding pull request: [osism/openstack-image-manager#635](https://github.com/osism/openstack-image-manager/pull/635) However, it seems that @berendt broke it with this commit: [osism/openstack-image-manager@11c4d1c](https://github.com/osism/openstack-image-manager/commit/11c4d1c89ccf2417b07076b0977330c79f1e30b9) What has happened???

Oh, I'll have a look tomorrow. I think I fixed it the wrong way round. There were problems in the mirror update script.

**Comment by mbuechse** [comment]
@berendt any news?

**Comment by artificial-intelligence** [comment]
I guess my fix should work, but I haven't tested it!

**Comment by berendt** [comment]
In the image definitions `url` has to be the URL of the image on the mirror. This is the URL we use for the Glance import task.

We added `latest_url` to the image definitions to point to the original source of the image.

At the moment we add `url` to the uploaded image as property `image_source`. I think we should add something like `image_original_source` there.

**Comment by mbuechse** [comment]
You will see it if you `grep` for `mirror_url` here: https://github.com/osism/openstack-image-manager/blob/main/openstack_image_manager/manage.py

**Comment by berendt** [comment]
This is done with the last image manager release. On the environments, the problem is solved over time by updating/rotating the images.
