### ISSUE TITLE
fluentd do not collect openstack logs over all time

### ISSUE THREAD

**Issue by muellerbe** [osism/issues#92]
after some time fluentd do not collect openstack logs for elasticsearch

**Comment by grawert** [comment]
This image seems to be working fine: ```quay.io/osism/fluentd:wallaby 3041e75a61f7```

**Comment by berendt** [comment]
Check this in the testbed and try to establish some automagic test.

**Comment by berendt** [comment]
@matfechner Please take care of this until the end of this week.

**Comment by berendt** [comment]
We cannot reproduce the behavior with Xena at the moment. Please reopen if the problem persists and provide more details on how to reproduce it.
