### ISSUE TITLE
7.0.0: Cleaning PENDING_CREATE/_DELETE loadbalancers can fail

### ISSUE THREAD

**Issue by garloff** [osism/issues#925]
After the wrong jobboard setting, we found lots of stuck loadbalancers in PENDING_CREATE or PENDING_DELETE
And the process to set them to ERROR and then clean up as admin does not work.

Here's what @maliblatt reported:
> it seems we have a lot of loadbalancers stuck in some PENDING states that can not be deleted properly. From the logs I can see that we seem to run into a bug which described here: https://bugs.launchpad.net/octavia/+bug/2037951
> A fix seems to be produced and is available in openstack/octavia 14.0.0.0rc1 ... Seems that there is no backport yet.
> I will have to take a deeper look into that to be able to remove all the stucking loadbalancers.

**Comment by berendt** [comment]
Backport pending: https://review.opendev.org/c/openstack/octavia/+/913506

**Comment by garloff** [comment]
Perfect, thanks!
