### ISSUE TITLE
cookiecutter fails with TARGET_UID not provided

### ISSUE THREAD

**Issue by l4z41** [osism/issues#931]
Hello, I'm trying to set up a new configuration repository after [this](https://docs.scs.community/docs/iaas/guides/configuration-guide/configuration-repository/#creating-a-new-configuration-repository) documentation and getting following error:
```
osism@scs-seed-1:~$ sudo docker run --rm -v $(pwd)/output:/output -it quay.io/osism/cookiecutter
Unable to find image 'quay.io/osism/cookiecutter:latest' locally
latest: Pulling from osism/cookiecutter
4abcf2066143: Pull complete
c3cdf40b8bda: Pull complete
d8b8280c2671: Pull complete
958655e35787: Pull complete
a5138315a319: Pull complete
46d56e2ca655: Pull complete
0624df4e33d0: Pull complete
b3ba87767d1a: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:455ec3138cc460ee3ed9a6f4ccf7e392f129de7fe10f9f737ec961f2dc482823
Status: Downloaded newer image for quay.io/osism/cookiecutter:latest
ERROR: ENVIRONMENT VARIABLE TARGET_UID IS NOT PROVIDED
```
It is not documented to set the environment variable and the only prior step is to create directory `output`. How to proceed for creation of a configuration directory?

**Comment by berendt** [comment]
Please have a look here: https://github.com/osism/osism.github.io/pull/310/files#diff-655d71d263525fcc417ff0798be833182c9ca47c8a3565bd41df58040550d663R88

I will try to merge this PR later this day.
