### ISSUE TITLE
change OSDs deployment behavior

### ISSUE THREAD

**Issue by rmueller-b1** [osism/issues#935]
Hello,
I am not sure if that is a feature request or not.
My issue is that at the end of a deployment of new OSDs ALL of them are getting restarted including already existing ones. That causes a disruption in productive Ceph applications. For some customers that will require a change window and has to be done every time when new nodes are added or if a disk has to be replaced due to a failure.
Is it possible to stop a restart of existing OSDs or at least get a delay between the restarts like it is in the rolling-upgrade command?
Regards

**Comment by berendt** [comment]
Do you add new OSDs with `osism apply ceph-osds` or with `osism apply ceph-osds -l HOST`?

**Comment by rmueller-b1** [comment]
`osism apply ceph-osds` because we had issues with limits in the past.

**Comment by berendt** [comment]
I think you have to use -l for the moment to avoid the restarts of all OSDs in the end.

I'm still looking into adding something to the handler for restarts and making serial configurable in the play for ceph-osds.

**Comment by rmueller-b1** [comment]
What is the current state of this issue? Our customer needs the extra OSDs ASAP. We would be fine with a sleep for one minute or more after each restart of an OSD container. The playbook would run for like 2-3 hours but that is better than a disruption in production. It also doesn't have to be in an official release for now. We are fine with manually adding some lines to the ceph playbook(s).
Using a limiter is also not a suitable option as it messes with the numbers of the OSDs which causes more issues than it solves.

**Comment by berendt** [comment]
With https://github.com/osism/container-image-ceph-ansible/blob/main/patches/stable-7.0/ceph-handler-skip-and-throttle.patch you now have 2 options. This will be included in OSISM 7.0.3 (probably end of April).  For you specific case you can edit the /ansible/roles/ceph-handler/tasks/handler_osds.yml file in the ceph-ansible container.

1. throttle the restarts (https://osism.tech/docs/guides/deploy-guide/services/ceph#throttling-service-restarts)

I think that could also be the default. It is actually best to treat the OSDs one after the other.

```
osism apply ceph-osds -e ceph_handler_osds_restart_throttle=1
```

2. skip the restarts (https://osism.tech/docs/guides/deploy-guide/services/ceph#avoiding-service-restarts)

This makes the most sense when adding new OSDs I think.

```
osism apply ceph-osds -e ceph_handler_osds_restart=False
```

**Comment by rmueller-b1** [comment]
What is the current state of this issue? Our customer needs the extra OSDs ASAP. We would be fine with a sleep for one minute or more after each restart of an OSD container. The playbook would run for like 2-3 hours but that is better than a disruption in production. It also doesn't have to be in an official release for now. We are fine with manually adding some lines to the ceph playbook(s).
Using a limiter is also not a suitable option as it messes with the numbers of the OSDs which causes more issues than it solves.

**Comment by rmueller-b1** [comment]
I have tested the option to skip the restart and it was working fine. Thanks

**Comment by berendt** [comment]
Thanks for the test.
