### ISSUE TITLE
Use '^\.zuul\.yaml$' in .zuul.yaml files

### ISSUE THREAD

**Issue by berendt** [osism/issues#957]
Use `'^\.zuul\.yaml$'` instead of `'^.zuul.yaml$'`. Check all .zuul.yaml files.

_Originally posted by @berendt in https://github.com/osism/ansible-collection-commons/issues/615#issuecomment-2033938196_

**Comment by sbstnnmnn** [comment]
Validations will be fixed here:
https://github.com/osism/ansible-collection-validations/pull/130

Fixing this in the commons was the intention here:
https://github.com/osism/ansible-collection-commons/pull/613
And is fixed here:
https://github.com/osism/ansible-collection-commons/pull/615

It has not yet been touched in the services.
