### ISSUE TITLE
Ceph Drain node

### ISSUE THREAD

**Issue by killermoehre** [osism/issues#964]
Hi,

$customer is asking on how to drain a ceph node with a simple command. https://osism.tech/docs/guides/operations-guide/ceph#remove-a-single-osd-node is empty at this point.

Is there a nice `osism apply` command for this?

**Comment by berendt** [comment]
> Also, how can I add back the OSDs removed via https://osism.tech/docs/guides/operations-guide/ceph#remove-an-osd-removing-it-completely-not-reprovisioning-it-again-without-double-rebalance? Even `osism apply ceph-osds` doesn't add them back. Is this really a task done by hand?

With ceph-ansible you have to do a lot by hand, yes. That will change in the future when Rook is usable.

**Comment by berendt** [comment]
> Hi,
> 
> $customer is asking on how to drain a ceph node with a simple command. https://osism.tech/docs/guides/operations-guide/ceph#remove-a-single-osd-node is empty at this point.
> 
> Is there a nice `osism apply` command for this?

There is currently no play for it. What exactly is the expected result? Then I'll see if we can add it. Due to the switch to Rook, we are no longer doing many new features with Ceph-Ansible at the moment.

**Comment by killermoehre** [comment]
The expected result is, that I get my 10 OSD back into the cluster after removing them according to the inventory.

**Comment by berendt** [comment]
```
$ docker exec -it ceph-mon-com2001 ceph osd tree
ID  CLASS  WEIGHT     TYPE NAME         STATUS  REWEIGHT  PRI-AFF
-1         111.76794  root default
-3          37.25598      host com2001
 0    hdd    9.31400          osd.0         up   1.00000  1.00000
 3    hdd    9.31400          osd.3         up   1.00000  1.00000
 6    hdd    9.31400          osd.6         up   1.00000  1.00000
10    hdd    9.31400          osd.10        up  1.00000  1.00000
-5          37.25598      host com2005
 1    hdd    9.31400          osd.1         up   1.00000  1.00000
 4    hdd    9.31400          osd.4         up   1.00000  1.00000
 7    hdd    9.31400          osd.7         up   1.00000  1.00000
 9    hdd    9.31400          osd.9         up   1.00000  1.00000
-7          37.25598      host com2009
 2    hdd    9.31400          osd.2         up   1.00000  1.00000
 5    hdd    9.31400          osd.5         up   1.00000  1.00000
 8    hdd    9.31400          osd.8         up   1.00000  1.00000
11    hdd    9.31400          osd.11        up   1.00000  1.00000
-9                 0      host com2021
12    hdd          0          osd.12        up         0  1.00000
13    hdd          0          osd.13        up         0  1.00000
14    hdd          0          osd.14        up         0  1.00000
15    hdd          0          osd.15        up         0  1.00000
```

**Comment by berendt** [comment]
I close this as done. The play itself is there. Rebalance in advance is a manual step and docs are available.
