### ISSUE TITLE
Document how to add SSL certificate to Ceph Object Gateway (RGW)

### ISSUE THREAD

**Issue by b1knoll** [osism/issues#966]
Hello,

please document how to add an SSL certificate to the RGW in Ceph.

There are many ways to accomplish this however it should included in the OSISM Ceph configuration.

For example somewhere under:

configuration/environments/ceph/configuration.yml

Or describe how to add it manually.

Best,
Marc

**Comment by b1knoll** [comment]
This is done by adding the following lines to:

/etc/ceph/ceph.conf

on every node where an RGW shall be deployed:

rgw frontends =  beast endpoint=${ip_address}:${port} ssl_endpoint=${ip_address}:${port} ssl_certificate=/path/to/cer ssl_private_key=/path/to/key

Of course one can edit:

configuration/environments/ceph/configuration.yml

and add it to the:

ceph_conf_overrides

However, what are the right Ansible variables to set an IP address for a single RGW when deploying more than one RGW?

For example when editing:

/configuration/inventory/host_vars/host_name.yml

radosgw_address: ${ip}

So under:

ceph_conf_overrides

it should look like this:

"rgw frontends":  beast endpoint={{ hostvars[rgw_ip_address]['ansible_hostname'] }}:8081 ssl_endpoint={{ hostvars[rgw_ip_address]['ansible_hostname'] }}:8333 ssl_certificate=/path/to/cer ssl_private_key=path/to/key

Can you tell me how to define and use:

{{ hostvars[rgw_ip_address]['ansible_hostname'] }}

Best,
Marc

**Comment by berendt** [comment]
We currently only support a single Ceph RGW and not several of them. We provide this single Ceph RGW via the HAProxy. Perhaps it is sufficient to add your own parameters such as `rgw_ip_address_0`, `rgw_ip_address_1`, ... and to use these if they are only used at this point.

**Comment by berendt** [comment]
No longer relevant.
