### ISSUE TITLE
manager: connection with broker refused

### ISSUE THREAD

**Issue by b1knoll** [osism/issues#967]
Hello,

after upgrading OSISM we see the follwoing message:

 ERROR | osism.services.listener:main:191 - Connection with broker refused. Retry in 60 seconds.

What can cause this error?

Best,
Marc

**Comment by berendt** [comment]
This can be ignored. You have enabled the manager listener service without configuring the manager broker service. Set `enable_listener: false` in `enviroments/manager/configuration.yml` to disable the listener service.
