### ISSUE TITLE
Upgrade ceph client to Reef

### ISSUE THREAD

**Issue by b1knoll** [osism/issues#968]
Hello,

upgraded to Ceph Reef.

However after applying:

osism apply cephclient

The client stays in Version 17.2.7.

Please upgrade to the Reef client version.

Best,
Marc

**Comment by berendt** [comment]
We do not yet support Ceph Reef. If you already want to use the ceph client for Reef set `cephclient_tag: reef` in `environments/infrastructure/configuration.yml`.

**Comment by b1knoll** [comment]
environments/infrastructure/configuration.yml? You're sure? There is only one line regarding netbox, yet.

**Comment by b1knoll** [comment]
This worked.
