### ISSUE TITLE
ceph command not working

### ISSUE THREAD

**Issue by b1knoll** [osism/issues#969]
Hello,

suddenly the ceph command from the manager does not work anymore.

ceph -s
2024-04-16T16:53:02.422+0000 7f548b7fe700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]

[errno 1] RADOS permission error (error connecting to the cluster)

The client seems to be missing the needed credentials. Not sure here.

Where are they? It is not /etc/ceph.

Could a redeployment of the ceph client container be the solution? How to do that?

Running this command from one of the storage nodes does work however.

Best,
Marc

**Comment by berendt** [comment]
For Ceph Reef?

**Comment by b1knoll** [comment]
Yes, for Reef. But it is running without errors on another cluster where we upgraded to Reef already. So this cannot be the cause. It is something about the credentials, I guess.

**Comment by b1knoll** [comment]
Upgrading the client to Ceph 18 worked, however I still get the error mentioned above.

**Comment by berendt** [comment]
No longer relevant.

**Comment by b1knoll** [comment]
For documentation:

The reason was an empty

ceph.client.admin.keyring

in

/opt/cephclient/configuration

So fill the file with the credentials normaly found under

/etc/ceph/ceph.client.admin.keyring

and everything works again.

Please document this.

This is not a Reef error!

Best,
Marc

**Comment by berendt** [comment]
This is already documented: https://osism.tech/docs/guides/deploy-guide/services/ceph (2nd step).
