### ISSUE TITLE
How to configure Grafana and Prometheus just for an OSISM Ceph Cluster

### ISSUE THREAD

**Issue by b1knoll** [osism/issues#971]
Hello,

I deployed a Ceph cluster without Openstack.

How to configure Grafana and Prometheus to use it with the Ceph cluster?

Best,
Marc

**Comment by berendt** [comment]
Both Grafana and the Prometheus service assume that you have deployed both OpenStack and Ceph. This means that all exporters are deployed and all prepared dashboards are imported.

If you only want to use Prometheus itself without the exporters, you would have to deactivate them all in `environments/kolla/configuration.yml`:

```
enable_prometheus_haproxy_exporter: "no"
enable_prometheus_mysqld_exporter: "no"
enable_prometheus_node_exporter: "no"
enable_prometheus_memcached_exporter: "no"
enable_prometheus_cadvisor: "no"
enable_prometheus_fluentd_integration: "no"
enable_prometheus_openstack_exporter: "no"
enable_prometheus_elasticsearch_exporter: "no"
enable_prometheus_blackbox_exporter: "no"
enable_prometheus_rabbitmq_exporter: "no"
enable_prometheus_libvirt_exporter: "no"
```

Then deploy prometheus, grafana and all necessary dependencies (mariadb, loadbalancer, common). I don't know if that makes sense in this scenario, it seems like a lot of overhead.

**Comment by berendt** [comment]
No longer relevant.
