### ISSUE TITLE
Rebuild manager node

### ISSUE THREAD

**Issue by b1knoll** [osism/issues#976]
Hello,

is it possible to totally rebuild a manager node whilst the services like Openstack or Ceph are running?

No redeployment needed. Services are running fine.

Best,
Marc

**Comment by berendt** [comment]
Yes, that's possible. You should make a copy of the contents inside the `manager_share` volume. Logs from Ansible are lost. If you have used Netbox, you should create a backup of the database and restore it as you often have manual changes there.

**Comment by b1knoll** [comment]
Hello,

thanks. What is the manager_share volume? I do not find anything about it in the documentation.

The reason for rebuilding is the not working ceph command on the manager node.

So I would like to redeploy the ceph-ansible container or every single container on the manager node.

Best,
Marc

**Comment by berendt** [comment]
The `manager_share` is a Docker volume on the manager node.

```
dragon@testbed-manager:~$ docker volume ls
DRIVER    VOLUME NAME
local     3d49ef8fa6047aed67a25ac8b4333177147c46463a2fc2d1d21724c27aca5b63
local     3e8352b2fdb13b4df354280bdeb0b4126f55c1d8c11be6e40257054005e5b122
local     04f558d5164f023fe8944aaee0850599f0e0550237d57510fe145fc4076ec51c
local     645cee121788b45f4665fb98f465a5a79f1ac1139b3a4e2705c8b5b0d15a7c47
local     a78d50467bbaceb564b300f8f9c3ff8fc7cbdbe5337e97b7c22a5695efb5e326
local     d0b4b58c999e9560596eb703bd09dea371599e5cde9675e4ad648bc5cfa0f697
local     db3527901f3d3aee787bc14a134477f30cd722e076a2c61e4e1acbbf7ed1068d
local     f6baaf5098c63712790336422ac941d76d685161d431870b0736409340d36546
local     fa2482b998ae0b2c5fa8d5947daffcc1363a64cef8b14ad5195a9abb09a520c8
local     fluentd_data
local     kolla_logs
local     manager_cache
local     manager_interface
local     manager_inventory_reconciler
local     manager_logs
local     manager_share
local     netbox_redis
local     nexus_data
local     nexus_logback
local     squid_squid
```

**Comment by b1knoll** [comment]
Hello,

alright, fine.

So can you please explain how to make the copy?

And then? Stop and kill everything? How to redeploy? I need the manager containers. No redeployment of Openstack or Ceph or something else.

Best,
Marc
