### ISSUE TITLE
Containers on hosts trail behind manager config / container repo builds

### ISSUE THREAD

**Issue by linwalth** [osism/issues#98]
I have run into this problem rather frequently: I have updated the manager, which means new kolla-playbooks and configurations - but some of the containers in the infrastructure then cannot handle the new configurations (ex: cadvisor) which makes a full recreation of said containers necessary.

Is there a way to refresh the container images on the hosts in such a way that the newest image for the existing and rolled-out kolla-revision is rolled out wherever needed?

**Comment by berendt** [comment]
Sure. You can use the refresh-containers action for this purpose. E.g. ```osism-kolla refresh-containers common``` will refresh all containers defined in the ```common``` role.

**Comment by linwalth** [comment]
Thank you - That is useful knowledge. Is there anything comparable for other containers beyond the common role?

**Comment by linwalth** [comment]
I misread you there. I understand now - I can refresh just about anything by running the osism-kolla refresh-containers command. Consider my problem solved, then :)
