### ISSUE TITLE
Bug when creating a fully-populated LB with allowed_cidr 

### ISSUE THREAD

**Issue by mario-minners** [osism/issues#980]
We were hit by this bug
[Bug when creating a fully-populated LB with allowed_cidr ](https://bugs.launchpad.net/octavia/+bug/2057751)

Would be nice to have an patched octavia image

**Comment by berendt** [comment]
Cherry picks:

* https://review.opendev.org/c/openstack/octavia/+/916100 (stable/2023.2)
* https://review.opendev.org/c/openstack/octavia/+/916099 (stable/2024.1)

**Comment by berendt** [comment]
CI verified. We‘ve to wait for core approval.

**Comment by berendt** [comment]
+2 by Tom Weininger, will probably merged tomorrow.

**Comment by berendt** [comment]
Backports merged. New images will be available tomorrow. For the moment you can use them by overwriting the octavia tag. We plan to do the next OSISM release end of April and will included updated images there as well. Is this okay for the moment?

Set `octavia_tag` in `environments/kolla/images.yml`:

``` 
octavia_tag: "2023.2"
```
