### ISSUE TITLE
Check/Replace python alpine container images

### ISSUE THREAD

**Issue by berendt** [osism/issues#981]
Marc mentioned in https://github.com/SovereignCloudStack/standards/commit/065465cd1abd813831f5dfa9c607e4f7511f63d1 that it could makes sense to not use the python alpine container images.

More information: https://pythonspeed.com/articles/alpine-docker-python/

Check if we still use python alpine container images somewhere and if it makese sense replace them with the non-alpine container images.

**Comment by berendt** [comment]
- [ ] osism/container-images/seed
- [ ] osism/container-images/openstackclient

**Comment by Belgeron** [comment]
start working on them to move to python:*-slim-bookwork

**Comment by berendt** [comment]
After an initial evaluation by Andreas, this was discarded. Not worth the future maintenance and savings at this point.
