### ISSUE TITLE
handle overflow of logs from docker

### ISSUE THREAD

**Issue by artificial-intelligence** [osism/issues#990]
Docker itself has afaik no way to manage logs (truncate, rotate etc).

on most systems running docker, cron is not installed, but we can use a systemd timer instead to start a simple bash script.

I prepared some scripts to handle this:

https://gist.github.com/artificial-intelligence/2ec65e808ed5f6d131d365943745136d

Question: how/where exactly to integrate this? `ansible-collection-serices` repo?

I'm not so sure.

**Comment by Belgeron** [comment]
You can manage Container logs within Docker:

See:
# more /etc/docker/daemon.json 
{
    "data-root": "/srv/docker",
    "log-driver": "json-file",
    "log-opts": {"max-size": "100m", "max-file": "3"}
}

3 Files, rotate at 100m.

After editing the daemon.json, Docker must be restarted, works also for other log-drivers, as i'm now aware how the actual setup is

**Comment by artificial-intelligence** [comment]
Thanks for that! I actually looked at the docker docs because I remembered something like this fuzzily but didn't find it again, thus I wrote the short script. Your solution should be better though, so thanks!.

**Comment by berendt** [comment]
That’s already part of osism.services.docker: https://github.com/osism/ansible-collection-services/blob/main/roles/docker/defaults/main.yml#L27-L31

Looks like it is not working like expected?
